### ISSUE TITLE
Provide unified python interface to Fluent

### ISSUE THREAD

**Issue by tomrobin-teschner** [ansys/pyfluent#1039]
### 📝 Description of the feature

I am thrilled to see the addition of PyFluent to the latest Fluent release which stands great chance of replacing all of my cobbled together journal scripts which are not really that readable (especially the parts where I do arithmetic). Python is a great wrapper for all of this functionality and I have already found the meshing workflow to be easier to automate with the python-based workflow scripts.

I looked through the documentation and [example for the mixing elbow](https://fluent.docs.pyansys.com/examples/00-fluent/mixing_elbow_settings_api.html#sphx-glr-examples-00-fluent-mixing-elbow-settings-api-py) but to my disappointment I saw the following code

```python
if solver.get_fluent_version() == "22.2.0":
    solver.setup.materials.copy_database_material_by_name(
        type="fluid", name="water-liquid"
    )
else:
    solver.setup.materials.database.copy_by_name(type="fluid", name="water-liquid")
```

This is the part which is already a huge turn-off for me when doing journal scripting, i.e. checking that each of my command works after upgrading to the latest fluent version (in the end I mostly stay with the version for which I created the journal file or use the "set-tui-version" command but even that seems like a hack). Unfortunately, it seems that there is no real interest in keeping a stable tui menu structure and it seems this unstable syntax is mirrored in the python implementation. This is odd and in stark contrast to what the rest of the (software) industry is trying to achieve, having each new release of fluent break existing scripts (making either the scripts useless or putting a deterant on upgrading to the latest version).

There is an opportunity here to fix this by establishing a proper API to fluent from within the python layer and I would love to see this realised.

### 💡 Steps for implementing the feature

Taking the same example again:

```python
if solver.get_fluent_version() == "22.2.0":
    solver.setup.materials.copy_database_material_by_name(
        type="fluid", name="water-liquid"
    )
else:
    solver.setup.materials.database.copy_by_name(type="fluid", name="water-liquid")
```
It would be more sensible to have an internal implementation within the PyFluent core module as follows:

```python
# within PyFluent core module
class PyFluent: # well, where ever this is implemented, I did not check
...
    def copy_material_by_name(self, type, name):
        if solver.get_fluent_version() == "22.2.0":
            solver.setup.materials.copy_database_material_by_name(type, name)
        elif solver.get_fluent_version() == "22.1.0":
            # version 2022R1 implementation
        elif solver.get_fluent_version() == "21.2.0":
            # version 2021R2 implementation
        # etc ...
        else:
            solver.setup.materials.database.copy_by_name(type, name)
```
This will allow the user to have a unified call in their script (regardless of the fluent version) as the following:

```python
solver.setup.copy_material_by_name(type="fluid", name="water-liquid")
```

In this way, scripting in Fluent will be exponentially more powerful (in my view). This will also allow to have a sensible version numbing of the PyFluent module, i.e. once a stable version and API is establised and PyFluent is in version 1.x.x, any code breaking changes can be communicated through an increment in the major version number and this can be independent from Fluent's release cycle. Otherwise PyFluent, at least to me, only adds syntactic sugar but no usefulness, if it does simply mirror existing functionality (journal scripts). I can see an interest to integrate that across ANSYS products (and hence to have a python implementation) but then again the above is even more so important if users will start using Fluent as part of their PyANSYS scripts. If each release of fluent is breaking their script, how are they supposed to know what is going wrong? Fluent needs a unified way of scripting, PyFluent has real potential to achieve that and I would love to see this happening.

**Comment by dnwillia-work** [comment]
Thanks for the great feedback!

Regarding your point about the settings interface versioning, you are right that this is not the way it should be.  This interface is not yet a released Fluent feature and one reason for that is we've not completed the work to facilitate making it backwards compatible from release to release.  So, this will come when the settings interface is a released feature for Fluent.

In the meantime, the PyFluent team decided that it was helpful to allow using it with the PyFluent library sooner rather than later because it already addresses many of the pitfalls of using the released `tui` interface and it allowed us to get some early feedback about the interface.  So, please feel free to share any additional feedback you have with us.

**Comment by tomrobin-teschner** [comment]
Hi Dan, great to hear this is already on your list and yes, I understand you are still pre 1.x.x so I am assuming (and hoping) the interface / api will still change. PyFluent is definitly something I'll be using quite a bit it seems and this will integrate nicely with other tools such as pytecplot or paraview. Cheers!

**Comment by seanpearsonuk** [comment]
@tomrobin-teschner 

this is from my prior conversation with @dnwillia-work :

"
I mandated that for tests _all those things_ are wrapped and in separate utility functions.
However, doing that means doing the APIs job, so it's moot whether it's right to do it.
But the tests would get very messy otherwise.
"

**Comment by tomrobin-teschner** [comment]
not just the tests, actual production scripts would look equally messy with if statements added for each new release (potentially). A clean interface would go along way here. I can see that this is not a trivial task with fluent's current tui API but worthwhile to have a think about if this could be addressed, especially since a complete new API is developed from scratch

**Comment by seanpearsonuk** [comment]
Sure, I'm not saying that production code wouldn't also look messy but I'm not promoting the idea of trying to do that ("actual production scripts... with if statements added for each new release").

"Customers who are doing large scale re-writes (from Scheme) now must start with TUI API IMHO. Anyone writing small verticals can use settings API and expect some rewrite later."
