### ISSUE TITLE
Syntax to Mark as updated in watertight workflow

### ISSUE THREAD

**Issue by pavankumarkonchada** [ansys/pyfluent#1081]
![image](https://user-images.githubusercontent.com/113668310/200795774-ecaeb832-756c-4a14-b531-e4fc4da2db7b.png)

**Comment by pavankumarkonchada** [comment]
Can u please help me in syntax of mark as updated on right click in pyfluent

**Comment by pavankumarkonchada** [comment]
meshing.workflow.TaskObject["Import Geometry"].Mark_As_Updated() 
This syntax not working

**Comment by pavankumarkonchada** [comment]
meshing.workflow.TaskObject['Import Geometry'].ForceUptoDate() 
This syntax is working but it prompts for a dialog box, is there any way we can proceed without dialog box popup

**Comment by pavankumarkonchada** [comment]
Please can any body help me in automatically ok button of dialog box getting clicked in pyfluent

**Comment by mkundu1** [comment]
If you want to just execute the task - `meshing.workflow.TaskObject['Import Geometry'].Execute()`

**Comment by pavankumarkonchada** [comment]
No I want to do mark all the tasks as mark as updated and then when it comes to volume meshing I want to insert new task and extrude the faces

**Comment by pavankumarkonchada** [comment]
But when I am using mark as updated I am getting the dialog box, I dont want that dialog box

**Comment by pavankumarkonchada** [comment]
Or else it should automatically get pressed ok

**Comment by pavankumarkonchada** [comment]
> If you want to just execute the task - `meshing.workflow.TaskObject['Import Geometry'].Execute()`

Any suggestion

**Comment by mkundu1** [comment]
This is a Fluent side issue - the function is asking for a confirmation prompt in the server. One alternative is to modify the internal state:
```
>>> meshing.workflow.TaskObject['Import Geometry'].State()
'Out-of-date'
>>> meshing.workflow.TaskObject['Import Geometry'].State.get_attrib_value("allowedValues")
['Out-of-date', 'Attention-required', 'Up-to-date', 'Forced-up-to-date']
>>> meshing.workflow.TaskObject['Import Geometry'].State = "Forced-up-to-date"
```

**Comment by seanpearsonuk** [comment]
We can reimplement the command in question by intercepting it in client code.
@prmukherj we can look at this in conjunction with other upcoming mwf updates.

**Comment by pavankumarkonchada** [comment]
> = "Forced-up-to-date"

Thank You Its working

**Comment by prmukherj** [comment]
In the enhanced meshing workflow one can just use:

>>> watertight.import_geometry.mark_as_updated()
