### ISSUE TITLE
Require clear, explicit naming throughout API, preferring GUI names

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#110]
Current example from the Settings API follows. We should aim to make everything clearly and explicitly named, and unabbreviated.
```
>>> root.setup.boundary_conditions.pressure_outlet['pressure-outlet-7'].get_state().keys()
dict_keys(['frame_of_reference', 'p', 'p_profile_multiplier', 't0', 'direction_spec', 'ke_spec', 'turb_intensity', 'turb_hydraulic_diam', 'p_backflow_spec_gen', 'prevent_reverse_flow', 'radial', 'avg_press_spec', 'targeted_mf_boundary'])
```

**Comment by seanpearsonuk** [comment]
TODO add US

**Comment by dnwillia-work** [comment]
I think we discussed this offline and decided on following PEP8, since it's an API.  We should publish our API naming guidelines.

**Comment by seanpearsonuk** [comment]
Reopened with focus on the current (2024R1) naming. The following is from my own observations and this is **not** comprehensive.
1. In the thermal section of boundary condition, temperature is still named `t`. In general, `temperature` is used throughout the API. Lower-case t indicates time anyway.
2. In the thermal section of boundary condition, `q` and `q_dot` names are used instead of full heat flux terminology. `heat_flux` appears within names elsewhere in the API.
3. In the thermal section of boundary condition, `caf` is used instead of `convective_augmentation_factor`.
4. In `non_reflecting_bc`, the abbreviations `general_nrbc` and `turbo_sepcific_nrbc` are used, which seems obscure.
5. Specific is misspelt in `turbo_sepcific_nrbc`.
6. In `perforated_wall`, there should at least be an underscore before injections in `ninjections`. Elsewhere in the API, we are using both `num_<items>` and `number_of_<items>`. We should settle on one form only.
7. Within boundary conditions (`perforated_wall.model_setup`) we have urf, which is termed `under_relaxation_factor` (preferred) elsewhere in the API.
8. We have `solution.methods.p_v_coupling` but pressure and velocity are generally fully named elsewhere.
9. In `solution.methods.discretization_scheme`, we have `mom`, `mp` and `k`. The UI does not use these abbreviations, nor are they universally used in the API. But you can find more examples of the same abbreviations scattered around the API.
10. Also within `methods`, we have `implicit_bodyforce_treatment` which should be `implicit_body_force_treatment`.
11.

**Comment by seanpearsonuk** [comment]
@gyeole @h-krishnan FYI. Thanks

**Comment by seanpearsonuk** [comment]
API much improved already - closing.
