### ISSUE TITLE
API to return number of iterations defined in case file

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#1149]
### 📝 Description of the feature

I would like to request for an API that returns number of iterations defined in the case file. 
This is required to write a custom journal script by optiSLang that calls iterate command. This command requires number of iterations as argument. We would like to give the default number of iterations as argument here. 

@seanpearsonuk @mkundu1

**Comment by seanpearsonuk** [comment]
Implemented as iter_count()
