### ISSUE TITLE
discrete_phase settings API includes contour options

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1158]
We should design model APIs carefully. This doesn't seem like an intrinsic property of the model. N.b.: the API reflects the GUI panel in this respect.
```
>>> s3.setup.models.discrete_phase.general_settings.contour_plotting_option.allowed_values()
['none', 'mean', 'mean-and-rms']
```

**Comment by seanpearsonuk** [comment]
#2006

**Comment by prmukherj** [comment]
Current state:
![Image](https://github.com/user-attachments/assets/047a46e5-d205-4bd5-83a1-dea4aeab2563)

**Comment by ansjschuetz** [comment]
Hello @seanpearsonuk (and @prmukherj )
although it may not look like it, this is indeed a sub-feature of Fluent's Euler/Lagrange multiphase model implementation:
It collects information from particles / trajectories passing through any cell and provides averaged phase properties (temperature, velocity,...) for mesh-based postprocessing (i.e., contours plots etc.).
Cf. [this Fluent User's Guide section](https://ansysproducthelpqa.win.ansys.com/account/secured?returnurl=/Views/Secured/corp/v252/en/flu_ug/flu_ug_sec_discrete_post.html%23flu_ug_pt_discrete_vars)

**Comment by seanpearsonuk** [comment]
@ansjschuetz We will close this now - thanks for the clarification
