### ISSUE TITLE
Migrating list queries and utility functions to pyfluent (meshing mode)

### ISSUE THREAD

**Issue by dnwillia-work** [ansys/pyfluent#1192]
### Discussed in https://github.com/pyansys/pyfluent/discussions/1111

<div type='discussions-op-text'>

<sup>Originally posted by **ansmhoeij** November 23, 2022</sup>
I am trying to migrate an existing meshing journal file that contains some query and utility functions. Is there a way to conveniently migrate these to PyFluent? All TUI commands seem to be available, but I wasn't able to find a way to pass scheme commands to the session. 

For instance I am trying to patch a list of un-referenced face zones. In a normal journal file I use something like this: 
```
(define zone-ids-to-patch (get-unreferenced-face-zones-of-filter '*) )
(ti-menu-load-string  ( format #f "/boundary/modify/auto-patch-holes ~a"
							zone-ids-to-patch
						 ) )	
```
However, I don't know how I would get the list of unreferenced face zones to PyFluent:
```Python
unreferenced_zones = session.meshing. ... ?
session.meshing.tui.boundary.modify.auto_patch_holes( unreferenced_zone[0], unreferenced_zone[1], ... )
```

Any suggestions on how I could work around this problem? Passing the scheme command as string could already work, but perhaps there is already a more elegant way to do this? 

In the end it comes down to being able to retrieve some properties/characteristics of the objects that are present in the Fluent session. Is there already a way to do this, or is this being considered? 

@seanpearsonuk. Any ideas?
</div>

**Comment by dnwillia-work** [comment]
Moved this from a discussion item.

**Comment by mkundu1** [comment]
This is now available: https://fluent.docs.pyansys.com/version/stable/api/general/services/meshing_queries.html.

There is a scope of improving the doc structure, we should move it from "General" section to "Meshing" section.

**Comment by hpohekar** [comment]
@mkundu1 @seanpearsonuk 

We will move `meshing_queries` to "General" section. We also have `meshing_utilities` which are not documented yet. What should be the ideal location for both `meshing_queries` and `meshing_utilities` ?

**Comment by seanpearsonuk** [comment]
@hpohekar Are they both aliases for the same thing due to a naming change after initial exposure?

**Comment by hpohekar** [comment]
> @hpohekar Are they both aliases for the same thing due to a naming change after initial exposure?

Yes but issue is that `meshing_queries` are around 100 while `meshing_utilities` are many.

`meshing_queries` does not contain all queries that we have implemented only first 100 using C++.

`meshing_utilites` contains all queries that we have implemented using FDL.

**Comment by hpohekar** [comment]
Yes, I agree. We can remove `meshing_queries` from PyFluent source code, documentation and PyConsole.
