### ISSUE TITLE
test units code with existing units-quantity attributes

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1204]
Settings API currently provides units_quantity attributes for some real parameters (under materials and boundary_conditions). These are string format, but we can start to test our code against this since "velocity" is equivalent to {"velocity":1}. In a separate issue, I will request some dict values for this attribute coming from the API.

**Comment by hpohekar** [comment]
We want to associate Unit Quantity Map ==> { Unit Quantity : power } with following things -

A) Real value solver setting 

`solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].vmag = 0.4` => { "Velocity" : 1 } = "m /s ^-1"

`solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].t = 293.15` => { "Temperature" : 1 } = "K"

B) Expression 

`solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].turb_hydraulic_diam = "4 [in]"` => { Length : 1 } => "m" not "in"

 we can construct Quantity using real value and unit used in above expression string. =>  "4 [in]" = Quantity(4, "in")     

C) Report Definition

`solver.solution.report_definitions.compute(report_defs=["torque"]) `=> { "Torque" : 1 } => "N m"

**Comment by hpohekar** [comment]
Following unit quantities are supported by `units-quantity` attribute.

Acceleration
Angle
Angular Acceleration
Angular Velocity
Area
Area Inverse
Density
Density Inverse
Concentration 
Current Density
Crank Angle 
Crank Angular Velocity 
Elec Capacity
Elec Capacity Density
Elec Concentration
Elec Conductivity
Elec Current
Elec Current Density
Elec Potential
Elec Resistance
Elec Resistivity
Force
Frequency
Heat Flux
Heat Generation Rate
Heat Transfer Coefficient
Ignition Energy 
Length
Length Inverse
Mass 
Mass Diffusivity
Mass Flow
Mag Flux Density
Mole Con Henry Const
Mole Specific Energy
Molec Wt
Moment 
Moment Of Inertia
None
Nucleation Rate
Number Density
Percentage
Power
Pressure
Soot Formation Constant Unit
Soot Limiting Nuclei Rate
Soot Linear Termination
Soot Pre Exponential Constant
Specific Area
Specific Energy
Specific Heat
Spring Constant
Surface Tension
Temperature
Temperature Inverse
Temperature Difference
Time
Time Inverse
Thermal Conductivity
Velocity
Viscosity
Viscosity Consistency Index
Voltage
Volume Flow Rate
Volume Inverse

**Comment by hpohekar** [comment]
Following unit quantities needs to be supported by `quantity_map_method`.

Area Inverse
Density Inverse 
Current Density
Crank Angle 
Crank Angular Velocity 
Elec Capacity
Elec Capacity Density
Elec Concentration
Elec Conductivity -> Electrical Conductivity
Elec Current
Elec Current Density -> Electric Current Density
Elec Potential
Elec Resistance -> Electrical Resistance
Elec Resistivity -> Electrical Resistivity
Heat Generation Rate -> Heat Generation
Ignition Energy 
Length Inverse
Mass Diffusivity 
Mag Flux Density -> Magnetic Flux Density
Mole Con Henry Const -> Molar Concentration Henry Coefficient
Mole Specific Energy
Molec Wt 
Moment Of Inertia -> Moment of Inertia of Area or Moment of Inertia of Mass
None
Nucleation Rate
Number Density
Percentage
Power
Soot Formation Constant Unit
Soot Limiting Nuclei Rate
Soot Linear Termination
Soot Pre Exponential Constant
Specific Area
Specific Heat
Spring Constant
Temperature Inverse 
Time Inverse -> Per Time
Viscosity
Viscosity Consistency Index
Voltage
Volume Flow Rate
Volume Inverse
