### ISSUE TITLE
Injection model issues

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1214]
```
session.setup.models.discrete_phase.general_settings.interaction.option = "coupled"
session.setup.models.discrete_phase.injections.create("spray_nozzle")
session.setup.models.discrete_phase.injections["spray_nozzle"].injection_type.option = "pressure-swirl-atomizer"
session.setup.models.discrete_phase.injections["spray_nozzle"].particle_type = "inert"
```

doesn't update `init_props` state. 

There are 2 issues:
1. The initial_props state in settings API is updated only if the injection panel is kept open in Fluent.
2. The injection commands aren't available at TUI for PyFluent.

**Comment by antonpersson-ba** [comment]
I'm having the same issue so would love to see this being worked on. In my case:

`solver.setup.models.discrete_phase.injections.create("injection-1")
 solver.setup.models.discrete_phase.injections["injection-1"].injection_type.option = "surface"
 pprint(solver.setup.models.discrete_phase.injections["injection-1"].initial_props())`

returns 

`{'diameter': {'option': 'uniform'},
'flow_rate': {'flow_rate': 1e-20},
'location': {'random_surface_inj': False, 'x': 0, 'y': 0, 'z': 0},
'velocity': {'use_face_normal_direction': False}}`

while it should have updated to something like

`{'diameter': {'diameter': 0.0001, 'option': 'uniform'},
 'flow_rate': {'scale_by_area': False, 'total_flow_rate': 1e-20},
 'location': {'injection_surfaces': [],
              'random_surface_inj': False},
 'velocity': {'use_face_normal_direction': False,
              'x_velocity': 0,
              'y_velocity': 0,
              'z_velocity': 0}}`

**Comment by seanpearsonuk** [comment]
@mkundu1 @antonpersson-ba I'm not able to reproduce this with the current 24R1 build. (`initial_values` now)

@mkundu1 any outstanding issues?
