### ISSUE TITLE
Improve client-side error messaging

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1260]
Play with the code, break the code. Assess the error messaging that comes out. Improve the error messages. Try- except at high level; pre-validation of input. Pre-validation of input means that we protect the backend from undefined behaviour.

**Comment by mkundu1** [comment]
Related - when launch_fluent fails, we should notify the launch path and launcher arguments with which Fluent was attempted to launch

**Comment by seanpearsonuk** [comment]
Another example is solver.rpvar(<invalid-rpvar-name>)

We could add allowed_values method for this
