### ISSUE TITLE
There is a bug in the fuel cell model setting contact resistance

### ISSUE THREAD

**Issue by xinJOBS** [ansys/pyfluent#1314]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Set the fuel cell model with contact internal resistance characters with brackets, intervals, etc., which pyfluent does not recognize.
solver.tui.define.models.addon_module(3)
![image](https://user-images.githubusercontent.com/43572105/215682731-0ba78f6f-c3e6-4786-826d-86c1a95cc22b.png)

![image](https://user-images.githubusercontent.com/43572105/215681936-7e03b2c7-16e3-404f-91c0-f6e51e6de131.png)
![image](https://user-images.githubusercontent.com/43572105/215681727-0fdfc125-51a2-4b09-b3c3-9b51a322ef26.png)
![image](https://user-images.githubusercontent.com/43572105/215681758-b85ffd90-c746-46dc-b2fe-955aaf470593.png)

### 📝 Steps to reproduce

solver.tui.define.models.addon_module(3)
solver.tui.define.models.resolved_MEA_fuelcells.enable_fc_model('yes')
solver.tui.define.models.resolved_MEA_fuelcells.advanced_setup.contact_resistivity(
'(105 . 1e-06 )', '(104 . 1e-06 )', (), 'no',
)
RuntimeError: CAR: invalid argument [1]: wrong type [not a pair]
Error Object: #f

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
pip install ansys-fluent-core
```

**Comment by seanpearsonuk** [comment]
@xinJOBS 

Please run the valid TUI commands directly in Fluent and record them into a Python journal. Then you can run the recorded journal in either the Fluent Python console or PyFluent. Please let us know the outcone. Thanks.

**Comment by prmukherj** [comment]
@xinJOBS, Please re-open if this issue is still reproducible only in PyFluent.
