### ISSUE TITLE
Use tox during CI runs

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1322]
While updating old release branches, we often see issues in CI runs due to conflicts between package versions in the release branches and latest development branches. As a long-term solution, we can configure our CIs to use tox which will run each job within separate python virtual environments. This can be done in all pyfluent repositories.

**Comment by hpohekar** [comment]
@mkundu1 

Do we need this now ?  as we are using poetry which creates virtual environment as per the requirement. [Poetry supports tox](https://python-poetry.org/docs/faq/#is-tox-supported). We can use tox if required otherwise we can close this.
