### ISSUE TITLE
Make nightly doc build resilient against bad Fl images

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1353]
Run nightly doc build iteratively against multiple images until successful, starting with the latest and going backwards.

**Comment by dnwillia-work** [comment]
Interesting, how could there be a bad Fluent image?

**Comment by seanpearsonuk** [comment]
@dnwillia-work the specific issue is in the format of docstrings from settings API. Non-compliant dostrings currently fail the build so we want to fix them up front in the PyFluent codegen procedure.

**Comment by dnwillia-work** [comment]
Yeah, I think we had done some basic alteration of the help strings in the code generator at some point.   eg: Add a period at the end of the strings if missing.  I guess you are seeing other non-compliance..
