### ISSUE TITLE
container-level operations missing in datamodel objects (covers more points)

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1419]
Python console in Fluent has:
```
>>> workflow.TaskObject()
{'TaskObject1': {'Arguments': {}, 'CommandName': 'ImportGeometry', ...
```
This is not supported in PyFluent. We should add that. N.b. Python console in Fluent does not have workflow.TaskObject.get_object_names() as supported by the solver settings API, so I will add a task for that in Fluent, as well as in PyFluent.

Furthermore, the solver settings API supports the following:
```
>>> inlets = [inlet for name, inlet in solver.setup.boundary_conditions.velocity_inlet.items()]
```
and in Python Console we have slightly different (list-like, not dict like containers) e.g.:
```
>>> for task in workflow.TaskObject:
...   print(task.display_name())
... 
Import Geometry
Add Local Sizing
Generate the Surface Mesh
Describe Geometry
Apply Share Topology
Enclose Fluid Regions (Capping)
Update Boundaries
Create Regions
Update Regions
Add Boundary Layers
Generate the Volume Mesh
```
but the above does not currently work in PyFluent.  We would want this to work in PyFluent. Try doing that first.

We should also try to emulate the settings dict-style version as shown above.
```
That is, we want full dict-like behaviour:
>>> for k in dict(a=1):
...   print(k)
...
a
>>> for k in dict(a=1).values():
...   print(k)
...
1
>>> for k, v in dict(a=1).items():
...   print(k, v)
...
a 1
>>>
```
Users of PyConsole might get a (nice) surprise.

**Comment by seanpearsonuk** [comment]
PyFluent:
```
>>> m2 = pf.launch_fluent(mode="meshing", show_gui=True, start_transcript=False)
>>> m2.workflow.TaskObject()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ANSYSDev\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 277, in __call__
    return self.get_state()
  File "C:\ANSYSDev\pyfluent\src\ansys\fluent\core\workflow.py", line 360, in __getattr__
    return getattr(self._task_container, attr)
AttributeError: 'TaskObject' object has no attribute 'get_state'
>>> m2.workflow.TaskObject.get_state()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ANSYSDev\pyfluent\src\ansys\fluent\core\workflow.py", line 360, in __getattr__
    return getattr(self._task_container, attr)
AttributeError: 'TaskObject' object has no attribute 'get_state'
>>>
```

**Comment by prmukherj** [comment]
Current Status:
1. workflow.TaskObject() works in both pyconsole and pyfluent.
2. workflow.TaskObject.get_object_names() works in both pyconsole and pyfluent.

TODO:
1. for task in workflow.TaskObject:
       print(task.display_name())
The above works in pyconsole but fails in pyfluent. Below is the error:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\workflow.py", line 288, in __getattr__
    result = getattr(self._task, attr)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1757, in __getattr__
    return self._get_child(name)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1746, in _get_child
    raise LookupError(
LookupError: display_name is not found at path /TaskObject:Import Geometry

2. We should also try to emulate the settings dict-style version as shown above for both pyfluent and pyconsole.

**Comment by prmukherj** [comment]
All suggested changes have been applied in pyfluent end: https://github.com/ansys/pyfluent/pull/2336

On pyconsole side we have to implement the dictionary style accessing.

**Comment by prmukherj** [comment]
@seanpearsonuk, shall we close this pyfluent issue as of now?
