### ISSUE TITLE
Clarification of environment variables versus arguments and settings

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1439]
In the doc for `launch_fluent`, we make the path precedence for the fluent executable clear. The documentation states that the environment is primary and even overrides any `product_version` argument passed to `launch_fluent`. For the `ip`, we state: "You can also use the environment variable PYFLUENT_FLUENT_IP=<ip> to set this parameter", but is unclear which takes precedence. For `port`, we state: "You can use the environment variable PYFLUENT_FLUENT_PORT=<port> to set a default value", which means that the argument takes precedence, which is opposite to the `product_version` logic. Unless there are good reasons, we should be consistent, and we should also be clear in any case.

**Comment by seanpearsonuk** [comment]
```
elif os.getenv("PYFLUENT_FLUENT_IP") and os.getenv("PYFLUENT_FLUENT_PORT"):
        ip = port = None
```
this is the current code, so will wait on a fix for this.

**Comment by hpohekar** [comment]
@seanpearsonuk 

If we see the code block, then precedence is as follows -
1. argument (`ip` and `port`)
2. `server_info_filepath`
3. environment variable (`os.getenv("PYFLUENT_FLUENT_IP") and os.getenv("PYFLUENT_FLUENT_PORT")`)

![image](https://github.com/ansys/pyfluent/assets/106588300/c642cd8e-1e57-4d7a-8941-df55f58b1f6b)
