### ISSUE TITLE
launch_fluent scheduler info is woolly

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1448]
- processor_count: "... In job scheduler environments the total number of allocated cores is clamped to this value" what value?
- general Notes: "In job scheduler environments such as SLURM, LSF, PBS, etc… the allocated machines and core counts are queried from the scheduler environment and passed to Fluent."

**Comment by dnwillia-work** [comment]
In the first one 'this' refers to `processor_count`.   i.e. the total is clamped to the value passed to the launch command.
