### ISSUE TITLE
 ansys.fluent.core.session_meshing.Meshing.tui.display.views is missing

### ISSUE THREAD

**Issue by ddamadori** [ansys/pyfluent#1476]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

the class  ansys.fluent.core.session_meshing.Meshing.tui.display does not have all the commands that should be under views, meaning that  ansys.fluent.core.session_meshing.Meshing.tui.display.views is missing. 
![image](https://user-images.githubusercontent.com/109603410/225379570-974e02e9-8f30-41b5-9121-2d2e8b9b481f.png)

The equivalent in the TUI is the following:
![image](https://user-images.githubusercontent.com/109603410/225379639-6e4ab097-86af-41e3-be61-8d2d9998042e.png)

It is also completely missing from the Settings API for the moment.

### 📝 Steps to reproduce

create a meshing session and try to access session.display.view

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

231

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
aiohttp==3.8.3
aiosignal==1.3.1
alabaster==0.7.12
ansys-api-fluent==0.3.5
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.12.3
-e git+https://github.com/pyansys/pyprime@b7c92c224f53aa0b3f5ebb400a69622389737f0d#egg=ansys_meshing_prime
ansys-platform-instancemanagement==1.0.2
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.2
astroid==2.11.7
async-timeout==4.0.2
asynctest==0.13.0
atomicwrites==1.4.1
attrs==21.4.0
autopep8==1.6.0
Babel==2.10.3
backcall==0.2.0
bcrypt==3.2.2
beautifulsoup4==4.11.1
binaryornot==0.4.4
black==22.6.0
bleach==5.0.1
certifi==2022.6.15
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.1.0
click==8.1.3
cloudpickle==2.1.0
colorama==0.4.5
cookiecutter==2.1.1
cryptography==37.0.4
cycler==0.11.0
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
diff-match-patch==20200713
dill==0.3.5.1
docutils==0.17.1
entrypoints==0.4
fastjsonschema==2.16.1
flake8==4.0.1
fonttools==4.34.4
frozenlist==1.3.3
googleapis-common-protos==1.56.4
grpcio==1.47.0
h5py==3.7.0
idna==3.3
imageio==2.21.0
imagesize==1.4.1
importlib-metadata==4.2.0
importlib-resources==5.8.0
inflection==0.5.1
intervaltree==3.1.0
ipykernel==6.15.1
ipython==7.34.0
ipython-genutils==0.2.0
isort==5.10.1
jedi==0.18.1
jellyfish==0.9.0
Jinja2==3.1.2
jinja2-time==0.2.0
json5==0.9.8
jsonschema==4.7.2
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.4
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
keyring==23.7.0
kiwisolver==1.4.4
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
multidict==6.0.2
mypy-extensions==0.4.3
nbclassic==0.4.3
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook==6.4.12
notebook-shim==0.1.0
numpy==1.21.6
numpydoc==1.4.0
packaging==21.3
pandas==1.3.5
pandocfilters==1.5.0
paramiko==2.11.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.5.2
pluggy==1.0.0
pooch==1.6.0
prometheus-client==0.14.1
prompt-toolkit==3.0.30
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.1
ptyprocess==0.7.0
pycodestyle==2.8.0
pycparser==2.21
pydocstyle==6.1.1
pyflakes==2.4.0
Pygments==2.12.0
pylint==2.14.5
pyls-spyder==0.4.0
PyNaCl==1.5.0
pyparsing==3.0.9
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
pyrsistent==0.18.1
python-dateutil==2.8.2
python-lsp-black==1.2.1
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.5.0
python-slugify==6.1.2
pytoolconfig==1.2.1
pytz==2022.1
pyvista==0.37.0
pywin32==304
pywin32-ctypes==0.2.0
pywinpty==2.0.6
PyYAML==6.0
pyzmq==23.2.0
QDarkStyle==3.0.3
qstylizer==0.2.1
QtAwesome==1.1.1
qtconsole==5.3.1
QtPy==2.1.0
requests==2.28.1
rope==1.2.0
Rtree==1.0.0
scooby==0.7.0
seaborn==0.12.2
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
Sphinx==4.3.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spyder==5.3.2
spyder-kernels==2.3.2
terminado==0.15.0
text-unidecode==1.3
textdistance==4.3.0
three-merge==0.1.1
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.1
tornado==6.2
traitlets==5.3.0
typed-ast==1.5.4
typing_extensions==4.3.0
ujson==5.4.0
urllib3==1.26.10
vtk==9.2.2
watchdog==2.1.9
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.3
whatthepatch==1.0.2
wrapt==1.14.1
wslink==1.9.1
yapf==0.32.0
yarl==1.8.1
zipp==3.8.1
```

**Comment by dnwillia-work** [comment]
Not sure why it does not show up in the TUI interface, will need to take a look.  For sure none of the meshing TUI is under consideration for the settings API yet.  Not sure if we will migrate it there or not.

**Comment by ddamadori** [comment]
Hi Dan,

Thanks for the feedback.

May I ask why this migration is not considered?

In my humble opinion there is no doubt that Settings API is clearly the way to go for on the long term, and that is also the message we deliver to the customers, at least for the solver part.

Thank you,

Dario


Dario Amadori  /  Application Engineer II

[cid:94d2ad30-7e97-47a5-b975-7b5a93363e11]

Via G.B. Pergolesi 25  /  Milano, 20124

 +39 3458621915  /  +39 0289013378

***@***.******@***.***>  /   www.ansys.com<https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ansys.com%2F&data=05%7C01%7Cdario.amadori%40ansys.com%7Cd8f0d5c259f44819318608da537d6fb2%7C34c6ce6715b84eff80e952da8be89706%7C0%7C0%7C637914095459099579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oHd80tsJXohByrKFGZmvNUaM1cOnJ7IuH%2FC2E4jung8%3D&reserved=0>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

________________________________

**Comment by dnwillia-work** [comment]
Yes, you are totally right and it is under consideration.  Note in my post it says 'yet'.  Migrating the meshing TUI -> Settings API requires an investment into Fluent meshing that's not gotten on the priorities yet for the Fluent meshing team relative to all the other things they are asked to do.  It's not that it wont happen, it's just about when.

**Comment by mkundu1** [comment]
A workaround is to pass the TUI commands as arguments of the parent command: `meshing.tui.display.views("list-views")`

**Comment by seanpearsonuk** [comment]
@mkundu1 I have explicitly placed this on the backlog

**Comment by mkundu1** [comment]
The child menus can be accessed only interactively in Fluent TUI, will document the limitation and workaroud.
