### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by Atulsingh92** [ansys/pyfluent#1482]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

`f = examples.download_file("mixing_elbow.pmdb", "pyfluent/mixing_elbow")

Traceback (most recent call last):
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/aus1n19/.conda/envs/pyfluentenv/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable`

Mind well the above occured, just after the imports, given in the example page for mixing_elbow.py. And I am not sure, why it would not pick up the examples directory?

Anything I could do to correct this?

### 📝 Steps to reproduce

`import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples

#import_filename = "elbow.pmdb' # This gave a an error "Import Geometry is not found at path /TaskObject" at 
                                                  # meshing.workflow.TaskObject["Import Geometry"].Arguments = {
import_filename = examples.download_file("mixing_elbow.pmdb", "pyfluent/mixing_elbow")` # This gave the Network error described above. 

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

23.1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.5
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.12.5
ansys-fluent-parametric==0.6.1
ansys-fluent-visualization==0.6.0
ansys-platform-instancemanagement==1.0.3
appdirs==1.4.4
certifi @ file:///croot/certifi_1671487769961/work/certifi
charset-normalizer==3.1.0
contourpy==1.0.7
cycler==0.11.0
fonttools==4.39.2
googleapis-common-protos==1.58.0
grpcio==1.51.3
h5py==3.8.0
idna==3.4
imageio==2.26.0
importlib-metadata==6.0.0
kiwisolver==1.4.4
matplotlib==3.7.1
numpy==1.24.2
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
platformdirs==3.1.1
pooch==1.7.0
protobuf==3.20.3
protoc-gen-swagger==0.1.0
pyparsing==3.0.9
PySide6==6.2.4
python-dateutil==2.8.2
pytz==2022.7.1
pyvista==0.38.4
pyvistaqt==0.9.1
QtPy==2.3.0
requests==2.28.2
scooby==0.7.1
shiboken6==6.2.4
six==1.16.0
urllib3==1.26.15
vtk==9.2.6
zipp==3.15.0
```

**Comment by mkundu1** [comment]
```
import urllib.request
response = urllib.request.urlopen("https://raw.githubusercontent.com/pyansys/example-data/master/pyfluent/mixing_elbow/mixing_elbow.pmdb")
print(response.status)
```
Could you please provide the output of the above code outside pyfluent?

**Comment by mkundu1** [comment]
It seems your cluster node doesn't have access to github network to download the geometry file. Perhaps, you can download it outside the cluster and submit it with your job. 
```
import_filename = examples.download_file("mixing_elbow.pmdb", "pyfluent/mixing_elbow")
```
`import_filename` is the downloaded location of the .pmdb file which you need to copy to your cluster.

**Comment by dnwillia-work** [comment]
I think you just pass the cad file name to the location where it's stored on your cluster right.

**Comment by Atulsingh92** [comment]
So that is infact my question @dnwillia-work , if I have a pmdb file, how do I assign to a variable name?

Also, in my slurm script, I also have a `cd $SLURM_SUBMIT_DIR` which basically goes to the place where .py, .pmdb and .slurm file exists. So I'd argue this command is indeed correct. But correct me if I am wrong, that "/myfolder/elbow.pmdb" should be best practice instead? or perhaps something else?

**Comment by dnwillia-work** [comment]
Sorry about that, I thought it was clear what was wrong.  Regarding my previous post you would want to change it by a single character right:

` import_filename = "elbow.pmdb"`

i.e. use double quotes on both ends or single quotes but don't combine them.  For your second issue you will have to get the files downloaded ahead of time and deploy them to a location where the compute nodes can see them.  eg: somewhere on the file system.

**Comment by seanpearsonuk** [comment]
Sufficient information provided. Hopefully, this is working for you now.
