### ISSUE TITLE
Execute cleanup script from pyfluent

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1515]
.. to cleanup any hung Fluent processes

**Comment by mkundu1** [comment]
@Adam-Boutin When a session object goes out-of-scope we need to make sure all corresponding Fluent child processes are exited. If for some reason some Fluent processes are hung, we can execute Fluent's cleanup script to kill the hung processes. When Fluent is launched, it writes a cleanup script in its working directory which has the commands to kill all child processes.

Under the scope of this issue, we plan to add just the ability to execute the cleanup script. We would avoid executing the cleanup script automatically as of now as some pids in the script could have been already re-used in some other session.

**Comment by Adam-Boutin** [comment]
Ok just to confirm that I am understanding this correctly. We will be creating a manual process to run the cleanup scripts made by fluent?(e.g. cleanup-fluent-DESKTOP-*******-1352.bat) 

Is there anything currently in place that would be similar?

**Comment by mkundu1** [comment]
I'm thinking something like `fn = session.get_process_cleaner()`, then even after `session` goes out-of-scope, we can execute `fn()` to kill the Fluent process manually later.

**Comment by mkundu1** [comment]
@raph-luc Sometimes child Fluent processes don't exit properly which is outside of pyfluent's control. Running the cleanup script, which is a mechanism provided by Fluent, will be useful in such situations. At this point, I'm only looking for the ability to run cleanup script to be available in pyfluent without integrating it into the session's lifecycle.

Yes, ideally, we would need process monitoring of Fluent processes implemented in Fluent.

**Comment by seanpearsonuk** [comment]
@raph-luc it's great that you brought up these points, thanks. @mkundu1 it's a good point that the examples could demonstrate the good practice.

**Comment by lagacep-ans** [comment]
@seanpearsonuk @mkundu1 @raph-luc I'm taking a look at some aspects of the fluent error handling right now, including if the MPT_Monitor system is used at its full capability.    
We'll need to :
 - Improve (or add) some error state flags in fluent itself
 - gRPC protocol should serve that state (event? passive query? return value on any api call?)
 - pyFluent needs to choose how to handle remote crashes/hard failures,  throw an exception or passive queries?
    ... right now in (at least one) case of a segfault on server side, pyfluent is unaware of what happened, api calls fail silently.
    
    we'll need to open a separate discussion stream on this.

**Comment by seanpearsonuk** [comment]
@lagacep-ans @mkundu1  @raph-luc 
_gRPC protocol should serve that state (event? passive query? return value on any api call?)_
- return value is ineffective since we can have multiple clients for a given server
- passive query for error states in general assumes that the server is healthy enough to serve responses. This approach is otherwise unappealing anyway and inconsistent with the general approach
- I presume that we should use the existing event streaming mechanism to provide the error information

_pyFluent needs to choose how to handle remote crashes/hard failures_
- pyfluent must throw an exception for fatal server errors: execution should not just continue

**Comment by dnwillia-work** [comment]
Regarding throwing exceptions in the Python client if Fluent is not usable I've got to agree with that.  @lagacep-ans and I had chatted about this at some point.   Though, I think a lot of the 'error handling' is a separate issue from calling the clean up script, I agree with @mkundu1 that it needs to be something that is optional.

**Comment by Adam-Boutin** [comment]
@mkundu1 Where should I build a function that does this?
Would it just search the working directory for a file prefixed by "cleanup-fluent" then run it?
Should I make a branch for this with the "feat/*" branch name?

**Comment by mkundu1** [comment]
@Adam-Boutin We can start according to [this plan](https://github.com/ansys/pyfluent/issues/1515#issuecomment-1543191847) and see how it goes. With the scheme functions I mentioned earlier, it will be possible to identify the complete cleanup script path.

Yes, please create a "feat/*" branch.

**Comment by Adam-Boutin** [comment]
@mkundu1 I just have 2 more questions:
Where should I put fn()?
Will this be a direct terminal command or run through python scripting?

**Comment by mkundu1** [comment]
@Adam-Boutin `fn` would be part of user-script
```
fn = None
with pyfluent.launch_fluent() as session:
    fn = session.get_cleanup_script_runner()
    # Use session
# session goes out-of-scope here
# Later if needed
fn()  # calls the cleanup script
```

**Comment by raph-luc** [comment]
Started working on this, as it is going to be shared by the "watchdog" functionality we are currently prototyping

@Adam-Boutin feel free to check the WIP pull request https://github.com/ansys/pyfluent/pull/1674 and make contributions / improvements / suggestions
