### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by MingjieZhangNJU** [ansys/pyfluent#1556]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Dear all,
 I wonder how we write correct pyfluent lines, which aren't shown in example files.
I refer to the tui command to write the lines to run the simulation and to interpret the udf.
It works.
However, I will also encounter some issues ...
If so, how should I proceed...

### 📝 Steps to reproduce

Here I have an example of an error when execute_on_demand:
tui.define.user_defined.interpreted_functions("udf.c")  # the interpretation works fine
tui.define.user_defined.execute_on_demand("udf.c","demand01") # this will cause error
tui.define.user_defined.execute_on_demand("demand01") # this will cause error

I would like to ask for your help on revising the above lines.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ANSYS2023 

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
,,,
```

**Comment by MingjieZhangNJU** [comment]
study to use pyfluent

**Comment by mkundu1** [comment]
You may need extra quotes around the argument as Fluent expects a string:
```
tui.define.user_defined.execute_on_demand('"demand01"')
```
