### ISSUE TITLE
Supported versions documentation

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1590]
https://fluent.docs.pyansys.com/dev/getting_started/installation.html
"The ansys-fluent-core package supports Python **3.7** through Python **3.10** on Windows and Linux."

https://visualization.fluent.docs.pyansys.com/release/0.7/getting_started/index.html
"The ansys-fluent-visualization package supports Python **3.7** through Python **3.10** on Windows and Linux."
 
and similar in 
https://parametric.fluent.docs.pyansys.com/release/0.7/getting_started/index.html

We should state that 3.8 through 3.11.

**Comment by hpohekar** [comment]
@seanpearsonuk 

Visualization changes are implemented in this PR - https://github.com/ansys/pyfluent-visualization/pull/263, 

but no idea why it is not appearing in docs.

**Comment by seanpearsonuk** [comment]
ok, looks like there's a fix for the build in place. You many close this issue if the other parts are done
