### ISSUE TITLE
Undocument PYFLUENT_FLUENT_ROOT

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1601]
Users are misusing this; e.g., it does not resolve CAD reader locations without AWP variables being set (#1572). It would be simpler to leave it out - it was not intended for general usage.

@dnwillia @mkundu1 do you agree to remove or only add some caveat?
@acarvalh-work - the work is pending final decision how to proceed.

https://fluent.docs.pyansys.com/release/0.13/api/general/launcher/index.html

**Comment by dnwillia-work** [comment]
Yes, agree that we should remove the documentation.  It's meant for pointing to a local Fluent build area which the library users will almost never have.

**Comment by mkundu1** [comment]
@acarvalh-work @seanpearsonuk We also need to make this change in release/0.13 to update the stable documentation. Patch version won't be required, running the [release-doc-build](https://github.com/ansys/pyfluent/blob/main/.github/workflows/release-doc-build.yml) after merge should deploy the latest stable doc.
