### ISSUE TITLE
Intellisense with VS Code not working with latest release

### ISSUE THREAD

**Issue by sravanansys** [ansys/pyfluent#1609]
Intellisense for parameter level is not showing up in VS Code. For example, the parameters for energy doesn't appear

`session.setup.models.energy`

Also, the arguments for `session.file.read_case` do not appear similar to `launch_fluent`

![image](https://github.com/ansys/pyfluent/assets/99287292/6bc55de3-6179-4d5c-b2fd-f9fb5e61cb87)

**Comment by dnwillia-work** [comment]
FWIW I think it's been busted for a while (again).  We broke it before...

**Comment by mkundu1** [comment]
I have a fix for the parameter listing. `session.file.read_case` is a class while statically typing in vscode. One way to force a type-hint with functional arguments would be to annotate `session.file.read_case` like a function in a typing stub file.
