### ISSUE TITLE
Expose allowed_values() method for a string only if has_allowed_values is true in static info

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1613]
Fluent provides a flag `has_allowed_values` via static-info to indicate whether allowed values are defined for a string. PyFluent should consume that information and expose the `allowed_values()` method for a string only if that flag is true.

**Comment by hpohekar** [comment]
@seanpearsonuk @mkundu1 

All `string` type settings have `has_allowed_values: True`. 

I have executed following steps - 

```
import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples
import_filename = examples.download_file("elbow.cas.h5", "pyfluent/examples/DOE-ML-Mixing-Elbow")

solver = pyfluent.launch_fluent()
solver.tui.file.read_case(import_filename)
solver_static_info = solver._settings_root._static_info

meshing = pyfluent.launch_fluent(mode="meshing")
meshing.tui.file.read_case(import_filename)
meshing_static_info = meshing.settings_service.get_static_info()
```

Then if we search for `'type': 'string', 'has_allowed_values': False` in `solver_static_info` or `meshing_static_info` then we don't get single matching entry.

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk @mkundu1
> 
> All `string` type settings have `has_allowed_values: True`.
> 
> I have executed following steps -
> 
> ```
> import ansys.fluent.core as pyfluent
> from ansys.fluent.core import examples
> import_filename = examples.download_file("elbow.cas.h5", "pyfluent/examples/DOE-ML-Mixing-Elbow")
> 
> solver = pyfluent.launch_fluent()
> solver.tui.file.read_case(import_filename)
> solver_static_info = solver._settings_root._static_info OR
> solver_static_info = solver.settings_service.get_static_info()
> 
> meshing = pyfluent.launch_fluent(mode="meshing")
> meshing.tui.file.read_case(import_filename)
> meshing_static_info = meshing.settings_service.get_static_info()
> ```
> 
> Then if we search for `'type': 'string', 'has_allowed_values': False` in `solver_static_info` or `meshing_static_info` then we don't get single matching entry.

@hpohekar 

Some questions:

- Is the same true for string list parameters?

- Given that all string parameters have has_allowed_values=True, are any of those incorrect?

**Comment by h-krishnan** [comment]
@seanpearsonuk @mkundu1 @hpohekar I think has_allowed_values = True is sent only for those for which this value is True. The default is assumed to be false. This is to reduce the data transfer.

**Comment by hpohekar** [comment]
@seanpearsonuk 

Is the same true for string list parameters? - Yes

**Comment by seanpearsonuk** [comment]
@hpohekar just in case you missed it, please see the above clarification from @h-krishnan
