### ISSUE TITLE
Improvement in the docker run workflow

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1616]
1. Add a docker-compose file, instead of `docker run` call
2. Move all related env. vars in a .env file and document them.
3. Improve the exposure of docker container run in launch_fluent.

**Comment by seanpearsonuk** [comment]
Re point 2, should this all be just env var configurable? Should we not allow it to be configured also via `launch_fluent` arguments?

Are we proposing to use the `docker` Python package?

N.b. during hackathon, I created the branch feat/hackathon as a basic way to get around hardcoded container repository (which we could not use) and mount path. Shall we address these in the same issue?

@mkundu1 @raph-luc
