### ISSUE TITLE
Update pyfluent related info in observability.pyansys.com

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1618]
check what information is missing for pyfluent repos/projects and populate github/setup,py/pyproject.toml etc.

update the packaging instruction (either in setup.py or in pyproject.toml)

**Comment by hpohekar** [comment]
Need to discuss with @seanpearsonuk and @mkundu1

**Comment by hpohekar** [comment]
@seanpearsonuk @mkundu1 

Following information is missing for PyFluent repos/projects 

Repo/project name -> Missing information 

0. ansys/protos-pyfluent -> Website
1. ansys/pyfluent-conversion-demo -> Website
2. ansys/pyfluent-dash-components -> Website
3. ansys/pyfluent-dev -> License, Website
4. ansys/pyfluent-dev-docs -> License, Admin 
5. ansys/pyfluent-dev-docs-redirect -> License, Admin, Website
6. ansys/pyfluent-docs -> License, Admin
7. ansys/pyfluent-docs-redirect -> License, Admin, Website 
8. ansys/pyfluent-examples-dev-docs -> Description, License, Website
9. ansys/pyfluent-examples-docs -> Description, License, Website
10. ansys/pyfluent-examples-internal-2 -> Description, Website
11. ansys/pyfluent-parametric-dev-docs -> License, Website
12. ansys/pyfluent-parametric-docs -> License, Website
13. ansys/pyfluent-ui-dev-docs ->Description, License, Website
14. ansys/pyfluent-ui-docs ->License, Website
15. ansys/pyfluent-visualization-dev-docs -> License, Website
16. ansys/pyfluent-visualization-docs -> License, Website

**Comment by hpohekar** [comment]
@seanpearsonuk @mkundu1 

Following information is missing for **PyPi** PyFluent projects -

1. Source URL, 
2. Bugtrack URL, 
3. Docs URL

![image](https://github.com/ansys/pyfluent/assets/106588300/a3e404f1-1995-4c66-a2bc-5705b844c006)

**Comment by hpohekar** [comment]
@seanpearsonuk @mkundu1 

Following repos doesn't have docs URL to specify it as a Website.

https://github.com/ansys/protos-pyfluent
https://github.com/ansys/pyfluent-dash-components

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk @mkundu1
> 
> Each of the following repo doesn't have docs URL to specify it as a Website.
> 
> https://github.com/ansys/protos-pyfluent https://github.com/ansys/pyfluent-conversion-demo https://github.com/ansys/pyfluent-dash-components https://github.com/ansys/pyfluent-dev https://github.com/ansys/pyfluent-examples-internal-2

That's right, these are all private.
