### ISSUE TITLE
base class information gone from **Settings** API documentation

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1630]
E.g.,
https://fluent.docs.pyansys.com/version/stable/api/solver/_autosummary/settings/file.html#file

This affects settings API only. I checked data model and TUI APIs which look OK. 

There was a different implementation used for settings API in the latest round of changes in terms of what is automatically created?

**Comment by seanpearsonuk** [comment]
@hpohekar I don't want to distract you with this right now, but this is something we should correct fairly soon. **The current open-telemetry work takes precedence.**

**Comment by hpohekar** [comment]
@seanpearsonuk It's resolved now. Thanks. https://github.com/ansys/pyfluent/pull/1632
