### ISSUE TITLE
Fluent data file reader

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1637]
Develop a data file (.dat.h5) reader. This can use h5py just as does the CaseFile class.  Perhaps for svar, we can present the same interface as the live svar object on a PyFluent solver session.

Related: #1385.

@raph-luc: I will tentatively assign this to you. If you want to take it up soon, we can discuss it more.

CC: @ajain-work

**Comment by raph-luc** [comment]
Completed by https://github.com/ansys/pyfluent/pull/1909
