### ISSUE TITLE
Correct the doc for setting up debug logging

### ISSUE THREAD

**Issue by dnwillia-work** [ansys/pyfluent#1655]
### Description of the modifications

This is not right.

https://fluent.docs.pyansys.com/version/stable/user_guide/index.html#global-logging

I think the right thing is
```
import logger
logger.getLogger().setLevel(logger.DEBUG)
```

**Comment by raph-luc** [comment]
Already reported here: https://github.com/ansys/pyfluent/issues/1625

In the current pyfluent version, logging is already set to "DEBUG" by default, and the root logger is effectively unused. 

Logging rework being addressed by https://github.com/ansys/pyfluent/pull/1651
