### ISSUE TITLE
TWF Setup

### ISSUE THREAD

**Issue by acarvalh-work** [ansys/pyfluent#1670]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

There are 2 methods of performing a turbo workflow. The first is through `workflow` object of a solver session, and the other is through the `solverworkflow` object of a solver session. 

When performing the turbo workflow tasks using `workflow` there are no issues as seen in [turbo_machinery(working).py](https://github.com/ansys/pyfluent/blob/feat/additional_example/examples/00-fluent/turbo_machinery(working).py), however, when performing the same tasks using the `solverworkflow` method there seems to be ambiguity in what should be entered into the tasks as when a task fails it throws an unknown exception.

[turbo_machinery(broken).py](https://github.com/ansys/pyfluent/blob/13056b4cb3e8abe7628f0b4ec6a1d99d7e4e7d8e/examples/00-fluent/turbo_machinery(broken).py) follows a TWF using the `solverworkflow` method and is failling in 2 locations: 

1.

https://github.com/ansys/pyfluent/blob/13056b4cb3e8abe7628f0b4ec6a1d99d7e4e7d8e/examples/00-fluent/turbo_machinery(broken).py#L67-L73

Error:

![image](https://github.com/ansys/pyfluent/assets/132941110/361cdc28-fefa-45f2-a4eb-b9cdd9c722d9)

The previous code throws an error within `TWF_BasicMachineDescription`, but this tasks works correctly when initializing TWF with `solver_session.workflow.InitializeWorkflow(WorkflowType="Turbo Workflow")`. The issue only occurs when initializing TWF with `solver_session.solverworkflow.GlobalSettings.EnableTurboMeshing(True)`.

2.

https://github.com/ansys/pyfluent/blob/13056b4cb3e8abe7628f0b4ec6a1d99d7e4e7d8e/examples/00-fluent/turbo_machinery(broken).py#L148-L166

![image](https://github.com/ansys/pyfluent/assets/132941110/44cdad80-6bce-4f63-be4d-dab7164c1853)

The previous code throws an error within the first import mesh statement, only when using `solver_session.solverworkflow.TWF_ImportMesh()`.

### 📝 Steps to reproduce

1. Switch to the [feat/additional_example](https://github.com/ansys/pyfluent/tree/feat/additional_example) remote branch
2. Run [turbo_machinery(broken).py](https://github.com/ansys/pyfluent/blob/13056b4cb3e8abe7628f0b4ec6a1d99d7e4e7d8e/examples/00-fluent/turbo_machinery(broken).py)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-platform-instancemanagement==1.1.1
ansys-sphinx-theme==0.9.6
appdirs==1.4.4
asttokens==2.2.1
attrs==23.1.0
autodocsumm==0.2.10
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2023.5.7
cfgv==3.3.1
charset-normalizer==3.1.0
colorama==0.4.6
comm==0.1.3
contourpy==1.0.7
coverage==7.2.7
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
docutils==0.19
exceptiongroup==1.1.1
executing==1.2.0
fastjsonschema==2.16.3
filelock==3.12.0
fonttools==4.39.4
googleapis-common-protos==1.59.0
grpcio==1.54.0
h5py==3.8.0
identify==2.5.24
idna==3.4
imagesize==1.4.1
importlib-metadata==6.6.0
iniconfig==2.0.0
ipykernel==6.23.0
ipython==8.13.2
ipywidgets==8.0.6
jedi==0.18.2
Jinja2==3.1.2
jsonschema==4.17.3
jupyter-sphinx==0.4.0
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
livereload==2.6.3
lxml==4.9.2
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==2.0.5
nbclient==0.7.4
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
nodeenv==1.7.0
numpy==1.24.3
numpydoc==1.5.0
packaging==23.1
pandas==2.0.1
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.0
pluggy==1.0.0
pre-commit==3.3.1
prompt-toolkit==3.0.38
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.5
pure-eval==0.2.2
pydata-sphinx-theme==0.13.3
Pygments==2.15.1
pypandoc==1.10
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.3.1
pytest-cov==4.1.0
pytest-mock==3.10.0
pytest-sphinx==0.5.0
python-dateutil==2.8.2
pytz==2023.3
pywin32==306
PyYAML==6.0
pyzmq==25.0.2
requests==2.30.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.4.1
Sphinx==5.3.0
sphinx-autobuild==2021.3.14
sphinx-copybutton==0.5.1
sphinx-gallery==0.11.1
sphinx-notfound-page==0.8.3
sphinx_autodoc_typehints==1.22
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-websupport==1.2.4
sphinxemoji==0.2.0
stack-data==0.6.2
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.1
traitlets==5.9.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==2.0.2
virtualenv==20.23.0
wcwidth==0.2.6
webencodings==0.5.1
widgetsnbextension==4.0.7
zipp==3.15.0
```

**Comment by mkundu1** [comment]
@acarvalh-work I think using the `workflow` datamodel is the right way of doing it. The `solverworkflow` datamodel is updated through `workflow` datamodel. It is similar to `meshing` and `workflow` datamodel for meshing workflow. @seanpearsonuk let us know if something else is not correct.

**Comment by seanpearsonuk** [comment]
I will double-check that this is no longer exposed before closing

**Comment by seanpearsonuk** [comment]
no longer exposed
