### ISSUE TITLE
Fix doc warnings

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1690]
The attached build_errors.txt shows all doc warnings from PyFluent source excluding the generated API code. To reproduce:
```
git clean -fdx doc                (Skip generated API doc)
set PYFLUENT_SKIP_EXAMPLES_DOC=1  (Skip examples doc)
make -C doc HTML                  (Generate with warnings in build_erros.txt)
```  

[build_errors.txt](https://github.com/ansys/pyfluent/files/11763824/build_errors.txt)

Edit: Removed `-W --keep-going` as that part is not required to generate build_errors.txt.

**Comment by raph-luc** [comment]
Would just add that `git clean -fdx` may delete things that you do not want to delete.

Yesterday I started using a script like this to clean only the generated API code on Windows, running from the pyfluent root directory, inside a `.bat` file:
 ```
 del src\ansys\fluent\core\fluent_version_*
rmdir /s /q src\ansys\fluent\core\datamodel_231
rmdir /s /q src\ansys\fluent\core\datamodel_232
rmdir /s /q src\ansys\fluent\core\datamodel_241
del src\ansys\fluent\core\meshing\tui_*
rmdir /s /q src\ansys\fluent\core\solver\settings_231
rmdir /s /q src\ansys\fluent\core\solver\settings_232
rmdir /s /q src\ansys\fluent\core\solver\settings_241
del src\ansys\fluent\core\solver\tui_*
rmdir /s /q doc\source\api\meshing\datamodel
rmdir /s /q doc\source\api\meshing\tui
rmdir /s /q doc\source\api\solver\datamodel
rmdir /s /q doc\source\api\solver\tui
rmdir /s /q doc\source\api\solver\_autosummary
```
