### ISSUE TITLE
crash fluent by requesting invalid reduction

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1699]
Maybe need to pre-check the expression validity.

This is by word of mouth so I don't have specifics.

**Comment by seanpearsonuk** [comment]
@prmukherj please don't start on this until we find out more

**Comment by dpons-ansys** [comment]
So on a session from the mixing elbow case, if I perform a force reduction on a user created plane, it will crash the session:

`from ansys.fluent.core.solver.function import reduction
import ansys.fluent.core.quantity as q

# Create a Plane and perform a reduction
loc = 2.5 # In Inches
plane_name = 'plane-1'
solver.results.surfaces.plane_surface.create(plane_name)
val = reduction.area_average(expr="TotalPressure",locations=[plane_name], ctxt=solver)
force = reduction.force(locations=[plane_name], ctxt=solver)
`

**Comment by seanpearsonuk** [comment]
@prmukherj please see above the instructions from @dpons-ansys

**Comment by RebelYoung** [comment]
There is no `named_expression' attribute in `solver.setup`, why???
![image](https://github.com/ansys/pyfluent/assets/59256512/3c056bd9-7c0f-48b2-886f-b06d2bf56cef)
```
dir(solver.setup)
['__annotations__',
 '__call__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_flproxy',
 '_get_parent_of_active_child_names',
 '_is_protocol',
 '_name',
 '_parent',
 '_print_state_helper',
 '_setattr',
 '_state_type',
 'boundary_conditions',
 'cell_zone_conditions',
 'child_names',
 'command_names',
 'flproxy',
 'fluent_name',
 'general',
 'get_active_child_names',
 'get_active_command_names',
 'get_active_query_names',
 'get_attr',
 'get_attrs',
 'get_completer_info',
 'get_state',
 'is_active',
 'is_read_only',
 'materials',
 'models',
 'obj_name',
 'parent',
 'path',
 'print_state',
 'query_names',
 'reference_values',
 'set_flproxy',
 'set_state',
 'to_python_keys',
 'to_scheme_keys']
```

**Comment by prmukherj** [comment]
![image](https://github.com/ansys/pyfluent/assets/109645853/ca08d3bc-9cf8-48a8-81da-fd99c8b1e598)
Not able to reproduce the above issue. Could you please provide some more information about the version of fluent and pyfluent that you are using. Thank you.

**Comment by RebelYoung** [comment]
> ![image](https://github.com/ansys/pyfluent/assets/109645853/ca08d3bc-9cf8-48a8-81da-fd99c8b1e598)
> Not able to reproduce the above issue. Could you please provide some more information about the version of fluent and pyfluent that you are using. Thank you.

Because of the complexity of the solver.field_data in newer version, I always choose 13.X.

**Comment by RebelYoung** [comment]
> > ![image](https://github.com/ansys/pyfluent/assets/109645853/ca08d3bc-9cf8-48a8-81da-fd99c8b1e598)
> > Not able to reproduce the above issue. Could you please provide some more information about the version of fluent and pyfluent that you are using. Thank you.
> 
> Because of the complexity of the solver.field_data in newer version, I always choose 13.X.

fluent 22r2 and pyfluent 13.x

**Comment by prmukherj** [comment]
Could you please explain the complexity with field_data. We will try to address any issues based on your feedback. Thank you.

**Comment by RebelYoung** [comment]
> Could you please explain the complexity with field_data. We will try to address any issues based on your feedback. Thank you.

I have explain in #1681 issue.

**Comment by RebelYoung** [comment]
> Could you please explain the complexity with field_data. We will try to address any issues based on your feedback. Thank you.

The type returned from field_data changed from a dict {id:np.array} into a complexed type Vector. it makes my code have no ability to read the data directly.

**Comment by RebelYoung** [comment]
@raph-luc thank you for your reply. But, my pyfluent is v0.13.0 and fluent version is 22r2. I choose them because mine programed a few months ago by pyfluent v0.11.0. The program using `field_data` inherit good from 0.11.0 to 0.13.0, but the return type changed into complex type from 0.14.0. I would not like to change my code. So, I continue use 0.13.0.
I exampled in #1681 and explained the complexity.

About the `dir(solver.setup)`, I don't konw why can not use any function in `reduction.py`, the python file download by `ansys-fluent-core` together. I don't think it is fault installation.

**Comment by RebelYoung** [comment]
> Could you please explain the complexity with field_data. We will try to address any issues based on your feedback. Thank you.

reduction.py, the python file, was download by `ansys-fluent-core` 0.13.0 together. I don't think it is fault installation.

**Comment by RebelYoung** [comment]
I got it. The `named_expressions` is not a child_name in `setup` in `settings_222.py` but exists in `settings_231.py`

It means any functions in `reduction.py` can not work out for `fluent 2022r2`.

![image](https://github.com/ansys/pyfluent/assets/59256512/1b493ea6-c34a-4bb2-9782-58d32d71cad2)




So, can you help me for a string or data flow from fluent console to python?
as follow example:
```
/report/fluxes> m
All boundary/interior zones [yes] no

Zone(1) [()] 5
Zone(2) [()] 7
Zone(3) [()] 
Write to file? [no] 

                  Mass Flow Rate               [kg/s]
-------------------------------- --------------------
                         exhaust            11.448219
                           inlet           -11.315761
                ---------------- --------------------
                             Net           0.13245784
```
```
def return_data(command):
    ...
    return data

data=return_data(solver.tui.report.surface_intergrals.sum(5,7,(),'px','no))
print(data)

{
 'exhaust'  :11.448219
'inlet':    -11.315761
 'Net':    0.13245784
}
```

**Comment by seanpearsonuk** [comment]
@RebelYoung multiple topics have been added to this issue. We need to keep issues on topic. Thank you.

**Comment by seanpearsonuk** [comment]
@prmukherj when you get around to this issue, it would be good to write a test based on @dpons-ansys 's script and see how general the issue is.

**Comment by seanpearsonuk** [comment]
@dpons-ansys 

@prmukherj cannot reproduce via your script with the current code, an there are some related PyFluent tests that are passing.

We shall close for now. Please let us know if you still experience this issue, and perhaps we can discuss/demo more at the meeting.
