### ISSUE TITLE
Multiple occurrences in API documentation

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1710]
E.g. `centroid_smooth_iterations` appears in following 5 pages:

https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/mesh/poly/controls/smooth_controls/index.html
https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/mesh/poly/controls/index.html
https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/mesh/poly/index.html
https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/mesh/index.html
https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/index.html

All of them are linked at https://fluent.docs.pyansys.com/version/stable/api/meshing/tui/mesh/poly/index.html#ansys.fluent.core.meshing.tui_231.main_menu.mesh.poly.controls.smooth_controls.centroid_smooth_iterations

**Comment by mkundu1** [comment]
Another issue:
Clicking `Appearance` in https://fluent.docs.pyansys.com/version/stable/api/meshing/datamodel/preferences/index.html (in meshing section) opens https://fluent.docs.pyansys.com/version/stable/api/solver/datamodel/preferences/index.html#ansys.fluent.core.datamodel_231.preferences.Root.Appearance (solver section).

**Comment by seanpearsonuk** [comment]
I perused the doc briefly and it seems that @mkundu1 's referenced PR has resolved the issues.
