### ISSUE TITLE
Issue when creating a Scene 

### ISSUE THREAD

**Issue by PyPablo** [ansys/pyfluent#1721]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I try to create a scene with the following code

`session.results.scene.create("scene_vof")
session.results.scene["scene_vof"].title = "scene_vof"
session.results.scene["scene_vof"] = {
    'temporary': False, 
    'graphics_objects': [{'colormap-left': 0.0, 
                          'transparency': 0, 
                          'colormap-width': 0.0, 
                          'colormap-height': 0.0, 
                          'colormap-position': -1, 
                          'colormap-bottom': 0.0, 
                          'name': 'mesh_iso_clip_liquid'}], 
    'display_state_name': 'None'}`

I get this error
![image](https://github.com/ansys/pyfluent/assets/99959795/964a856f-f32f-4efe-b6bc-e9b67a36273b)

### 📝 Steps to reproduce

Simply try to create a Scene object in the same way. Version used are

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Fluent: 2023R2
PyFluent: 0.16dev0

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by seanpearsonuk** [comment]
@PyPablo 

Is the `graphics_objects` `dict` that you are passing in valid input. That dictionary looks different to one I get from Fluent for a created scene. E.g, 
```
{'name': 'scene-1', 'title': 'scene-1', 'graphics_objects': {'contour-2': {'name': 'contour-2', 'transparency': 0, 'colormap_position': -1, 'colormap_left': 0.0, 'colormap_bottom': 0.0, 'colormap_width': 0.0, 'colormap_height': 0.0}}, 'display_state_name': 'None'}
```
Please reopen if you believe that your use case is valid.
