### ISSUE TITLE
Expression not recognized correctly

### ISSUE THREAD

**Issue by PyPablo** [ansys/pyfluent#1722]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In Fluent version 2023R2, I get an issue when creating and using an expression with newlines.

Assume I have the expression _viscosity_distribution_ that I want to use in the material properties as viscosity. The expression is as follows:

`session.setup.named_expressions["viscosity_distribution"].definition = '''
   IF(StaticTemperature< 283.15 [K], 468.0, 
       IF(StaticTemperature<293.15 [K], 468.0 + (200.0-468.0)/10.0*(StaticTemperature-283.15 [K])/1 [K], 0.0))*1 [Pa s]`

In 2023R1 and Pyfluent version 0.14 I could assign this expression to the material properties without issue. Now, if I use the same code in the latest version 0.16.dev0 and 2023R2 the expression gets created but it is not available for use in the viscous property panel.

A workaround to this is to write it as a single string with no newlines, i.e. the following code works in the latest version

`session.setup.named_expressions["viscosity_distribution"].definition = '''IF(StaticTemperature< 283.15 [K], 468.0,''' + \ 
       '''IF(StaticTemperature<293.15 [K], 468.0 + (200.0-468.0)/10.0*(StaticTemperature-283.15 [K])/1 [K], 0.0))*1 [Pa s]'''`

which is basically concatenating strings

### 📝 Steps to reproduce

Create an expression with the abovementioned characteristics

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R2

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
NA
```

**Comment by seanpearsonuk** [comment]
@PyPablo please could you check what is happening on the Fluent side when you create these expressions. Are the expressions created as expected? Do they show as valid? Can the issue be recreated without involving PyFluent?

**Comment by PyPablo** [comment]
@seanpearsonuk yes, the expressions get created normally and show no errors. In fact, if I run PyFluent session and I issue the command, if I simply open the expression panel and click on "Save", then I can use it in the properties panel normally.

**Comment by seanpearsonuk** [comment]
@PyPablo thanks for the additional information. If the expression shows up as valid in Fluent then PyFluent can wash its hands and we can only consider this as a Fluent issue. I will create a bug in Fluent. 

*TODO* Create a bug in Fluent

**Comment by prmukherj** [comment]
Not reproducible in the latest fluent release.
