### ISSUE TITLE
Settings API versions of PyFluent examples

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1723]
This is about all documented examples, whether they are in the PyFluent docs of any of the repos or the PyFluent examples docs. For the solver set-up, the vast majority of examples use the TUI API, which is more stable than the settings API, but it is not a programming interface so the examples are unreadable and cannot be generalised. 

Conceptually, what we need to do is to continue to use the TUI-based scripts as a basis, and to auto-generate the settings API analogues per Fluent version.

**Comment by seanpearsonuk** [comment]
Any volunteers?
@ajain-work @mkundu1 @prmukherj @hpohekar @raph-luc @acarvalh-work

**Comment by dnwillia-work** [comment]
@ansjsia is doing a migration
