### ISSUE TITLE
job scheduler script interaction

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1726]
For sessions run within job scheduler environments, we require full interactivity via Python to the Fluent server.

**Comment by dnwillia** [comment]
I don't quite understand what the UX for this look like. Do I just:
```
s = pyfluent.launch_fluent(...some args for scheduler)  # blocks the console until the job spins up in the scheduler?
```
If it's that then I'm not sure this issue makes sense.  Would be good to have some more details.

**Comment by seanpearsonuk** [comment]
@dnwillia-uk good point, yes, we have left the details here for the design and implementation. We will need asynchronous behaviour here. I think the launch should happen via a separate method, the behaviour being distinct. It should be possible to register a callback for when the connection to a remote server is fully established. We can implement in terms of the health check service both for manually checking of the connection and for the callback, which will be the preferred programmatical approach. 

@mkundu1
