### ISSUE TITLE
simple_upload_server

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#1746]
@seanpearsonuk @hpohekar  Is the line below working as intended?
https://github.com/ansys/pyfluent/blob/1842fee8a79c3db5db05dd235c869c0c8f22f96d/src/ansys/fluent/core/session.py#L297

As far as I can tell `simple_upload_server` does not exist, is it just for testing or maybe Ansys Lab?

**Comment by seanpearsonuk** [comment]
@hpohekar might know more https://github.com/ansys/pyfluent/blob/1842fee8a79c3db5db05dd235c869c0c8f22f96d/src/ansys/fluent/core/session.py#L297

**Comment by hpohekar** [comment]
@seanpearsonuk @raph-luc 

We have `simple_upload_server_client-0.0.1-py3-none-any.whl` file in Ansys Lab environment. We install it there then only line 297 works and it is only intended to use in Ansys Lab.
