### ISSUE TITLE
Remove settings API arguments method which only returns Scheme-level information

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1756]
```
>>> s.solution.run_calculation.iterate.arguments()
{'iter-count': {'set-value': None, 'fluent-value': None, 'on-child-changed': None, 'value': None, 'env': None, 'default': None, 'min': None, 'set-fluent-value': None, 'ti-active?': None, 'type': None, 'on-changed': None, 'display-text': None, 'help': None, 'fluent-default': None, 'set-value-impl': None, 'exec-on-child-changed-on-parents': None, 'ti-prompt': None, 'dependent-paths': None, 'units-quantity': None, 'active?': None}}
```
We should either convert this to something meaningful to Python users or exclude it from the Python interface. I'm not sure what the intention is with this method(?) 

@h-krishnan: I am no longer ever able to tag gyeole. I wonder if he didn't update his MFA settings.

**Comment by h-krishnan** [comment]
@seanpearsonuk @mkundu1 I don't see any point in having this method. Should we just remove it?

**Comment by seanpearsonuk** [comment]
@h-krishnan I agree, I will use this issue to request one of the team to remove it.
