### ISSUE TITLE
units_table si_data si_offset

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1770]
This is reassigned before the value is used.

**Comment by acarvalh-work** [comment]
Removed the `si_offset` reassignment:

https://github.com/ansys/pyfluent/blob/3396a7409a343f625594f6f32e33d4912a02bf8c/src/ansys/fluent/core/quantity/units_table.py#L211-L217

now `si_offset` is only assigned once:

https://github.com/ansys/pyfluent/blob/3396a7409a343f625594f6f32e33d4912a02bf8c/src/ansys/fluent/core/quantity/units_table.py#L176-L180

and only the initial `si_offset` value is returned by `si_data`.
