### ISSUE TITLE
session.file.read() hangs indefinitely inside Docker container rather than returning error 

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#1791]
These tests hanged until they reached the time limit for this reason (all Fluent versions, v222, v231, v232, v241): https://github.com/ansys/pyfluent/actions/runs/5512845380/jobs/10050274022

MWE, using latest Fluent v241 Docker image (created 15 days ago as of today):
```
import ansys.fluent.core as pyfluent

session = pyfluent.launch_fluent(start_container=True)

session.file.read(file_type="case", file_name="test.err")
```

Fluent and PyFluent seem to hang indefinitely after this point. It should raise a `RuntimeError: File "test.err" not found!`, as it does when running Fluent standalone.

This is the last gRPC trace before it hangs:
`GRPC_TRACE: rpc = /ansys.api.fluent.v0.settings.Settings/ExecuteCommand, request = {'pathInfo': {'root': 'fluent', 'path': 'file'}, 'command': 'read', 'args': {'valueMap': {'m': {'file-type': {'string': 'case'}, 'file-name': {'string': 'test.err'}}}}}`

Edit: Also reported by Dario Amadori to occur in clusters

**Comment by seanpearsonuk** [comment]
Seems related to #1947

**Comment by hpohekar** [comment]
@raph-luc @seanpearsonuk 

We are raising an exception if file does not exist.

![image](https://github.com/ansys/pyfluent/assets/106588300/065aff94-b8e3-4ee4-9c8d-65f6df5273c0)

Closing this now.
