### ISSUE TITLE
vector field data request crashes at least Fluent 23R1, 23R2, 24R1

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1811]
Running with an up-to-date local build of Fluent 24R1. The following usage is consistent with [the doc](https://fluent.docs.pyansys.com/version/stable/api/solver/fielddata.html). The data access call crashes Fluent,
hence the errors on the client side. I find this 100% reproducible. The same behaviour is however well covered in CI
via tests/test_field_data.py:test_field_data_objects_2d

```
>>> import ansys.fluent.core as pf
>>> s = pf.launch_fluent(show_gui=True, start_transcript=False)
>>> # ...read case, init and solve in Fluent...
>>> fd = s.field_data
>>> fd.is_data_valid()
True
>>> fd.get_vector_field_data.field_name.allowed_values()
['relative-velocity', 'velocity']
>>> fd.get_vector_field_data.surface_name.allowed_values()
['default-interior', 'pressure-outlet-7', 'symmetry', 'velocity-inlet-5', 'velocity-inlet-6', 'wall', 'z=0_out']
>>> # can also call with surface_name="velocity-inlet-5" with the same outcome:
>>> fd.get_vector_field_data(field_name='velocity', surface_name='pressure-outlet-7')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\services\field_data.py", line 358, in __call__
    return self._field_data_accessor(*args, **kwargs)
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\services\field_data.py", line 1351, in get_vector_field_data
    fields = ChunkParser().extract_fields(self._service.get_fields(fields_request))
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\services\field_data.py", line 818, in extract_fields
    for chunk in chunk_iterator:
  File "E:\ANSYSDev\pyfluent17\fieldhelp\lib\site-packages\grpc\_channel.py", line 426, in __next__
    return self._next()
  File "E:\ANSYSDev\pyfluent17\fieldhelp\lib\site-packages\grpc\_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:49157 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-07-18T11:39:21.41138161+00:00"}"
```

N.b. field_data method help is also rather sketchy.

**Comment by henriquedaponte** [comment]
I've been having the same issue. Let me know if you find a solution

**Comment by seanpearsonuk** [comment]
@cj-hodgson please can you try to reproduce this? @ajain-work is not able to reproduce it.

**Comment by cj-hodgson** [comment]
@seanpearsonuk I can also reproduce this.

**Comment by seanpearsonuk** [comment]
Thnaks @cj-hodgson

**Comment by seanpearsonuk** [comment]
@henriquedaponte 
please can you let me know your version of Fluent, thanks.

**Comment by henriquedaponte** [comment]
Ansys Student 2023 R1 @seanpearsonuk

**Comment by seanpearsonuk** [comment]
@henriquedaponte  thank you very much

**Comment by seanpearsonuk** [comment]
@ajain-work any idea what's going on here? This issue has apparently been lurking for some time.

**Comment by seanpearsonuk** [comment]
More details.
The simplest way to reproduce this is to launch fluent from PyFluent (or connect to fluent from PyFluent) and then execute e.g., `(fill-vector-field-data "velocity" '(3))` in the **Fluent** console. If you are running standalone Fluent or Fluent connected to some other client like remote visualization client then the behaviour is fine, but in the PyFluent scenario we get the crash as described. So far we know that this happens for at least 23R1...24R1. It also happens for PyFluent 0.10.0 (the earliest in PyPI), up to the current version. I didn't go any earlier because already at 0.10.0, pip complains about grpc incompatibility. I have isolated the area of code in Fluent where the issue is occurring.

**Comment by seanpearsonuk** [comment]
@ajain-work this was closed as #562 not reproducible, but it is apparently a persistent issue all this time

**Comment by henriquedaponte** [comment]
Is there any other functional way to collect velocity data while this bug is being fixed?

**Comment by henriquedaponte** [comment]
@seanpearsonuk @ajain-work @cj-hodgson Any updates?

**Comment by ajain-work** [comment]
@seanpearsonuk I will look into it and update.

**Comment by ajain-work** [comment]
@henriquedaponte 
Please execute following command before fetching vector field data
_solver.scheme_eval.string_eval("(surface? (thread-name->id 'surface-name))")_


_solver.scheme_eval.string_eval("(surface? (thread-name->id 'hot-inlet))")
solver.scheme_eval.string_eval("(surface? (thread-name->id 'cold-inlet))")
solver.scheme_eval.string_eval("(surface? (thread-name->id 'outlet))")_

 field_data = solver.field_data
 hot_inlet_velocity_mag = field_data.get_vector_field_data(field_name="velocity", surface_name="hot-inlet")
 cold_inlet_velocity_mag = field_data.get_vector_field_data(field_name="velocity", surface_name='cold-inlet')
 outlet_velocity_mag = field_data.get_vector_field_data(field_name="velocity", surface_name="outlet")

**Comment by seanpearsonuk** [comment]
@ajain-work 
I believe that we should insert the code to do this inside the PyFluent get_vector_field_data method itself. Do you agree? If so, I will assign the work within the team.

**Comment by seanpearsonuk** [comment]
@hpohekar please see the above code that needs to be inserted in both the client-side code (for released Fluent versions) and also the server-side code.

**Comment by seanpearsonuk** [comment]
Discussing with @hpohekar 
We need to construct:
`solver.scheme_eval.string_eval("(surface? (thread-name->id 'surface-name))")`
In the case of ids we need to construct:
```
for id in ids:
   solver.scheme_eval.string_eval("(surface? id)")
```

**Comment by seanpearsonuk** [comment]
@cj-hodgson I have forwarded this to the "testing" column - it was a significant issue.

**Comment by seanpearsonuk** [comment]
@henriquedaponte just in case I missed notifying you, this should be ready to use in PyFluent

**Comment by cj-hodgson** [comment]
@millerj97 Please can you test this. You'll need to test with 23R1, 23R2 and 24R1.
