### ISSUE TITLE
There needs to be solver.file.write_ equivalents to solver.file.read_case() solver.file.read_data()

### ISSUE THREAD

**Issue by AdamTheEngineer-dev** [ansys/pyfluent#1824]
### 📝 Description of the feature

There are two ways to read a case file:

solver.file.read(file_type="case", filename="my_case.cas.h5")
solver.file.read_case("my_case.cas.h5")

and the same for data files:

solver.file.read(file_type="data", filename="my_data.dat.h5")
solver.file.read_data("my_data.dat.h5")

but the shorter (safer?) forms:

solver.file.write_case("my_case.cas.h5")
solver.file.write_data("my_data.dat.h5")

 are not available for writing. Why?

### 💡 Steps for implementing the feature

Wrap the longer forms in an alias type function.
I assume this is the way it's done for the case and data read functions.

**Comment by mkundu1** [comment]
I'm trying to address the inconsistency part. The settings API commands don't accept positional arguments. In the latest code:

![Code_A9BSkvkQU7](https://github.com/ansys/pyfluent/assets/94432368/572b7f07-943a-46ca-a5f9-435a792a4dae)

What are the PyFluent and Fluent versions you are using?

**Comment by h-krishnan** [comment]
We should implement write_case etc. in settings API.
________________________________

**Comment by AdamTheEngineer-dev** [comment]
Fluent : Revision: 23.2.0 for ANSYS 2023 R2
Build Time: May 29 2023 07:52:07 EDT  Build Id: 10212

PyFluent version_info : 'Build date: July 11, 2023 12:29 UTC ShaID: 9c0be47'

**Comment by AdamTheEngineer-dev** [comment]
There is also an issue with passing strings back as they have to be explicitly wrapped in ""
Is there a helper function that detects a Python var's type and stringifies it correctly?

I have a routine that goes the other way from scheme to Python.

**Comment by AdamTheEngineer-dev** [comment]
I would assume, the functions that don't use the TUI do this in the background.

**Comment by mkundu1** [comment]
It is not clear to me how `solver.file.read_case("my_case.cas.h5")` (with positional arguments) is working for you. Are you using any wrapper code on top of PyFluent's API?

**Comment by seanpearsonuk** [comment]
@AdamTheEngineer-dev: with reference to @mkundu1's comments, did you perhaps write the example code from memory?

**Comment by h-krishnan** [comment]
write_case, write_data etc. have been added now.
