### ISSUE TITLE
Dictionary value assignement for periodic boundary condition

### ISSUE THREAD

**Issue by amonteyr** [ansys/pyfluent#1839]
Hi,
Basically, I want to set up boundary conditions of my fluent session.
I know I can do so using TUI, but I found lately that session.solution.boundary_conditions is of type dictionary and I find it very convenient.
I managed to assign values to the different keys for my inlet and outlet, but I can't do this for periodic zones.

Here is my code :
print(session.setup.boundary_conditions()['periodic']["zone1_per2_1"])
print(type(session.setup.boundary_conditions()['periodic']["zone1_per2_1"]))
session.setup.boundary_conditions()['periodic']["zone1_per2_1"]['angular']=False
print(session.setup.boundary_conditions()['periodic']["zone1_per2_1"])

Here the result :
_{'name': 'zone1_per2_1', 'angular': True}
<class 'dict'>
{'name': 'zone1_per2_1', 'angular': True}_

The 'angular' value is not modified.
Without parentesis at the end of boundary_conditions, I got "invalid key 'periodic'" error, even if boudary_conditions is of type dictionary with 'periodic' as on of the keys
With session.setup.boundary_conditions.periodic["zone1_per2_1"]['angular']=False, I got "TypeError: 'periodic_child' object does not support item assignment", as it is not anymore a dictionary, but a pyfluent object.

Well, as a conclusion : how can i change this dictionary value without using tui ? Why can I do this for inlet, outlet and not periodic ?

thank you.

**Comment by mkundu1** [comment]
`session.setup.boundary_conditions.periodic["zone1_per2_1"].angular = False` should set the value. 

To access the state:
```
session.setup.boundary_conditions.periodic["zone1_per2_1"].angular()
session.setup.boundary_conditions.periodic["zone1_per2_1"]()  # returns full state of the boundary condition
```
