### ISSUE TITLE
Add field_name in add_vector_fields_request and 'Faces' object has no attribute 'node_data'

### ISSUE THREAD

**Issue by hpohekar** [ansys/pyfluent#1848]
### Description of the modifications

https://fluent.docs.pyansys.com/version/stable/api/solver/fielddata.html

transaction.add_vector_fields_request(surface_ids=[1,2]) -> transaction.add_vector_fields_request(surface_ids=[1,2], field_name="velocity")

![image](https://github.com/ansys/pyfluent/assets/106588300/37c742f0-7db8-458f-8ed0-59f70a965762)

![image](https://github.com/ansys/pyfluent/assets/106588300/75b6b024-eac4-4a68-9f07-1be2261bad05)

`------------------------------------------------------------------------`

'Faces' object has no attribute 'node_data' -

![image](https://github.com/ansys/pyfluent/assets/106588300/dac9c37a-e866-45f6-b87c-13c7f2c12405)

### Useful links and references

https://fluent.docs.pyansys.com/version/stable/api/solver/fielddata.html

**Comment by hpohekar** [comment]
@seanpearsonuk

**Comment by seanpearsonuk** [comment]
@hpohekar thanks, I saw yourPR.
