### ISSUE TITLE
launch_fluent difficulties for a user

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1860]
@pysrg has reported that launch_fluent has today suddenly started failing. He gets PyFluent from PyPI and it was working on Friday but started failing today. He is using Fluent 23R1. I asked him to try launching Fluent first and then calling `session = connect_to_fluent(server_info_filepath=<server_info_filepath>)`. Only this method works for him. N.b. @prmukherj has tried out launch_fluent with 23R1 locally and it works fine for him. @pysrg is not connected to VPN when the issue occurs.

**Comment by seanpearsonuk** [comment]
![MicrosoftTeams-image](https://github.com/ansys/pyfluent/assets/93727996/30f62c94-59e8-490e-b561-df84f6268a51)

**Comment by raph-luc** [comment]
Our exception hiding there is very unhelpful, going to suggest an improvement so that it reports what the exception caught was

**Comment by seanpearsonuk** [comment]
> Our exception hiding there is very unhelpful, going to suggest an improvement so that it reports what the exception caught was

Yes, @prmukherj and I happened to be looking at this code today, and saying the same,

**Comment by mkundu1** [comment]
I think `raise LaunchFluentError(launch_string) from ex` would show the original exception also. @PySRG Are there more lines above launcher.py:731 in the output message?
