### ISSUE TITLE
Requesr for details on offline installation of pyfluent.

### ISSUE THREAD

**Issue by Krishna935028** [ansys/pyfluent#1878]
Hi all,
I'm trying to install pyfluent in a virtual desktop. The desktop is not connected to internet. could any one guide me on how to install pyfluent in offline mode?

**Comment by mkundu1** [comment]
Following this [SO answer](https://stackoverflow.com/a/14447068), I tested the following steps:
1. Download .whl files of ansys-fluent-core and its dependencies in a local directory
```
pip download ansys-fluent-core
```
2. Install pyfluent from the downloaded .whl files in a clean virtual environment
```
pip install --no-index --find-links /path/to/download/dir/ ansys-fluent-core
```
Then I can use pyfluent normally. I haven't tested on an offline machine, so let us know if this works.
