### ISSUE TITLE
Runtime error when running "solver.tui.adjoint.design_tool.design_change.modify_mesh()"

### ISSUE THREAD

**Issue by answillgm** [ansys/pyfluent#1931]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When "solver.tui.adjoint.design_tool.design_change.modify_mesh()" is called, runtime error is thrown

Traceback (most recent call last):
  File "D:\Bugs\Reproduce Pyfluent\python version\adj_cylinder_tui_s1.py", line 48, in <module>
    solver.tui.adjoint.design_tool.design_change.modify_mesh()
  File "E:\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 308, in __call__
    return PyMenu(self.service, self.path).execute(*args, **kwargs)
  File "E:\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 206, in execute
    return self._execute_command(request)
  File "E:\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 172, in _execute_command
    ret = self._service.execute_command(request)
  File "E:\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: ()
Error Object: #f

### 📝 Steps to reproduce

1. Download and unzip "reproduce.zip"
2. Run "python adj_cylinder_tui_s1.py"

[reproduce.zip](https://github.com/ansys/pyfluent/files/12474438/reproduce.zip)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
absl-py==1.4.0
ansi2html==1.8.0
ansys-api-fluent==0.3.15
ansys-api-platform-instancemanagement==1.0.0
-e e:\pyfluent
-e e:\pyfluent-parametric
-e e:\pyfluent-visualization
ansys-platform-instancemanagement==1.1.2
asttokens==2.2.1
astunparse==1.6.3
backcall==0.2.0
bcrypt==4.0.1
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
dash==2.12.1
dash-bootstrap-components==1.4.2
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
docker==6.1.3
et-xmlfile==1.1.0
executing==1.2.0
Flask==2.2.5
flatbuffers==23.5.26
fonttools==4.42.1
gast==0.4.0
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.57.0
grpcio-health-checking==1.48.2
h5py==3.9.0
idna==3.4
imageio==2.31.1
importlib-metadata==6.8.0
ipython==8.14.0
itsdangerous==2.1.2
jedi==0.19.0
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
keras==2.13.1
kiwisolver==1.4.4
libclang==16.0.6
lxml==4.9.3
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
nest-asyncio==1.5.7
numpy==1.24.3
oauthlib==3.2.2
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.1
pandas==2.0.3
paramiko==3.3.1
paramiko-expect==0.3.5
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
plotly==5.16.1
pooch==1.7.0
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.16.1
PyNaCl==1.5.0
pyparsing==3.0.9
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
python-dateutil==2.8.2
python-pptx==0.6.21
pytz==2023.3
pyvista==0.41.1
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
QtPy==2.3.1
requests==2.31.0
requests-oauthlib==1.3.1
retrying==1.3.4
rsa==4.9
scikit-learn==1.3.0
scipy==1.11.2
scooby==0.7.2
seaborn==0.12.2
shiboken6==6.5.2
six==1.16.0
stack-data==0.6.2
tenacity==8.2.3
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow==2.13.0
tensorflow-estimator==2.13.0
tensorflow-intel==2.13.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.3.0
threadpoolctl==3.2.0
traitlets==5.9.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.16
vtk==9.2.6
wcwidth==0.2.6
websocket-client==1.6.2
Werkzeug==2.2.3
wrapt==1.15.0
xgboost==1.7.6
XlsxWriter==3.1.2
zipp==3.16.2
```

**Comment by seanpearsonuk** [comment]
Please could you triage this?

**Comment by hpohekar** [comment]
Given script works fine in 231 and 232 gives error in 241.

Server side works fine in 241, issue is from client side only.

![image](https://github.com/ansys/pyfluent/assets/106588300/22784ee5-b3cc-4e66-aa9e-80e788cc9442)

**Comment by answillgm** [comment]
@hpohekar Has this now been fixed? The test in question now passes with no issues

**Comment by hpohekar** [comment]
We have not pushed any specific fix for this issue. We found that local build was giving an error for `adjoint` otherwise it is working as mentioned above.

**Comment by hpohekar** [comment]
@answillgm If it is passing without any issue then may be we can close this now. Thanks.
