### ISSUE TITLE
Fluent meshing TUI command gives error through execute_tui

### ISSUE THREAD

**Issue by sravanansys** [ansys/pyfluent#1936]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Hi,

It seems that not all TUI commands are available through TUI API. I was trying to adjust graphic views through TUI through execute_tui command. Most of them worked except the following

`meshing.execute_tui("display views camera roll-camera 270")`

It returns the following error in fluent console

![image](https://github.com/ansys/pyfluent/assets/99287292/eb10ccf9-61c9-4c54-8aae-7ab2941f208d)

If I use `scheme_eval.string_eval(command)`, it works fine.

### 📝 Steps to reproduce

Use any meshing script or mixing elbow case and after generating the mesh, execute the following command

`meshing.execute_tui("display views camera roll-camera 270")`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.15
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.17.0
ansys-fluent-parametric==0.7.1
ansys-fluent-visualization==0.7.1
ansys-platform-instancemanagement==1.1.2
asttokens==2.2.1
backcall==0.2.0
certifi==2023.7.22
charset-normalizer==3.2.0
colorama==0.4.6
comm==0.1.4
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7.post1
decorator==5.1.1
docker==6.1.3
executing==1.2.0
fonttools==4.42.1
grpcio==1.57.0
grpcio-health-checking==1.48.2
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
ipykernel==6.25.1
ipython==8.14.0
jedi==0.19.0
jupyter_client==8.3.1
jupyter_core==5.3.1
kiwisolver==1.4.5
lxml==4.9.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
nest-asyncio==1.5.7
numpy==1.25.2
packaging==23.1
pandas==2.0.3
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
pooch==1.7.0
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
Pygments==2.16.1
pyparsing==3.0.9
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
python-dateutil==2.8.2
pytz==2023.3
pyvista==0.41.1
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.1
QtPy==2.4.0
requests==2.31.0
scooby==0.7.2
shiboken6==6.5.2
six==1.16.0
stack-data==0.6.2
tornado==6.3.3
traitlets==5.9.0
tzdata==2023.3
urllib3==2.0.4
vtk==9.2.6
wcwidth==0.2.6
websocket-client==1.6.2
zipp==3.16.2
```

**Comment by mkundu1** [comment]
For these TUIs, the TUI hierarchy is not correctly extracted on the Fluent side. This is causing issues in Fluent's Python console also. I'll have a look into that.

The `execute_tui` is a separate issue, will merge a fix in PyFluent.
