### ISSUE TITLE
Issue in opening a gui on remote machine

### ISSUE THREAD

**Issue by pavankumarkonchada** [ansys/pyfluent#1949]
when using the launch_fluent on remote machine from app service , gui is not getting open. Instead it is running in the background. But I need to get space claim open to do the necessary modification on geometry and then send it to fluent. Any suggestion will be really appreciated.

**Comment by seanpearsonuk** [comment]
@PyPablo do you or Adam A (I cannot find him to tag) want to pick this up? I will assign to you as a placeholder, thanks.

**Comment by pavankumarkonchada** [comment]
Just for information I am using ssh protocol for connection

**Comment by seanpearsonuk** [comment]
@pavankumarkonchada could you please post this on the Ansys developer portal instead.

https://developer.ansys.com/

**Comment by pavankumarkonchada** [comment]
Hi nobody from ansys development team has responded on that
