### ISSUE TITLE
Error in meshing mode - Workflow API

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#1968]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Following image describes the issue 
<img width="863" alt="image" src="https://github.com/ansys/pyfluent/assets/97435870/41b8e852-e22c-4079-810d-9f2b72412c1e">

@seanpearsonuk @mkundu1 

### 📝 Steps to reproduce

>>> session = pyfluent.launch_fluent(start_transcript=False, mode="meshing", start_watchdog=False)
>>> session.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core 0.17.0
```

**Comment by raph-luc** [comment]
See the first line in your console output: 
![image](https://github.com/ansys/pyfluent/assets/132297401/03a5751f-7aa9-4cc8-86bc-e2f4d8854e5e)

As you are using Ansys v241, you need to run `python codegen/allapigen.py` to generate the required API files

**Comment by tejalprabhu01** [comment]
@raph-luc we are adding ansys-fluent-core in optiSLang python. How can we run the python command before using pyfluent in optiSLang?

**Comment by raph-luc** [comment]
`pip install ansys-fluent-core` is sufficient for the latest publicly released Ansys Fluent version, which currently is v232. Fluent v241 is still in active development and unreleased. 

I apologize but I am not familiar with what you are doing with optiSLang, will wait for the others to provide better input.

Also, you tagged the GitHub user "mk" in your original post, Martin Kavalar, who I believe has nothing to do with Ansys. Did you mean to tag @mkundu1 ?

**Comment by tejalprabhu01** [comment]
> `pip install ansys-fluent-core` is sufficient for the latest publicly released Ansys Fluent version, which currently is v232. Fluent v241 is still in active development and unreleased.
> 
> I apologize but I am not familiar with what you are doing with optiSLang, will wait for the others to provide better input.
> 
> Also, you tagged the GitHub user "mk" in your original post, Martin Kavalar, who I believe has nothing to do with Ansys. Did you mean to tag @mkundu1 ?

Sorry, I mean mkundu1. Thanks for your support!
