### ISSUE TITLE
Strongly-typed version checks

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1973]
Comment from https://github.com/ansys/pyfluent/pull/1961:

It should be safe to write `>=` here. I would prefer it if we had a function that we could call for all such queries. Something like:
`if ansys_versions.current >= ansys_versions.version_24_1`:
```suggestion
    if ansys_version >= "24.1.0":
```

**Comment by ansaboutin** [comment]
Where would the ansys_versions function live?

**Comment by seanpearsonuk** [comment]
E.g.,

```
from ansys.fluent.core import version
if version.current > version.v24R1:
   ...

if version.current <= version.v23R2:
  ...

if version.current != version.v23R1:
  ...

# etc

```

**Comment by ansaboutin** [comment]
Would it make sense to add the comparison dunder methods here: 
![image](https://github.com/ansys/pyfluent/assets/143635850/5cafb2d5-2102-4111-a877-5e9a676c23be)
and change `get_ansys_version()` to return a FluentVersion attribute?

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk Would it make sense to add the comparison dunder methods here: ![image](https://user-images.githubusercontent.com/143635850/270461435-5cafb2d5-2102-4111-a877-5e9a676c23be.png) and change `get_ansys_version()` to return a FluentVersion attribute?

Yes
