### ISSUE TITLE
Check settings API angles

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1991]
Moved from point 4 in https://github.com/ansys/pyansys-units/issues/25

```
>>> v = Quantity(60.0, "ft")
>>> float(v)
18.287999999999997 
>>> v = Quantity(45.0, "degree")
>>> float(v)
0.7853981633974483
```
the angle behaviour is important because it means we have easy interaction with trig functions etc. But I have one question about this. Fluent SI uses degrees, not radians (no idea why). Need to check what the API does before we start using this stuff seriously and make sure if we're relying on these conversions that we're properly taking account of the API's peculiarities.

**Comment by h-krishnan** [comment]
@seanpearsonuk I think only the default display unit for angle is deg. The API will probably still expect the value to be in radians.

**Comment by seanpearsonuk** [comment]
Thanks @h-krishnan I will close this now
