### ISSUE TITLE
TUI transformation

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2025]
We get many issues marked "bug" that state: I invoked `solver.tui...foo("no", "no", "no", "yes")` and got the following error...

The following is partway useful:

https://fluent.docs.pyansys.com/version/stable/user_guide/tui_commands.html

but it pre-dates our journaling capability, so that the instructions advise the user to construct the Python calls manually which is error-prone, and it also misses out the possibility of automagic transformation to a settings API call.

- First, let's update this documentation to reflect this degree of automation
- Also, it's a very important piece of documentation, so we want to emphasize it right at the beginning of te documentation.
- Can we streamline the conversion in ways beyond what we are doing?
  - e.g., build optional creation of equivalent Python commands in run_menu (e.g., menu_topy("define/materials/change-create")) which dumps out the Python command at the end. We would want all these things also available if possible in PyFluent!
  - e.g., solver.tui.advise_api_upgrades(). We can use the journaling mechanism in the background to detect when a tui call is transformed. We can simply return `(return_value, settings_call | None)`.

cc: @mkundu1

**Comment by mkundu1** [comment]
@seanpearsonuk 

> Can we streamline the conversion in ways beyond what we are doing?

For either option, we need to execute the TUI to know whether an equivalent settings API command is available. If we need to type `menu_topy("define/materials/change-create"))` in legacy or Python console, we will lose the TUI interactivity. I think a better option could be whenever we type a TUI in Fluent's legacy console, Fluent's Python console or PyFluent, we will print the advice that an equivalent settings API command is available. This can be the default behaviour (behind beta in Fluent) for interactive sessions.

**Comment by mkundu1** [comment]
Implemented on PyFluent side, remaining work is on Fluent side (24.2)

**Comment by mkundu1** [comment]
Closing as the feature is now available in the new pyconsole implmentation.
