### ISSUE TITLE
toggle-prompt

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2038]
https://sphinx-toggleprompt.readthedocs.io/en/latest/

pyfluent, but also wherever appropriate for other packages

**Comment by hpohekar** [comment]
sphinx_toggleprompt==0.4.0 needs sphinx <7 and >4.5.

![image](https://github.com/ansys/pyfluent/assets/106588300/c99047a4-ba9e-4bb7-b807-edb50f8e2671)

![image](https://github.com/ansys/pyfluent/assets/106588300/32ead0ac-64f0-402a-a20c-55e7699c5a2f)

We need to wait until sphinx_toggleprompt supports sphinx>=7.1.2
