### ISSUE TITLE
Fix issues in FAQ page

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2050]
formatting issues, outdated info about journaling etc.

**Comment by raph-luc** [comment]
- https://fluent.docs.pyansys.com/version/stable/getting_started/faqs.html#how-do-you-install-pyfluent

![image](https://github.com/ansys/pyfluent/assets/132297401/b4a3a2f1-8dd6-486f-86d2-f4c5b3c59eb4)

- https://fluent.docs.pyansys.com/version/stable/getting_started/faqs.html#how-do-you-learn-how-to-use-pyfluent

![image](https://github.com/ansys/pyfluent/assets/132297401/71b34808-784a-4b70-aa0c-ab0dd6f7ca1d)
