### ISSUE TITLE
bogus settings report object?

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2064]
```
    @property
    def report(self):
        """Settings for report."""
        return self._root.report
```
in session_solver.py. Ideally we should not hard-code these children here but generate them instead.

**Comment by seanpearsonuk** [comment]
As confirmed by @h-krishnan report has been removed from the root of the API (now under results). We should remove report in the first instance. 

Also, we should remove all these explicit properties that reflect API objects.

**Comment by prmukherj** [comment]
@mkundu1, please add your views.

**Comment by mkundu1** [comment]
We currently have these explicit properties, so the settings API can be called lazily. During the first call to settings API, static-info is fetched from the server. In-memory classes are generated in the client if there is a hash mismatch with already generated files (through codegen). Can we do a timing comparison between both approaches and decide based on that? We can compare the timing of `dir(solver)`. Make sure there is a hash mismatch (the message ""Mismatch between ..." will be shown). Note that, users will see this hash mismatch whenever they use a PyFluent version released after Fluent's API freeze, which is a common scenario.

**Comment by mkundu1** [comment]
One solution could be to dynamically create those properties from the codegen-generated files (without calling the server).
