### ISSUE TITLE
Testing: Explicit attribute accessor methods on settings objects

### ISSUE THREAD

**Issue by cj-hodgson** [ansys/pyfluent#2090]
See issue #618 - https://github.com/ansys/pyfluent/issues/618

**Comment by millerj97** [comment]
@cj-hodgson features regression test "attribute_methods" gives coverage of the methods in issue #618. `is_list, min_max, vals` list items are appended to the remaining list items below to test. Extra step included to ensure invalid combinations are treated correctly.

![Image](https://github.com/ansys/pyfluent/assets/126583804/2118d13d-e41a-4887-907b-1e9a1336603d)
