### ISSUE TITLE
test_mixing_elbow issue

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2116]
From https://github.com/ansys/pyfluent/actions/runs/6452187156/job/17513840455#step:26:1119,
```
FAILED tests/test_cad_to_post_wtm.py::test_mixing_elbow - UnboundLocalError: local variable 'velocity_inlet' referenced before assignment
```

Not sure how the test is passing for other Fluent versions

**Comment by ansaboutin** [comment]
Should this be changed as well?
![image](https://github.com/ansys/pyfluent/assets/143635850/93f02793-991b-45b3-8128-404285a93815)
