### ISSUE TITLE
Examples have some Python warnings in the output

### ISSUE THREAD

**Issue by dnwillia-work** [ansys/pyfluent#2117]
### Description of the modifications

The output for the solve commands

https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/exhaust_system.html#start-calculation
https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/external_compressible_flow.html#solve-for-25-iterations

are showing some warnings in the monitor_streaming module, in the compressible flow example none of the iteration output is shown either.

**Comment by raph-luc** [comment]
Also in the `external_compressible_flow` example: 
![image](https://github.com/ansys/pyfluent/assets/132297401/7d821d00-45f1-4104-b3ae-872570d2a010)
And I think those parentheses around the file name (in the text, not in the code line) could be removed as well
