### ISSUE TITLE
Not able to display 3D vector plot using PyFluent visualization

### ISSUE THREAD

**Issue by mkvani** [ansys/pyfluent#2124]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While trying to display a vector plot, it shows following message and shows static image instead of 3D interactive plot.

#########################################

d:\users\mvani\PyWB\PyWB-examples\pyworkbench-examples\pywb_env\lib\site-packages\pyvista\jupyter\notebook.py:33: UserWarning: Failed to use notebook backend: 

No module named 'trame'

Falling back to a static output.
  warnings.warn(
#########################################

### 📝 Steps to reproduce

After solving, I am trying to plot vectors by following commands:

################################################

graphics_session_vec = Graphics(fluent_session)
velocity_vector = graphics_session_vec.Vectors["velocity-vector"]
velocity_vector.field = "temperature"
velocity_vector.surfaces_list = ["symmetry-xyplane"]
velocity_vector.scale = 2
velocity_vector.display()

################################################

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024 R1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.17                              
ansys-api-platform-instancemanagement==1.0.0
ansys-api-workbench==0.1.7
ansys-fluent-core==0.17.1
ansys-fluent-visualization==0.7.1
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc1
ansys-tools-path==0.3.1
ansys-workbench-core==0.3.dev0
asttokens==2.4.0
backcall==0.2.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
clr-loader==0.2.6
colorama==0.4.6
comm==0.1.4
contourpy==1.1.1
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
docker==6.1.3
executing==1.2.0
fonttools==4.43.1
grpcio==1.58.0
grpcio-health-checking==1.48.2
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
ipykernel==6.25.2
ipython==8.12.2
jedi==0.19.0
jupyter-client==8.3.1
jupyter-core==5.3.1
kiwisolver==1.4.5
lxml==4.9.3
matplotlib==3.7.3
matplotlib-inline==0.1.6
nest-asyncio==1.5.8
numpy==1.24.4
packaging==23.1
pandas==2.0.3
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.1
platformdirs==3.10.0
pooch==1.7.0
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
pyparsing==3.1.1
PySide6==6.5.3
PySide6-Addons==6.5.3
PySide6-Essentials==6.5.3
python-dateutil==2.8.2
pytz==2023.3.post1
pyvista==0.42.3
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.1
QtPy==2.4.0
requests==2.31.0
scooby==0.7.4
shiboken6==6.5.3
six==1.16.0
stack-data==0.6.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.10.0
typing-extensions==4.8.0
tzdata==2023.3
urllib3==2.0.5
vtk==9.2.6
wcwidth==0.2.6
websocket-client==1.6.3
WMI==1.5.1
zipp==3.17.0
```

**Comment by dnwillia** [comment]
@mkvani can you put this into the visualization repo?

**Comment by mkvani** [comment]
@dnwillia , done: logged here: https://github.com/ansys/pyfluent-visualization/issues/349

Thank you,
Manoj

**Comment by mkvani** [comment]
Logged in correct repo as suggested by @dnwillia 

https://github.com/ansys/pyfluent-visualization/issues/349
