### ISSUE TITLE
Tutorial needs update due to changes in API

### ISSUE THREAD

**Issue by mkvani** [ansys/pyfluent#2137]
### Description of the modifications

Settings API [tutorial ](https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow_settings_api.html) is not working. 

It gives following errors:

1) Velocity inlet settings API:
#################################
  File "d:/users/mvani/PyFluent/check_mixing_elbow/mixing_elbow_tut/mixing_elbow_settings_api.py", line 101, in <module>
    cold_inlet.vmag = 0.4
  File "d:\users\mvani\PyFluent\check_mixing_elbow\envpyfluent\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 529, in __setattr__
    raise AttributeError(
AttributeError: vmag is not an allowed Settings objects name.

#################################

2) Hot inlet settings API:

#############################
  File "d:/users/mvani/PyFluent/check_mixing_elbow/mixing_elbow_tut/mixing_elbow_settings_api.py", line 116, in <module>
    hot_inlet.vmag = 1.2
  File "d:\users\mvani\PyFluent\check_mixing_elbow\envpyfluent\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 529, in __setattr__
    raise AttributeError(
AttributeError: vmag is not an allowed Settings objects name.
The most similar names are: thermal.
##############################

3) Outlet setting API:

############################
  File "d:/users/mvani/PyFluent/check_mixing_elbow/mixing_elbow_tut/mixing_elbow_settings_api.py", line 126, in <module>
    solver.setup.boundary_conditions.pressure_outlet["outlet"].turb_viscosity_ratio = 4
  File "d:\users\mvani\PyFluent\check_mixing_elbow\envpyfluent\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 529, in __setattr__
    raise AttributeError(
AttributeError: turb_viscosity_ratio is not an allowed Settings objects name.
############################

4) Mass flow rate reporting API:

###############################
  File "d:/users/mvani/PyFluent/check_mixing_elbow/mixing_elbow_tut/mixing_elbow_settings_api.py", line 176, in <module>
    mass_flow_rate.zone_names.get_attr("allowed-values")
  File "d:\users\mvani\PyFluent\check_mixing_elbow\envpyfluent\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 518, in __getattribute__
    raise AttributeError(
AttributeError: zone_names is not an allowed Settings objects name.

###################################

### Useful links and references

https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow_settings_api.html

###

Fluent version: 2024R1

Python modules:

ansys-api-fluent==0.3.18
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.17.1
ansys-platform-instancemanagement==1.1.2
certifi==2023.7.22
charset-normalizer==3.3.0
docker==6.1.3
grpcio==1.59.0
grpcio-health-checking==1.48.2
h5py==3.10.0
idna==3.4
importlib-metadata==6.8.0
lxml==4.9.3
numpy==1.24.4
packaging==23.2
pandas==2.0.3
platformdirs==3.11.0
protobuf==3.20.3
psutil==5.9.5
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32==306
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
tzdata==2023.3
urllib3==2.0.6
websocket-client==1.6.4
zipp==3.17.0

**Comment by mkvani** [comment]
I have the updated tutorial. Should I create a PR or share separately?

**Comment by mkundu1** [comment]
@mkvani The tutorials are based on the current release version of Fluent which is 2023 R2. If the changes are for Fluent 2024 R1, please create a draft PR. We shall merge it after 2024 R1 release.

**Comment by ansjsia** [comment]
I've created a PR for this: https://github.com/ansys/pyfluent/pull/2214

**Comment by raph-luc** [comment]
Thanks @ansjsia, the tests won't pass and we can't merge that PR for now as the documentation build runs on the latest released version (currently 23.2). 

As Mainak said, we will review and merge this after 2024 R1 release, and after the repo is updated to support the new release.

**Comment by dnwillia-work** [comment]
@ansjsia Why don't you update the CI/CD pipeline in your PR to run 24.1 then we can see the documentation builds.

**Comment by ansjsia** [comment]
> @ansjsia Why don't you update the CI/CD pipeline in your PR to run 24.1 then we can have a look at the documentation builds.

24R1 doc build is completed and artifacts are available!
