### ISSUE TITLE
24R1 tests are failing

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2141]
There was a new 2024 R1 container release about 2 hours ago, and 24R1 tests are failing:
https://github.com/ansys/pyfluent/pull/2125: https://github.com/ansys/pyfluent/actions/runs/6508615503/job/17678449736?pr=2125 
https://github.com/ansys/pyfluent/pull/2138: https://github.com/ansys/pyfluent/actions/runs/6508122618/job/17676999074?pr=2138
https://github.com/ansys/pyfluent/pull/2131: https://github.com/ansys/pyfluent/actions/runs/6508470332/job/17678023490?pr=2131
https://github.com/ansys/pyfluent/pull/2139: https://github.com/ansys/pyfluent/actions/runs/6508893335/job/17679313197?pr=2139
``` 
FAILED tests/test_rp_vars.py::test_get_and_set_rp_vars - RuntimeError: number-of-iterations is not an allowed rp-vars name.
FAILED tests/test_rp_vars.py::test_get_all_rp_vars - TypeError: unhashable type: 'list'
FAILED tests/test_rp_vars.py::test_rp_vars_allowed_values - RuntimeError: number-of-iterations is not an allowed rp-vars name.
```

**Comment by mkundu1** [comment]
The tests fail in the latest docker image but pass in the develop branch. We can skip the tests until the image is updated.

**Comment by mkundu1** [comment]
Apart from #2174, `test_get_all_rp_vars` overwrites the original case. We should avoid that.
