### ISSUE TITLE
Examples use graphics commands that don't output anything to PyFluent user executing them

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2164]
See https://github.com/ansys/pyfluent/pull/2102#discussion_r1363879683 and discussion

Other examples that do this:
https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/exhaust_system.html#create-contours-of-velocity-magnitude
https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow.html#create-definition-for-velocity-magnitude-contours
https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow_settings_api.html#create-velocity-vectors

**Comment by dnwillia** [comment]
Yeah that's a fair point.  We could include the equivalent commands in these examples to generate the required static images.

**Comment by raph-luc** [comment]
An example of how this can be unintuitive to customers: https://github.com/ansys/pyfluent/discussions/2297#discussioncomment-7838251

@ansjsia

**Comment by ansjsia** [comment]
@dnwillia @raph-luc Perhaps as part of the 24R1 example upgrades, we should add commands to save images to disk after calling `display()` for examples that don't use PyFluent Visualization, as I did for the species transport example: https://github.com/ansys/pyfluent-examples/pull/100

I'm happy to take the lead on making the required changes.

**Comment by raph-luc** [comment]
Sounds like a big improvement to me. Ideally, in the long term, we'd have a method to stream the image data from the server directly to a Python display window without having to write to disk, but what you suggest is much better than not showing anything to the user. 

Thanks @ansjsia!

**Comment by ansjsia** [comment]
@raph-luc I imagine that would involve more integration with PyVista/PyFluent Visualization?

**Comment by raph-luc** [comment]
Ideally, yes
