### ISSUE TITLE
Errors related to monitors

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2188]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

A customer reported following errors while using pyfluent from Fluent nodes in optiSLang:
![image002](https://github.com/ansys/pyfluent/assets/97435870/326c148d-9a80-4406-b1ad-3dfb3f758cff)
![image003](https://github.com/ansys/pyfluent/assets/97435870/39de7c67-1565-497d-bdee-934a318bb04b)
![image001](https://github.com/ansys/pyfluent/assets/97435870/0570accb-eb07-4ab1-83c1-e630024b96a0)

@seanpearsonuk @ajain-work 

### 📝 Steps to reproduce

Unfortunately I donot know which command leads to this, since it was reproduced on the customer machine. If more information is required, Please let me know. 

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by seanpearsonuk** [comment]
Thank you for submitting this, @tejalprabhu01.

Yes, for the customer's sake, if they can provide the ful details, it will help in finding a solution.

**Comment by hpohekar** [comment]
@seanpearsonuk @tejalprabhu01 

I have investigated it now.

The primary guess is that the user has either not read data file or not called `iterate()` before executing methods of `solver_session.monitors_manager`.

e.g 
```
solver_session.monitors_manager.get_monitor_set_names()
solver_session.monitors_manager.get_monitor_set_data(monitor_set_name="residual")
```

Normal solver session

```
>>> import ansys.fluent.core as pyfluent
>>> from ansys.fluent.core import examples
>>> import_case = examples.download_file(file_name="exhaust_system.cas.h5", directory="pyfluent/exhaust_system")
Checking if specified file already exists...
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.cas.h5
>>> import_data = examples.download_file(file_name="exhaust_system.dat.h5", directory="pyfluent/exhaust_system")
Checking if specified file already exists...
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.dat.h5
>>> solver_session = pyfluent.launch_fluent(precision="double", processor_count=2, start_transcript=False, mode="solver", cleanup_on_exit=False)
```

Monitors list empty now.

```
>>> monitors_list = solver_session.monitors_manager.get_monitor_set_names()
>>> monitors_list
[]
```

Monitors list is still empty after reading case file

```
>>> solver_session.tui.file.read_case(import_case)                                                                                               
pyfluent.tui WARNING: Currently calling the TUI commands in a generic manner. Please run `python codegen/allapigen.py` from the top-level pyfluent directory to generate the local TUI commands classes.
The following solver settings object method could also be used to execute the above command:
<solver_session>.file.read_case(file_name = r"C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.cas.h5")
>>> monitors_list = solver_session.monitors_manager.get_monitor_set_names()
>>> monitors_list
[]
```

We get monitors list only after reading a case file or after calling `iterate()` method.

```
>>> solver_session.tui.file.read_data(import_data)                          
The following solver settings object method could also be used to execute the above command:
<solver_session>.file.read_data(file_name = r"C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\exhaust_system.dat.h5")
>>> monitors_list = solver_session.monitors_manager.get_monitor_set_names()
>>> monitors_list
['residual', 'mass-bal-rplot', 'mass-tot-rplot', 'mass-in-rplot', 'point-vel-rplot']
```

calling `iterate()` method.

```
>>> solver_session.tui.solve.set.number_of_iterations(15)
The following solver settings object method could also be used to execute the above command:
<solver_session>.solution.run_calculation.iter_count = 15
>>> solver_session.tui.solve.iterate()
The following solver settings object method could also be used to execute the above command:
<solver_session>.solution.run_calculation.iterate(iter_count = 15)
>>> solver_session.monitors_manager.get_monitor_set_names()
['residual', 'mass-bal-rplot', 'mass-tot-rplot', 'mass-in-rplot', 'point-vel-rplot']
```

I also verified following source code behavior (shared by user in 1st screenshot). It's working fine.

![image](https://github.com/ansys/pyfluent/assets/106588300/6c107c7f-3c18-4de7-89dc-7900ec828cbf)

```
>>> for monitor_set_name, monitor_set_info in solver_session.monitors_manager._monitors_info.items():
...     print(monitor_set_info["monitors"])                                
... 
['continuity', 'x-velocity', 'y-velocity', 'z-velocity', 'energy', 'k', 'omega']
['mass-bal']
['mass-tot']
['mass-in']
['point-vel']
>>>
```

**Comment by hpohekar** [comment]
@seanpearsonuk @tejalprabhu01 

@ajain-work and I tried to reproduce this bug and we are able to reproduce this.

We will create a PR soon.

Thank you.
