### ISSUE TITLE
CI unit testing passes but action gets stuck and times out after 6 hours

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2196]
No test failures reported and test finishes successfully, but action times out with `Error: The operation was canceled.`

https://github.com/ansys/pyfluent/actions/runs/6671093343/job/18132700125
Logs: [6671093343.txt](https://github.com/ansys/pyfluent/files/13239141/6671093343.txt)

https://github.com/ansys/pyfluent/actions/runs/6722252147/job/18270609195
Logs: [6722252147.txt](https://github.com/ansys/pyfluent/files/13239154/6722252147.txt)

https://github.com/ansys/pyfluent/actions/runs/6714740063/job/18248689443
Logs: [6714740063.txt](https://github.com/ansys/pyfluent/files/13239146/6714740063.txt)

**Comment by mkundu1** [comment]
Probably some temporary issue, as unittests are completed in some of the later runs - https://github.com/ansys/pyfluent/actions/workflows/ci.yml

**Comment by raph-luc** [comment]
I don't know if it was a temporary issue or if it is a random failure, the actions that got stuck that I linked above happened over the past week, seemingly randomly, they didn't all occur at the same time. Let's try to track if additional actions fail again in the same way.

**Comment by raph-luc** [comment]
We just had another one with the exact same behavior:
https://github.com/ansys/pyfluent/actions/runs/6736759425/job/18313318670
[6736759425.txt](https://github.com/ansys/pyfluent/files/13253609/6736759425.txt)

**Comment by raph-luc** [comment]
https://github.com/ansys/pyfluent/actions/runs/6872087832/job/18690292730
[6872087832.txt](https://github.com/ansys/pyfluent/files/13368116/6872087832.txt)

I wonder if this is an issue with `pytest`

**Comment by raph-luc** [comment]
Another one, same issue:
https://github.com/ansys/pyfluent/actions/runs/7171908338/job/19528475746?pr=2305
[7171908338.txt](https://github.com/ansys/pyfluent/files/13648933/7171908338.txt)
