### ISSUE TITLE
Issues with closing fluent sessions

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2208]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

We have noticed some of the errors like the one in screenshot arent received back by pyfluent. This leads to further errors and fails closing the fluent session
![image](https://github.com/ansys/pyfluent/assets/97435870/82ea5e23-2702-49b3-9d99-cb3506800b21)

@seanpearsonuk @mkundu1 

### 📝 Steps to reproduce

This error typically comes up when multiple fluent meshing sessions are launched and all of them try to import the geometry at the same time. To reproduce the error, start multiple fluent sessions and try to import geometry in them at same time and then try to close the sessions.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by prmukherj** [comment]
@tejalprabhu01, Whether there are any specific file type where this is likely to happen?

**Comment by tejalprabhu01** [comment]
@prmukherj this used to happen when multiple fluent meshing sessions were launched in parallel. There was a bug related to this error on Fluent meshing side. But this issue is now fixed. I have not seen this error lately.
