### ISSUE TITLE
RP var service unable to update underlying object

### ISSUE THREAD

**Issue by answillgm** [ansys/pyfluent#2250]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When using the rp var functionality, some simple variables when updated will show in the editor, and persist after saving and reloading. However, some complex rp vars (such as "monitors/report-definitions") when updated will show this change in pyfluent, but not in the gui, and on saving and reloading, the original rp var will show in pyfluent and the gui.

### 📝 Steps to reproduce

1. Download the attached zip and run python in the produced directory
2. Run the following code in the console:

```
import ansys.fluent.core as pyfluent
flglobals = pyfluent.setup_for_fluent(product_version="24.1.0", mode="solver", version="2d", precision="double", processor_count=1, show_gui=True)
globals().update(flglobals)
solver.file.read_case_data(file_name = "noz_ss.cas.h5")
```

3. Call `solver.rp_vars("monitor/report-definitions")` - this should get the complex list representation of the object and produce this output:

`[[('name', '"mass_flowrate_out"'), ['report-definition', 'surface-massflowrate', ['surface-ids', 1], ['surface-names', 'outlet'], ['old-props', 'per-surface?', False, 'average-over', 1, 'surface-ids', [1], 'location-type', [2], 'surface-names', ['outlet'], 'phase', '"mixture"', 'header', '""', 'retain-instantaneous-values?', False, 'name', '"mass_flowrate_out"', 'type', '"surface-massflowrate"'], ('per-surface?', False), ('average-over', 1), ('phase', '"mixture"'), ('report-type', '""'), ('retain-instantaneous-values?', False), ['physics'], ['geometry'], ['surfaces']]]]`

4. Edit the name tuple to have a new name (e.g. "mass_flowrate_out_1") and set the rp var like:

`solver.rp_vars("monitor/report-definitions", [[('name', '"mass_flowrate_out_1"'), ['report-definition', 'surface-massflowrate', ['surface-ids', 1], ['surface-names', 'outlet'], ['old-props', 'per-surface?', False, 'average-over', 1, 'surface-ids', [1], 'location-type', [2], 'surface-names', ['outlet'], 'phase', '"mixture"', 'header', '""', 'retain-instantaneous-values?', False, 'name', '"mass_flowrate_out"', 'type', '"surface-massflowrate"'], ('per-surface?', False), ('average-over', 1), ('phase', '"mixture"'), ('report-type', '""'), ('retain-instantaneous-values?', False), ['physics'], ['geometry'], ['surfaces']]]])`

5. Call `solver.rp_vars("monitor/report-definitions")` - this should show the changed name in the console output
6. Open the GUI window and check the corresponding report definition - the name is unchanged
7. Write the case and data (e.g. `solver.file.write_case_data(file_name="noz_ss_1.cas.h5")`)
8. Reload the new case and data as in step 2, and call `solver.rp_vars("monitor/report-definitions")` - the output will not have changed from the original output as expected, and the GUI will continue to be unaffected

[nozzle_tui_a1.zip](https://github.com/ansys/pyfluent/files/13363294/nozzle_tui_a1.zip)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024 R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
absl-py==2.0.0
ansi2html==1.8.0
ansys-api-fluent==0.3.18
ansys-api-platform-instancemanagement==1.0.0
-e git+https://github.com/ansys/pyfluent@d15cc3789488a8aa9520aa1fe55d2126d12398d4#egg=ansys_fluent_core
-e git+https://github.com/ansys/pyfluent-parametric@bb35cdddfad6b26c0e7dc04d92eaac4842e0f006#egg=ansys_fluent_parametric
-e git+https://github.com/ansys/pyfluent-visualization@b907538e399406d96da587a38d8518697746593d#egg=ansys_fluent_visualization
ansys-platform-instancemanagement==1.1.2
asttokens==2.4.1
astunparse==1.6.3
bcrypt==4.0.1
blinker==1.7.0
cachetools==5.3.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
dash==2.14.1
dash-bootstrap-components==1.5.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
docker==6.1.3
et-xmlfile==1.1.0
exceptiongroup==1.1.3
executing==2.0.1
Flask==3.0.0
flatbuffers==23.5.26
fonttools==4.44.0
gast==0.5.4
google-auth==2.23.4
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.59.2
grpcio-health-checking==1.48.2
h5py==3.10.0
idna==3.4
imageio==2.32.0
importlib-metadata==6.8.0
ipython==8.17.2
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
kaleido==0.2.1
keras==2.14.0
kiwisolver==1.4.5
libclang==16.0.6
lxml==4.9.3
Markdown==3.5.1
MarkupSafe==2.1.3
matplotlib==3.8.1
matplotlib-inline==0.1.6
ml-dtypes==0.2.0
nest-asyncio==1.5.8
numpy==1.26.2
oauthlib==3.2.2
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.2
pandas==2.1.3
paramiko==3.3.1
paramiko-expect==0.3.5
parso==0.8.3
Pillow==10.0.1
platformdirs==4.0.0
plotly==5.18.0
pooch==1.8.0
prompt-toolkit==3.0.40
protobuf==3.20.3
psutil==5.9.6
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.16.1
PyNaCl==1.5.0
pyparsing==3.1.1
PySide6==6.6.0
PySide6-Addons==6.6.0
PySide6-Essentials==6.6.0
python-dateutil==2.8.2
python-pptx==0.6.23
pytz==2023.3.post1
pyvista==0.42.3
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
QtPy==2.4.1
requests==2.31.0
requests-oauthlib==1.3.1
retrying==1.3.4
rsa==4.9
scikit-learn==1.3.2
scipy==1.11.3
scooby==0.9.2
seaborn==0.13.0
shiboken6==6.6.0
six==1.16.0
stack-data==0.6.3
tenacity==8.2.3
tensorboard==2.14.1
tensorboard-data-server==0.7.2
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-intel==2.14.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.3.0
threadpoolctl==3.2.0
traitlets==5.13.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
vtk==9.3.20230807rc0
wcwidth==0.2.9
websocket-client==1.6.4
Werkzeug==3.0.1
wrapt==1.14.1
xgboost==2.0.2
XlsxWriter==3.1.9
zipp==3.17.0
```

**Comment by answillgm** [comment]
Another issue has been noted with setting bool values, as when setting a boolean rp var (such as "rp-lam?"), pyfluent is able to set it to true, but cannot set it to false again. This is not an issue when using the tui console.

Recreate (with same case as previously):

1. Call solver.rp_vars("rp-lam?") - it gives a value of False
2. Call solver.rp_vars("rp-lam?", True), then check the value again - it gives a value of True
3. Call solver.rp_vars("rp-lam?", False), then check the value again - it gives a value of True

**Comment by seanpearsonuk** [comment]
> Another issue has been noted with setting bool values, as when setting a boolean rp var (such as "rp-lam?"), pyfluent is able to set it to true, but cannot set it to false again. This is not an issue when using the tui console.
> 
> Recreate (with same case as previously):
> 
> 1. Call solver.rp_vars("rp-lam?") - it gives a value of False
> 2. Call solver.rp_vars("rp-lam?", True), then check the value again - it gives a value of True
> 3. Call solver.rp_vars("rp-lam?", False), then check the value again - it gives a value of True

There is a PR with a fix for this issue.

**Comment by seanpearsonuk** [comment]
@answillgm It is valid to compare the Python behaviour against direct rpvar behaviour via Scheme calls. Please indicate if such differences are still observed after the changes. Thanks for reporting the rp-lam? issue.
