### ISSUE TITLE
Select zone names for drag report-definition

### ISSUE THREAD

**Issue by sabbraxcaddabra** [ansys/pyfluent#2276]
I try to add drag coefficient report for my external flow problem
Now I have now idea how to do this by pyfluent. Can anyone help me with this feature? I'm using Fluent 2023R1

**Comment by prmukherj** [comment]
1. Initialize and create the report definition:
>>> solver.solution.report_definitions.drag["drag_coeff_1"] = {}
>>> d1 = solver.solution.report_definitions.drag["drag_coeff_1"]

2. Either set its state via a dictionary of state:
         i. >>> d1.get_state()
         {'scaled': True, 'average_over': 1, 'per_zone': False, 'thread_names': None, 'force_vector': [1, 0, 0]}
         ii. >>> d1.set_state({'scaled': True, 'average_over': 1, 'per_zone': False, 'thread_names': ["wall"], 'force_vector': [0, 1, 0]})

3. Or, set the states individually:
         i. >>> d1.thread_names.allowed_values()
         ['wall']
         ii. >>> d1.thread_names = ["wall"]

Using dir(d1) will help with the other methods available with this report as well.
For further help refer the documentation: https://fluent.docs.pyansys.com/version/stable/

**Comment by prmukherj** [comment]
Please note: Some of the settings object names have changed for later versions of fluent.
@sabbraxcaddabra, we shall close this issue if the reply is of help.
