### ISSUE TITLE
Docker Launch Error

### ISSUE THREAD

**Issue by ansaboutin** [ansys/pyfluent#2281]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While starting docker a `Internal Server Error ("error while creating mount source path` is raised.

### 📝 Steps to reproduce

Run this: `docker run -it -e "ANSYSLMD_LICENSE_FILE=1055@leblnxlic64.ansys.com:1055@lebfluintwin103.win.ansys.com" -v ~/.local:/testing ghcr.io/ansys/pyfluent:v23.2.0 3ddp -gu`

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

v23.2.0

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.19
ansys-api-platform-instancemanagement==1.0.0
-e git+https://github.com/ansys/pyfluent.git@53867e8552f21593c9975bcfacd0755b772c89c3#egg=ansys_fluent_core
ansys-platform-instancemanagement==1.1.2
beartype==0.16.4
certifi==2023.11.17
charset-normalizer==3.3.2
docker==6.1.3
grpcio==1.59.3
grpcio-health-checking==1.48.2
idna==3.4
importlib-metadata==6.8.0
lxml==4.9.3
numpy==1.26.2
packaging==23.2
pandas==2.1.3
platformdirs==4.0.0
protobuf==3.20.3
psutil==5.9.6
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
tzdata==2023.3
urllib3==2.1.0
websocket-client==1.6.4
zipp==3.17.0
```

**Comment by raph-luc** [comment]
The supported way to launch Fluent containers from PyFluent is documented here: https://fluent.docs.pyansys.com/version/stable/api/general/launcher/fluent_container.html

What is the intention here? Is it to use the PyFluent inside the container itself, and not the one the user has installed and available locally? Or in other words, to launch the container manually and use the PyFluent within the container?
