### ISSUE TITLE
Creating non-conformal interfaces using settings API (auto_pairing)

### ISSUE THREAD

**Issue by mkvani** [ansys/pyfluent#2301]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am trying to create non-conformal interfaces using "auto_pairing" function. But it is not creating any NCI.
 
I want to create NCI for all walls. I am using this function as below:
 
solver.setup.mesh_interfaces.auto_pairing(all = True, si_create= True)
 
The output message says "Interfaces created successfully". However Fluent setup doesn't has any interface.
 
Is there something I am missing?

### 📝 Steps to reproduce

Use following function to create NCI:

solver.setup.mesh_interfaces.auto_pairing(all = True, si_create= True)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.19
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.18.2
ansys-platform-instancemanagement==1.1.2    
certifi==2023.11.17
charset-normalizer==3.3.2
docker==6.1.3
grpcio==1.60.0
grpcio-health-checking==1.48.2
idna==3.6
importlib-metadata==7.0.0
lxml==4.9.3
numpy==1.26.2
packaging==23.2
pandas==2.1.3
platformdirs==4.1.0
protobuf==3.20.3
psutil==5.9.6
python-dateutil==2.8.2
pytz==2023.3.post1
pywin32==306
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
tzdata==2023.3
urllib3==2.1.0
websocket-client==1.7.0
zipp==3.17.0
```

**Comment by mkvani** [comment]
Hi,

Any update on this? This is for an ongoing FDS approved solution project. 

Thank you,
Manoj

**Comment by dnwillia** [comment]
Manoj, is that same command working properly in Fluent's PyConsole?

**Comment by mkvani** [comment]
Hi @dnwillia ,

This doesn't seem to work in PyConsole. Please see snapshot below. 

![image](https://github.com/ansys/pyfluent/assets/102018222/f629f4d9-e7cd-4279-85eb-a4d7bb44fd5e)

**Comment by dnwillia** [comment]
OK thanks for checking, it means this is a problem in Fluent itself.  You could file an internal defect for this too.

**Comment by mkvani** [comment]
Thank you @dnwillia for your comments.
I will do the needful.

 I wanted to ask one more thing. The function arguments are not intuitive for me. Following are snapshots of function argument document and Fluent UI for the same operation. Mainly following arguments are not clear:

all, new_si_id and si_create.


![image](https://github.com/ansys/pyfluent/assets/102018222/776611f5-2194-402a-aadd-fc7af9443b88)
  ![image](https://github.com/ansys/pyfluent/assets/102018222/034c0646-e360-4403-97db-fcbcfafdd779)

**Comment by mkvani** [comment]
Filed defect for Fluent (https://tfs.ansys.com:8443/tfs/ANSYS_Development/Portfolio/_workitems/edit/959285)

**Comment by dnwillia** [comment]
Yeah, I agree that some of the names are not intuitive.  For instance I think `si_name` should have been called `interface_name_prefix` as that seems to be right thing.  The parameters documented with the 'child' terminology is just auto generated so these would be undocumented in Fluent itself too (eg: in the PyConsole).

**Comment by mkundu1** [comment]
I see in the latest settigns API (24.2), these parameters have been renamed to more intuitive names. Closing as there is no outstanding issue for PyFluent.
