### ISSUE TITLE
"For developers" section of readme 

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2302]
Still frequently getting enquiries from internal user using unreleased Fluent versions and therefore requiring the codegen step. The message in the exception is accurate and informative, but it still seems that people can't quite make the mental leap necessary. Shall we be more explicit in the "For developers" section? Shall we re-title that section so that all internal users are drawn to those steps? Shall we add more detailed information to the exception message?

**Comment by mkundu1** [comment]
We now have a developer section in both[ installation guide](https://fluent.docs.pyansys.com/version/stable/getting_started/installation.html#ref-installation) and github README.

@seanpearsonuk Closing this, feel free to revert if something is remaining.
