### ISSUE TITLE
`solvermode` tests are currently set to run in v242, should they be changed to v241?

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2304]
See https://github.com/ansys/pyfluent/pull/2296#issuecomment-1849631901

Tests are failing due to v242 dev changes https://github.com/ansys/pyfluent/actions/workflows/weekly-solvermode-test-run.yml

**Comment by mkundu1** [comment]
The `solvermode` tests track settings API change in the latest development. The testing team maintains the test scripts.

@cj-hodgson @millerj97 Can you please check the current failures?

**Comment by cj-hodgson** [comment]
@millerj97 Please could you take care of this

**Comment by millerj97** [comment]
issue #2393 posted for test_species_model.py failure @cj-hodgson @mkundu1
