### ISSUE TITLE
Sun Grid Engine Support

### ISSUE THREAD

**Issue by eusta777** [ansys/pyfluent#2321]
### 📝 Description of the feature

As I read documentation "The supported scheduler environments are Univa Grid Engine (UGE), Load Sharing Facility (LSF), Portable Batch System (PBS), and Slurm.". Sun Grid Engine is not included if there is a way to use it please can you share. Or is it possible to add Sun Grid Engine?

**Comment by mkundu1** [comment]
Both Univa and Sun Grid Engine are supported in Fluent in the same way (https://ansyshelp.ansys.com/account/secured?returnurl=/Views/Secured/corp/v241/en/flu_lm/flu_sge_parallel_sge.html). So, the UGE documentation in PyFluent is applicable for SGE also.
