### ISSUE TITLE
No way to overwrite saved picture in settings API

### ISSUE THREAD

**Issue by ansjsia** [ansys/pyfluent#2322]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When saving a picture in Fluent, if a file with the same name already exists, there is no way to command Fluent to overwrite the file in the settings API. The TUI or the GUI will prompt for confirmation.

This means that if Fluent is launched with `show_gui=False`, there is no way to continue. This could cause examples that are run repeatedly to hang.

An option should be added to `root.results.graphics.picture` to enable overwrite without prompting for confirmation.

### 📝 Steps to reproduce

1. Launch Fluent with `show_gui=False` and load a case file of your choice.
2. In the settings API, call `root.results.graphics.picture.save_picture(file_name='example.png')`
3. Repeat step 2.
4. Fluent will not be able to proceed.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
accessible-pygments==0.0.4
alabaster==0.7.13
ansys-api-fluent==0.3.20
ansys-api-platform-instancemanagement==1.0.0
-e git+https://github.com/ansys/pyfluent.git@a54b918ea4a7febbb384102a393192c3fb881284#egg=ansys_fluent_core
ansys-fluent-parametric==0.6.0
-e git+https://github.com/ansys/pyfluent-visualization.git@b907538e399406d96da587a38d8518697746593d#egg=ansys_fluent_visualization
ansys-platform-instancemanagement==1.1.2
ansys-sphinx-theme==0.12.1
appdirs==1.4.4
asttokens==2.4.1
attrs==23.1.0
autodocsumm==0.2.11
Babel==2.14.0
beartype==0.16.4
beautifulsoup4==4.12.2
bleach==6.1.0
build==1.0.3
certifi==2023.11.17
cfgv==3.4.0
charset-normalizer==3.3.2
colorama==0.4.6
comm==0.2.0
contourpy==1.2.0
coverage==7.3.3
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.8
docker==7.0.0
docutils==0.20.1
et-xmlfile==1.1.0
exceptiongroup==1.2.0
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
fonttools==4.47.0
grpcio==1.60.0
grpcio-health-checking==1.48.2
h5py==3.10.0
identify==2.5.33
idna==3.6
imagesize==1.4.1
importlib-metadata==7.0.0
iniconfig==2.0.0
ipykernel==6.27.1
ipython==8.18.1
ipywidgets==8.1.1
jedi==0.19.1
Jinja2==3.1.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
jupyter-sphinx==0.4.0
jupyter_client==8.6.0
jupyter_core==5.5.1
jupyterlab-widgets==3.0.9
jupyterlab_pygments==0.3.0
kiwisolver==1.4.5
livereload==2.6.3
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==3.0.2
nbclient==0.9.0
nbconvert==7.13.0
nbformat==5.9.2
nest-asyncio==1.5.8
nodeenv==1.8.0
numpy==1.26.0
numpydoc==1.5.0
openpyxl==3.1.2
packaging==23.2
pandas==2.1.1
pandocfilters==1.5.0
parso==0.8.3
Pillow==9.5.0
platformdirs==4.1.0
plotly==5.17.0
pluggy==1.3.0
pooch==1.8.0
pre-commit==3.6.0
prompt-toolkit==3.0.43
protobuf==3.20.3
psutil==5.9.7
pure-eval==0.2.2
pydata-sphinx-theme==0.14.4
Pygments==2.17.2
pypandoc==1.10
pyparsing==3.1.1
pyproject_hooks==1.0.0
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
pytest==7.4.3
pytest-cov==4.1.0
pytest-mock==3.12.0
pytest-sphinx==0.5.0
python-dateutil==2.8.2
python-pptx==0.6.22
pytz==2023.3.post1
pyvista==0.43.1
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.2
QtPy==2.4.1
referencing==0.32.0
requests==2.31.0
rpds-py==0.15.2
scooby==0.9.2
seaborn==0.13.0
shiboken6==6.6.1
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.5
sphinx-autobuild==2021.3.14
sphinx-copybutton==0.5.1
sphinx-gallery==0.14.0
sphinx-notfound-page==1.0.0
sphinx_autodoc_typehints==1.21.8
sphinx_design==0.5.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sphinxcontrib-websupport==1.2.4
sphinxemoji==0.2.0
stack-data==0.6.3
tabulate==0.9.0
tenacity==8.2.3
tinycss2==1.2.1
tomli==2.0.1
tornado==6.4
traitlets==5.14.0
typing_extensions==4.9.0
tzdata==2023.3
urllib3==2.1.0
virtualenv==20.25.0
vtk==9.3.20230807rc0
wcwidth==0.2.12
webencodings==0.5.1
widgetsnbextension==4.0.9
XlsxWriter==3.1.9
zipp==3.17.0
```

**Comment by raph-luc** [comment]
This is a good point, and FYI there are other situations like this where existing files can cause issues for subsequent execution, and this is one of the reasons why we often clean up the working folders when executing the tests and examples using `sudo rm -rf /home/ansys/.local/share/ansys_fluent_core/examples`

**Comment by ansjsia** [comment]
> This is a good point, and FYI there are other situations like this where existing files can cause issues for subsequent execution, and this is one of the reasons why we often clean up the working folders when executing the tests and examples using `sudo rm -rf /home/ansys/.local/share/ansys_fluent_core/examples`

Is this something we should be instructing users to do when running examples?

**Comment by raph-luc** [comment]
I would say no, we should not do that: we'd rather have users report specific situations where they have issues like this so that we can fix them. 

In fact, we probably should be going in the other direction: improving things so that we do not need to clean up the working folders before execution, and making sure things behave in a more intuitive and clear way when existing files may cause conflicts.

**Comment by mkundu1** [comment]
F;uent bug id - 1035235

**Comment by mkundu1** [comment]
Fixed in latest Fluent
