### ISSUE TITLE
Hide recommandation of solver setting object when using a tui command.

### ISSUE THREAD

**Issue by etiennelame** [ansys/pyfluent#2323]
If executing a python code of tui command, such as: **solver.tui.define.models.viscous.kw_geko('yes')**

the console will show a recomendation of command basing on solver settings object method:
The following solver settings object method could also be used to execute the above command:
**<solver_session>.setup.models.viscous.model = "k-omega"
solver.setup.models.viscous.k_omega_model = "geko"**

How to hide these messages when i excute the python code and run fluent?

**Comment by raph-luc** [comment]
Hi @etiennelame, thanks for the question.

The plan is to deprecate the TUI commands, in which case this `solver.tui.define.models.viscous.kw_geko('yes')` command you are using will stop working. We expect users to stop using the old TUI commands and move to the new "Settings API" commands which generally have a better interface and usability. There should usually be no reason to use TUI commands over the Settings API ones.

In this case, to make the warning go away, the solution is to just use the alternative Settings API commands, as recommended by the automated helper.

Are you noticing any issues using the new version of the commands?

**Comment by etiennelame** [comment]
> Hi @etiennelame, thanks for the question.
> 
> The plan is to deprecate the TUI commands, in which case this `solver.tui.define.models.viscous.kw_geko('yes')` command you are using will stop working. We expect users to stop using the old TUI commands and move to the new "Settings API" commands which generally have a better interface and usability. There should usually be no reason to use TUI commands over the Settings API ones.
> 
> In this case, to make the warning go away, the solution is to just use the alternative Settings API commands, as recommended by the automated helper.
> 
> Are you noticing any issues using the new version of the commands?

Tui command can be adapted to different version, some API command of v22 changed in v23. That's why tui is prefered.

**Comment by mkundu1** [comment]
@etiennelame These messages can be hidden by setting the env var `PYFLUENT_SKIP_API_UPGRADE_ADVICE=1`
