### ISSUE TITLE
pyfluent.datamodel WARNING: Currently calling the datamodel API in a generic manner. Please run `python codegen/allapigen.py` from the top-level pyfluent directory to generate the local datamodel API classes.

### ISSUE THREAD

**Issue by zzz-luo** [ansys/pyfluent#2331]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I'm learning the official lesson of 'Getting Started with Ansys PyFluent'. There is a exercise in Lesson 3 for starting a Jupyter session of recorded PyFluent Journal. I opened the .ipynb file offered by official and runned the codes of first section, then I receieved the warning that "**pyfluent.datamodel WARNING: Currently calling the datamodel API in a generic manner. Please run `python codegen/allapigen.py` from the top-level pyfluent directory to generate the local datamodel API classes.**". Can anyone teach me how to solve this issue? Thank you so much. 
![image](https://github.com/ansys/pyfluent/assets/155145522/02e0e740-5f39-4fbf-816a-de64675d21d4)

### 📝 Steps to reproduce

Just type these codes of the picture above, and the issue will appears.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024 R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.20
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.18.2
ansys-fluent-parametric==0.9.0
ansys-fluent-visualization==0.8.0
ansys-platform-instancemanagement==1.1.1
anyio==3.7.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==23.1.0
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.2.0
colorama==0.4.6
comm==0.1.3
contourpy==1.1.0
cycler==0.11.0
debug==0.3.2
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
docker==7.0.0
exceptiongroup==1.1.2
executing==1.2.0
fastjsonschema==2.17.1
flake8==6.0.0
fonttools==4.40.0
fqdn==1.5.1
googleapis-common-protos==1.59.1
grpcio==1.56.0
grpcio-health-checking==1.48.2
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
ipdb==0.13.13
ipykernel==6.24.0
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.7
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jsonpointer==2.4
jsonschema==4.18.0
jsonschema-specifications==2023.6.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
kiwisolver==1.4.4
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mccabe==0.7.0
mistune==3.0.1
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.6.0
nbformat==5.9.1
nest-asyncio==1.5.6
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.25.1
overrides==7.3.1
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.8.1
pooch==1.7.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.5
pure-eval==0.2.2
pycodestyle==2.10.0
pycparser==2.21
pyflakes==3.0.1
Pygments==2.15.1
pyparsing==3.0.9
PySide6==6.5.1.1
PySide6-Addons==6.5.1.1
PySide6-Essentials==6.5.1.1
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
pyvista==0.40.1
pyvistaqt==0.11.0
pywin32==306
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
referencing==0.29.1
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.8.10
scooby==0.7.2
see==1.4.1
Send2Trash==1.8.2
shiboken6==6.5.1.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.2
traitlets==5.9.0
tzdata==2023.3
uri-template==1.3.0
urllib3==2.0.3
vtk==9.3.20230807rc0
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
widgetsnbextension==4.0.8
yapf==0.40.1
zipp==3.16.0
```

**Comment by VincenzoRO** [comment]
Hi zzz-luo,

I am trying to replicate the same examples from the ansys pyfluent documentation. I have suffered the same thing when I tried to run the first example, even going through the tutorial videos it was impossible for me to run the script.  I am running the examples in almost the same conditions as you, Windows 11, Python version 11 and the same version of Ansys for students.

The solution I found was to **install Git** and **clone the repository** included in the instructions(for developers). Inside the repository in the folder named **"codegen "** is the file that announces the warning **"allapigen.py "**(this was my clue). So I clone the repository, copy my jupyter notebook script and paste it into the same path as the cloned repository. Then from the command line I run the jupyter notebook file and it finally runs.

I am not sure about the problem, I guess it is related to a path issue and working with the repository locally it is possible to run the script without problems.

I hope my answer is helpful.

**Comment by raph-luc** [comment]
@zzz-luo @VincenzoRO Sorry for the delayed answer, but the PyFluent package on PyPI does not yet include the API files for Ansys Fluent 2024 R1. 

For now, if you want to use PyFluent with Ansys 2024 R1 with all the API functionalities, you need to use the _development_ PyFluent install as described here: https://fluent.docs.pyansys.com/version/stable/getting_started/installation.html#install-the-package

The next PyFluent release (work in progress) is going to contain the 2024 R1 API files, so that doing this won't be necessary anymore.

**Comment by schrummy14** [comment]
Thank you for the information @raph-luc.

By chance, do you know if the PyPI version will be updated before the end of the month?

Thank you.

**Comment by prmukherj** [comment]
There is an updated release in the PyPi now -> v0.19.1

@schrummy14, please confirm if this issue is resolved now. Thank you.

**Comment by prmukherj** [comment]
We now have a PyPi release of 0.19.1 which should solve this issue. @schrummy14, could you please confirm: https://pypi.org/project/ansys-fluent-core/0.19.1/

**Comment by schrummy14** [comment]
Hello,
Yes, I can confirm that the error is now gone.
Thank you.
