### ISSUE TITLE
How to get the value of the output parameter

### ISSUE THREAD

**Issue by lazyaa** [ansys/pyfluent#2350]
I want to use pyfluent to get the value of pyfluent in cas, but the existing tui instruction allows me to get only the.out file of the output parameter, and I cannot get only the values of the output parameter from the out file

**Comment by mkundu1** [comment]
Please check this [unittest](https://github.com/ansys/pyfluent/blob/main/tests/parametric/test_parametric_workflow.py#L215) how output parameter values are extracted from a running session.
