### ISSUE TITLE
dir(solver_session) is slow for the first time after connecting to Fluent

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2356]
This is due to the one-time call to the settings API static-info, the issue is more prominent in the pyconsole autocompleter

**Comment by prmukherj** [comment]
@mkundu1, you are already working on this in the server side, right?

**Comment by mkundu1** [comment]
This has been resolved in Fluent/PyConsole, I'll remove the `console integration` tag.

For PyFluent, we start populating the dir in a background thread immediately after connection, will look into that later.

**Comment by mkundu1** [comment]
Currently, first access to settings API is slow:
```
import time
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent()
start_time = time.time()
solver.settings
print("Elapsed time: ", time.time() - start_time)
start_time = time.time()
solver.settings
print("Elapsed time: ", time.time() - start_time)
```
Above code prints
```
Elapsed time:  4.425086736679077
Elapsed time:  0.0
```

**Comment by mkundu1** [comment]
Most of the time is taken to retrieve the static-info (for hash comparison) - ~ 4 s.
