### ISSUE TITLE
Is it possible to launch multiple instances of pyFluent?

### ISSUE THREAD

**Issue by a-hagh** [ansys/pyfluent#2359]
### 📝 Description of the feature

When launching instances of Fluent using the pyfluent lib, we are limited to launching one instance at a time. I am proposing the feature/example that allows users to launch multiple instances of in parallel, with each instance having the capability to utilize a specified number of processor cores.

This will be useful for integration with OptiSLang and SimAI!

### 💡 Steps for implementing the feature

For example, with multiprocessor lib it should look like: 

import multiprocessing

def solve_fluent_instance(instance_id):
    solver = pyfluent.launch_fluent(processor_count=2)

total_instances = 3 
pool = multiprocessing.Pool(processes=total_instances)
pool.map(solve_fluent_instance, range(1, total_instances + 1))

**Comment by seanpearsonuk** [comment]
`launch_fluent` can be called multiple times via asynchronous calls.
