### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by Mohammadforuzannia** [ansys/pyfluent#2374]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Dear Ansys Support Team,

I hope this email finds you well. I am writing to inquire about using the Multi-GPU Solver with Pyfluent for my simulation needs.

I have been utilizing Pyfluent to simulate various problems, and while it has been effective, I have encountered challenges with the required computation time when running simulations solely on the CPU. Considering the advancements in GPU technology and its potential to accelerate computations, I am interested in exploring the benefits of using the Multi-GPU Solver with Pyfluent.

I would greatly appreciate it if you could provide me with information regarding the availability and compatibility of the Multi-GPU Solver in Pyfluent. Additionally, any guidance on how to set up and utilize the Multi-GPU Solver would be immensely helpful.

Thank you in advance for your assistance. I look forward to your response and any recommendations you may have.

Sincerely,

Mohammad Foruzan Nia

### 📝 Steps to reproduce

.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
.
```

**Comment by mkundu1** [comment]
There is a limitation presently in `launch_fluent` as the `gpu` parameter takes a boolean. Please use the `additional_arguments` parameter to pass the `-gpu` command-line option to the Fluent launcher:
```
launch_fluent(..., additional_arguments="-gpu=1,2,4")
```
Please refer [Fluent User's Guide](https://ansyshelp.ansys.com/account/secured?returnurl=/Views/Secured/corp/v241/en/flu_ug/flu_ug_sec_gpu_solver_starting.html) for details about `-gpu` command-line option.
