### ISSUE TITLE
Pings heard in the background while importing Discovery geometry

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2378]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When using Fluent session launched via pyfluent in meshing mode and Importing Disco geometry, one can hear 5 loud pings in the background. This is not observed when using standalone Fluent. On debugging, it is found that this sound is heard during the 'Attaching Geometry' step.

### 📝 Steps to reproduce

import ansys.fluent.core as pyfluent
session = pyfluent.launch_fluent(mode="meshing")
session.workflow.LoadWorkflow(FilePath=workflow_template)
session.workflow.TaskObject['Import Geometry'].Arguments  = dict(FileName=geometry_filepath)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by mkundu1** [comment]
@tejalprabhu01 Is there a complete script to reproduce the issue? I tried with the following script, but the issue is not reproducible:
```
import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples
geom_file = examples.download_file('toy_car.dsco', 'pyprimemesh/toy_car')
meshing = pyfluent.launch_fluent(mode="meshing")
meshing.workflow.InitializeWorkflow(WorkflowType='Watertight Geometry')
meshing.workflow.TaskObject['Import Geometry'].Arguments = {'FileName': geom_file}
meshing.workflow.TaskObject['Import Geometry'].Execute()
```

**Comment by tejalprabhu01** [comment]
@mkundu1 Following are the steps to reproduce:
import ansys.fluent.core as pyfluent
session = pyfluent.launch_fluent(show_gui=True, mode="meshing", start_watchdog=False)
session.workflow.LoadWorkflow(FilePath=r"D:\Release24R2\Fluent4\D2.wft")
session.workflow.TaskObject['Import Geometry'].Arguments=dict(FileName=r"D:\Release24R2\Fluent4\D2.dsco")
session.scheme_eval.string_eval("(wb-wf-update-all-workflow-tasks)")

I am also attaching the workflow template and the geometry for your reference
[Fluent4.zip](https://github.com/ansys/pyfluent/files/14238751/Fluent4.zip)

**Comment by mkundu1** [comment]
Can be reproducible in standalone Fluent meshing, shared recording.
