### ISSUE TITLE
Case gets modified for queries like reduction

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2404]
This issue might be there for other query-like services/methods, in both PyFluent + PyConsole.

**Comment by seanpearsonuk** [comment]
Fixed for reduction. @mkundu1 would like to check for field/svar data

**Comment by mkundu1** [comment]
Added tests for reduction/field_data/svar. Case is getting modified for field data queries.

**Comment by seanpearsonuk** [comment]
Fix will be on the Fluent side

**Comment by seanpearsonuk** [comment]
@mkundu1 @prmukherj Closing as this was fixed in Fluent
