### ISSUE TITLE
Two public ways to get session's Fluent version

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2406]
![image](https://github.com/ansys/pyfluent/assets/93727996/c931987d-6021-4b23-8403-b89d49e31e19)

Is it just a matter of renaming `version` to `_version` or can we remove it altogether?

**Comment by prmukherj** [comment]
We can remove the usage of version altogether and can instead access get_fluent_version() always. There are couple of reasons why I think this: 1. version is not available in meshing sessions, so it is confusing for users, 2. version in session_solver falls back to use get_fluent_version only internally.

**Comment by hpohekar** [comment]
@seanpearsonuk 

`solver.version` is specifically used for codegen. We will rename it to `_version`. Otherwise we will have to pre-process Fluent version something like `if float(solver_session.get_fluent_version()[:-2]) < 23.0:` for codgen.
