### ISSUE TITLE
Warnings on reading parametric project with CaseReader

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2419]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

Following warning is seen while reading parametric project with CaseReader
D:\temp_installations\optiSLang\lib\python3.10\lib\site-packages\ansys\fluent\core\filereader\case_file.py:639: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  (find_folder() or find_folder(retry=True))

Also this warning is written to StandardError stream
@seanpearsonuk  @mainakk 

### 📝 Steps to reproduce

from ansys.fluent.core.filereader.case_file import CaseFile
reader = CaseFile(project_file_name = input_filepath)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys.fluent.core
```

**Comment by seanpearsonuk** [comment]
Thanks for reporting this, @tejalprabhu01. @prmukherj: pls give this higher priority than the workflow designs, thank you.
