### ISSUE TITLE
Difference in behavior of parametric study objects 

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#2430]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The available commands on parametric study object obtained with session.current_parametric study and from studies.parametric_studies are different. the common commands like get_state() also written different output. Is this expected? 

Also unable to query designs points for the current_parametric_study object

see the code snippets below for more information:
<img width="847" alt="image" src="https://github.com/ansys/pyfluent/assets/97435870/6bd84dea-141b-49f2-86c9-6b78d42129d0">
<img width="859" alt="image" src="https://github.com/ansys/pyfluent/assets/97435870/364a34a0-e52c-4f99-80fb-9e3bc594ec58">

@seanpearsonuk @mainakk 

### 📝 Steps to reproduce

The steps mentioned in screenshot above

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by mkundu1** [comment]
@tejalprabhu01 `session.current_parametric study` is of type string and returns the name of theparametric study currently active 
 in Fluent. `session.parametric_studies` is of type container and holds all parametric studies object.

**Comment by tejalprabhu01** [comment]
> @tejalprabhu01 `session.current_parametric study` is of type string and returns the name of theparametric study currently active in Fluent. `session.parametric_studies` is of type container and holds all parametric studies object.

@mkundu1 no it is not a string 
<img width="420" alt="image" src="https://github.com/ansys/pyfluent/assets/97435870/4f5d20f9-972d-414d-992f-fbb96fffc467">

**Comment by mkundu1** [comment]
@tejalprabhu01 That shows the derived class name in PyFluent. It is derived from setting string class.
```
>>> import ansys.fluent.core as pyfluent
>>> solver = pyfluent.launch_fluent()
>>> solver.current_parametric_study 
<ansys.fluent.core.solver.settings_242.current_parametric_study.current_parametric_study object at 0x000001F74C2C82E0>
>>> solver.current_parametric_study.__class__.__bases__
(<class 'ansys.fluent.core.solver.flobject.String'>,)
>>> solver.parametric_studies      
<ansys.fluent.core.solver.settings_242.parametric_studies.parametric_studies object at 0x000001F74C2A6BC0>
>>> solver.parametric_studies.__class__.__bases__
(<class 'ansys.fluent.core.solver.flobject.NamedObject'>, <class 'ansys.fluent.core.solver.flobject._CreatableNamedObjectMixin'>)
```
(The module name is shown different for you because the codegen output is outdated with respect to the Fluent version used.)

**Comment by tejalprabhu01** [comment]
@mkundu1 But this is going to be the case almost always in dev phase. how can we find out which exact Fluent version to be used with the pyfluent version we are using? and how do we handle this eventually, I mean for the release? Fluent release version would be higher than the pyfluent version that would be shipped with optiSLang python.

**Comment by mkundu1** [comment]
@tejalprabhu01

> (The module name is shown different for you because the codegen output is outdated with respect to the Fluent version used.)

Note that, this won't make any difference in the general usage. The Python classes generated in both scenarios have the same interface. With codegen, these classes are written out to external files (so it provides better documentation/intellisense support). If the codegen output is outdated, similar classes are generated in-memeory from the connected Fluent session during runtime.

We'll add the backward compatibility support in PyFluent so that scripts (optiSLang code in this case) with older version of settings API will continue to work with newer version of Fluent/settings API. (#2432).

**Comment by tejalprabhu01** [comment]
This is clear now. Thanks @mkundu1.
