### ISSUE TITLE
PyVista mesh display gives the following error

### ISSUE THREAD

**Issue by sujal-tipnis** [ansys/pyfluent#244]
To reproduce:

- Start Fluent via pyfluent
- Read any case and data.
- Create a non-default mesh display using pyvista.
- Use the script given below:
```py
import ansys.fluent.core as pyfluent
from ansys.fluent.post.pyvista import Graphics
s = pyfluent.launch_fluent(precision="double", processor_count=4)
root = s.get_settings_root()
s.tui.solver.file.read_case(case_file_name="manifold_solution.cas.h5")
s.tui.solver.file.read_data(case_file_name="manifold_solution.dat.h5")
gs_1 = Graphics(s)
mesh1 = gs_1.Meshes["mesh-1"]
mesh1.show_edges = True
mesh1.surfaces_list = ['inlet', 'inlet1', 'inlet2']
mesh1.display()
```

The pyvista module displays the mesh as required but following error is shown in the console:
![image](https://user-images.githubusercontent.com/97630067/160931808-135258a5-801f-4b40-b8d9-9350a8b6a8a9.png)

**Comment by seanpearsonuk** [comment]
Not worth fixing.
