### ISSUE TITLE
PyFluent import

### ISSUE THREAD

**Issue by ToMdAvI** [ansys/pyfluent#2461]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I’ve created a virtual environment and installed the three PyFluent packages.

Using visual studio code, I’m getting error when trying to import fluent. Any suggestions?
![image](https://github.com/ansys/pyfluent/assets/153080647/bcb53476-6c3a-48c8-8751-84b26eda1c71)

### 📝 Steps to reproduce

Above

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
Python -m pip freeze
```

**Comment by seanpearsonuk** [comment]
python -m pip install ansys-fluent-core

https://github.com/ansys/pyfluent?tab=readme-ov-file#for-developers

**Comment by ToMdAvI** [comment]
Hi,I think I’ve done that stage, I have the packages installed with the virtual environment. But I’m not sure if all the packages and downloads are in the right directory, where should they?Also I’m using ANSYS off a hard drive, with Python installed locally to the computer. Would this cause an issue. Would it work if I put Python on hard drive too?Kind Regards, TomOn 16 Feb 2024, at 20:29, Sean Pearson ***@***.***> wrote:﻿
python -m pip install ansys-fluent-core
https://github.com/ansys/pyfluent?tab=readme-ov-file#for-developers

**Comment by seanpearsonuk** [comment]
You showed `python - m pip freeze` with nothing listed. Are you activating the environment in which your packages are installed?

**Comment by ToMdAvI** [comment]
I got it installed, and everything was fine.But then we I go to load it at a later date it says PyFluent is not defined. What can I do to sort it?Kind Regards, TomOn 19 Feb 2024, at 09:01, Sean Pearson ***@***.***> wrote:﻿
You showed python - m pip freeze with nothing listed. Are you activating the environment in which your packages are installed?
