### ISSUE TITLE
Cannot set reference value

### ISSUE THREAD

**Issue by ToMdAvI** [ansys/pyfluent#2544]
### Discussed in https://github.com/ansys/pyfluent/discussions/2534

<div type='discussions-op-text'>

<sup>Originally posted by **ToMdAvI** March  5, 2024</sup>
Hello,

I would like to add a reference value to a surface (inlet) in PyFluent. However, I am struggling with the code to do this.

I currently have: 'solver.setup.reference_values.compute.from_zone_names("inlet")'
</div>

**Comment by raph-luc** [comment]
Please stick to discussions for questions like this
