### ISSUE TITLE
check readonly behaviour of prefs mwf option

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2550]
check that meshing.preferences.MeshingWorkflow.CheckpointingOption is readonly as expected

e.g., `meshing.preferences.MeshingWorkflow.CheckpointingOption = "Write into memory"`
is expected to raise an exception as in PyConsole.

**Comment by mkundu1** [comment]
@seanpearsonuk @prmukherj The check `RuntimeError: CheckpointingOption is readonly!` in old PyConsole is coming from PyStateEnigne layer. It is possible to set the state directly in the stateengine from a grpc client:
![image](https://github.com/ansys/pyfluent/assets/94432368/800f611e-90ec-4f12-9334-bed7c625b76e)

We need to add the infrastructure in PyFluent to avoid set_state on read_only field.
