### ISSUE TITLE
Interface segregation for session classes

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2558]
The objects returned from `launch_fluent()` etc should have a public interface that only contains what we want users of the library to call, and not any additional public methods intended for the implementation, such as the class-level factory method `create_from_server_info_file()`. To deal with that issue, we might make it a (standalone) function in the launcher code or just make it private in BaseSession (but still call it from launcher code).

- make `create_from_server_info_file()` private

- `settings_service` can be made private

- `events_service` can be made private

- `error_state`? It seems that it should be private - I can't find where it's actually used

- remove `svar_`* from the `dir()` results and still support usage for backwards compatibility

- make private: `set_file_transfer_service()`, `set_flproxy()`, `file_transfer_service`, `while_xxx()`, `unalias()` in each settings node

- I'm tempted to say that 'field_data', 'field_data_streaming', 'field_info', 'solution_variable_data', and 'solution_variable_info' could all be held under a single node, say `fields`. That's a lot of separate items.

Conversely:

- `solver._root` should actually be explicitly public

**Comment by seanpearsonuk** [comment]
I have added two assignees. @prmukherj is looking for tasks.

**Comment by mkundu1** [comment]
Following from a Fluent side defect - `solver.fluent_connection` can also be made private
