### ISSUE TITLE
force_exit or force_exit_container

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2559]
If the latter is called, it tells the caller to call the former. Why not just do it?

**Comment by raph-luc** [comment]
@seanpearsonuk I think the idea there was that these force exits are only for manual use by the end user, and not supposed to be used programmatically. The user should know whether Fluent is running in a container or not. If they for some reason think the specific Fluent instance they are trying to terminate is running in a container, but it isn't, and they try to call `force_exit_container()` by mistake, I think it may not be the best idea to `force_exit()` right away without warning the user first. 

Alternatively, we can completely deprecate the `force_exit_container()` and just let `force_exit()` automatically handle both situations (inside a container or standalone local).

**Comment by seanpearsonuk** [comment]
From @raph-luc:  _Alternatively, I think we can completely deprecate the force_exit_container() method and just let force_exit() automatically handle both situations (inside a container or standalone local)._
Agreed, this is what I had in mind. Overall, I am trying to slim down what is visible in `dir()` results for any PyFluent object. Since there is no strong reason not to do it, we shall go with this plan.
