### ISSUE TITLE
switch_to_solver() crashing session

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2577]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When using the `switch_to_solvermode()` the following error is reported
```
The application is busy.
Please wait a moment.
Mesh is now scaled to meters.
Traceback (most recent call last):
  File "MixingTank_Workflow.py", line 35, in <module>
    session = session.switch_to_solver()
  File "/lib/python3.10/site-packages/ansys/fluent/core/session_meshing.py", line 33, in <lambda>
    self.switch_to_solver = lambda: self._switch_to_solver()
  File "/lib/python3.10/site-packages/ansys/fluent/core/session_meshing.py", line 37, in _switch_to_solver
    self.tui.switch_to_solution_mode("yes")
  File "/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_tui.py", line 350, in __call__
    return PyMenu(self._service, self._version, self._mode, self._path).execute(
  File "/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_tui.py", line 243, in execute
    return self._service.execute_command(self._path, *args, **kwargs)
  File "/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_tui.py", line 161, in execute_command
    return self._impl.execute_command(request)
  File "/lib/python3.10/site-packages/ansys/fluent/core/services/error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: ()
Error Object: #f

```

Issue affecting regression

### 📝 Steps to reproduce

run attached script
[switch_bug.zip](https://github.com/ansys/pyfluent/files/14613587/switch_bug.zip)

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
absl-py==2.1.0
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.19.2
ansys-fluent-parametric==0.9.0
ansys-fluent-visualization==0.8.0
ansys-platform-instancemanagement==1.1.2
asttokens==2.4.1
astunparse==1.6.3
bcrypt==4.1.2
beartype==0.17.2
blinker==1.7.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.0
cryptography==42.0.5
cycler==0.12.1
dash==2.16.1
dash-bootstrap-components==1.5.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
dm-tree==0.1.8
docker==7.0.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
executing==2.0.1
Flask==3.0.2
flatbuffers==24.3.7
fonttools==4.49.0
gast==0.5.4
google-pasta==0.2.0
grpcio==1.62.1
grpcio-health-checking==1.48.2
h5py==3.10.0
idna==3.6
imageio==2.34.0
importlib_metadata==7.0.2
ipython==8.22.2
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
kaleido==0.2.1
keras==3.0.5
kiwisolver==1.4.5
libclang==16.0.6
lxml==5.1.0
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
mdurl==0.1.2
ml-dtypes==0.3.2
namex==0.0.7
nest-asyncio==1.6.0
numpy==1.26.4
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==24.0
pandas==2.2.1
paramiko==3.4.0
paramiko-expect==0.3.5
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
plotly==5.20.0
pooch==1.8.1
prompt-toolkit==3.0.43
protobuf==3.20.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.17.2
PyNaCl==1.5.0
pyparsing==3.1.2
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
python-dateutil==2.9.0.post0
python-pptx==0.6.23
pytz==2024.1
pyvista==0.43.4
pyvistaqt==0.11.0
PyYAML==6.0.1
QtPy==2.4.1
requests==2.31.0
retrying==1.3.4
rich==13.7.1
scikit-learn==1.4.1.post1
scipy==1.12.0
scooby==0.9.2
seaborn==0.13.2
shiboken6==6.6.2
six==1.16.0
stack-data==0.6.3
tenacity==8.2.3
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tensorflow-io-gcs-filesystem==0.36.0
termcolor==2.4.0
threadpoolctl==3.3.0
traitlets==5.14.2
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
vtk==9.3.20230807rc0
wcwidth==0.2.13
Werkzeug==3.0.1
wrapt==1.16.0
xgboost==2.0.3
XlsxWriter==3.2.0
zipp==3.18.1
```

**Comment by prmukherj** [comment]
@millerj97  and @seanpearsonuk, I cannot reproduce this issue either in PyFluent or PyConsole -> Fluent Build Id: 135.

Please report if anyone from the dev team can reproduce this issue. cc. @mkundu1 and @hpohekar

**Comment by hpohekar** [comment]
@prmukherj 

I'm getting following errors.

![image](https://github.com/ansys/pyfluent/assets/106588300/ae2c2016-e1b0-4e66-a272-d1e3b273c256)

`------------------------------------------------`

![image](https://github.com/ansys/pyfluent/assets/106588300/971bad49-851c-42b7-bad2-9b6221737617)

Script ended with following error.

![image](https://github.com/ansys/pyfluent/assets/106588300/1c6327a4-8f6b-4c96-b284-062ddbdc2032)

**Comment by prmukherj** [comment]
> @prmukherj
> 
> I'm getting following errors.
> 
> ![image](https://private-user-images.githubusercontent.com/106588300/313170614-ae2c2016-e1b0-4e66-a272-d1e3b273c256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDI0NTUsIm5iZiI6MTcxMDUwMjE1NSwicGF0aCI6Ii8xMDY1ODgzMDAvMzEzMTcwNjE0LWFlMmMyMDE2LWUxYjAtNGU2Ni1hMjcyLWQxZTNiMjczYzI1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMTI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjMzNGQxNzYzOGNmZTQ5M2I1ZTcwYTkyYWY5ZTU0ODg0N2VhYmI4ZjA1MTg4OGI5NjJiYmM0NDMxMDk4M2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wjDPGAvGY5Ec6gUXDfbB4VJzAgJTgQRMo-4SBMsM_V8)
> 
> `------------------------------------------------`
> 
> ![image](https://private-user-images.githubusercontent.com/106588300/313171132-971bad49-851c-42b7-bad2-9b6221737617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDI0NTUsIm5iZiI6MTcxMDUwMjE1NSwicGF0aCI6Ii8xMDY1ODgzMDAvMzEzMTcxMTMyLTk3MWJhZDQ5LTg1MWMtNDJiNy1iYWQyLTliNjIyMTczNzYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMTI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzFlNWY0ODU5NjM3MzE4N2M0YjA3YWViZjUwNjUxNDE0ZDU5NzIxOGQxNDY4YWIxODlmMTYxZTYwZDc3ODJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1-UzTEQmDLxVvxH6tM8vOyMCU3BnBP27ZdWpwexnwqI)
> 
> Script ended with following error.
> 
> ![image](https://private-user-images.githubusercontent.com/106588300/313171429-1c6327a4-8f6b-4c96-b284-062ddbdc2032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDI0NTUsIm5iZiI6MTcxMDUwMjE1NSwicGF0aCI6Ii8xMDY1ODgzMDAvMzEzMTcxNDI5LTFjNjMyN2E0LThmNmItNGM5Ni1iMjg0LTA2MmRkYmRjMjAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMTI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWNhNjNjZDUxMjc1OWZjNDhmNjMxYjQ2ZmI1ZTQxYWUwZTA4MjVkYWFhZTdiYTY4NzU4M2Q1OWM3MjAxM2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m_cphnp8BEgqqEtsycB0xmce-Ngev73aI9-XqyaFlqg)

Ok, Thanks @hpohekar. These are something else, but switch_to_solver() is working for you too.

**Comment by hpohekar** [comment]
@prmukherj Yes, that's correct.  `switch_to_solver()` is working fine for me.

**Comment by millerj97** [comment]
@prmukherj @hpohekar @seanpearsonuk thank you for checking this, there was a testing infrastructure issue and the problem is now resolved. Closing issue @cj-hodgson
