### ISSUE TITLE
Some state changes in the enhanced meshing workflow do not appear in GUI

### ISSUE THREAD

**Issue by answillgm** [ansys/pyfluent#2589]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When running pyfluent with the GUI open, some changes made to children in the fault tolerant meshing workflow don't appear in the GUI - this doesn't however prevent executing the task, and appears to be superficial. For example, changing the selected object in "Identify Construction Surfaces" in the object list will not show up in the GUI, however after executing the task in pyfluent the green tick appears next to the task in the GUI, despite no surfaces appearing to be selected.

### 📝 Steps to reproduce

1. Enter the following python to setup:

```
import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples
import_file_name = examples.download_file("exhaust_system.fmd", "pyfluent/exhaust_system")
meshing = pyfluent.launch_fluent(mode="meshing", show_gui=True)
fault_tolerant = meshing.fault_tolerant()
fault_tolerant.import_cad_and_part_management.fmd_file_name.set_state(import_file_name)
fault_tolerant.import_cad_and_part_management()
```

2. In describe geometry and flow, set "Identify Construction Surfaces" to true, so that it appears in the GUI tree view - select this task so that the details are showing in the GUI
3. Call **fault_tolerant.identify_construction_surfaces.object_selection_list.get_state()** to see the selected objects - like in the GUI, no objects will be selected
4. Call **fault_tolerant.identify_construction_surfaces.object_selection_list.set_state(["flow-pipe"])** - the GUI will not update with the new selection
5. Repeat step 3 - The selected object will appear in the returned list
6. Call **fault_tolerant.identify_construction_surfaces()** - the task in the GUI will show a green tick, despite no objects being selected in the select by object list

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
2to3==1.0
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.20.dev8
ansys-hpcservices-file-management-v1==23.1.2311.26
ansys-hpcservices-file-transfer-v1==23.1.2311.26
ansys-hpcservices-global-permission-v1==23.1.2311.26
ansys-hpcservices-hardware-configuration-clusters-v1==23.1.2311.26
ansys-hpcservices-hardware-configuration-endpoints-v1==23.1.2311.26
ansys-hpcservices-hardware-configuration-queues-v1==23.1.2311.26
ansys-hpcservices-hardware-configuration-storages-v1==23.1.2311.26
ansys-hpcservices-job-management-jobs-v1==23.1.2311.26
ansys-hpcservices-job-management-logs-v1==23.1.2311.26
ansys-hpcservices-job-management-templates-v1==23.1.2311.26
ansys-hpcservices-service-management-v1==23.1.2311.26
ansys-hpcservices-user-management-v1==23.1.2311.26
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc0
ansys-units==0.3.1
attrs==23.2.0
beartype==0.17.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
distro==1.9.0
docker==6.1.3
exceptiongroup==1.2.0
execnet==2.0.2
fonttools==4.49.0
future==0.18.0
googleapis-common-protos==1.52.0
grpcio==1.48.1
grpcio-health-checking==1.48.1
grpcio-status==1.26.0
h5py==3.10.0
idna==3.6
importlib_metadata==7.0.2
iniconfig==2.0.0
kiwisolver==1.4.5
llvmlite==0.39.1
lxml==4.9.4
matplotlib==3.6.0
numba==0.56.4
numpy==1.23.5
packaging==24.0
pandas==2.0.3
pillow==10.2.0
pip-system-certs==4.0
platformdirs==3.11.0
pluggy==1.4.0
protobuf==3.19.3
psutil==5.9.2
py==1.11.0
pybind11==2.10.0
pycparser==2.21
Pymem==1.13.1
pyparsing==3.1.2
pytest==7.2.1
pytest-forked==1.6.0
pytest-xdist==1.31.0
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==304
PyYAML==6.0.1
requests==2.31.0
scipy==1.9.3
SCons==4.0.1
shapely==2.0.2
sip==6.5.1
six==1.16.0
toml==0.10.2
tomli==2.0.1
tzdata==2024.1
urllib3==1.26.10
websocket-client==1.7.0
wrapt==1.16.0
zipp==3.17.0
```

**Comment by prmukherj** [comment]
@answillgm, Could you please see if this is still reproducible? Please close this bug in that case. Thank you.

**Comment by answillgm** [comment]
@prmukherj Currently it now prints this message when carrying out stage 6:

```
Error: Failed to update task "Create External Flow Boundaries" as value(s) for below argument(s) are not provided: 

Objects

Error Object: #f
```

Which matches what the GUI shows, however the object_selection_list still shows that the selection has been set:

```
>>> fault_tolerant.identify_construction_surfaces.object_selection_list.get_state()
['flow-pipe']
```

I would expect to be able to set the object selection list with the set state command, and have it synchronized with the server

**Comment by prmukherj** [comment]
@answillgm, will look into it. Thank you.

**Comment by prmukherj** [comment]
![image](https://github.com/ansys/pyfluent/assets/109645853/dad3967e-0298-454b-abd9-916cc6a8682f)

"Identify Construction Surfaces" is not a simple task which allows setting state like this. These is option to do this via add_child_and_update.
