### ISSUE TITLE
`additional_arguments` is not supported for container launch

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2624]
Try out `solver = pyfluent.launch_fluent(additional_arguments="-t2")` in a Fluent container launch environment. Fluent container is launched with the following command
```
mkundu@AAPAomeLhXO1rdt:/mnt/d/ANSYSDev/PyFluentDev/pyfluent$ docker ps --no-trunc
CONTAINER ID                                                       IMAGE                            COMMAND                                                                                          CREATED          STATUS         PORTS                                           NAMES
46c6cfcf0a5360f736f20379b7c9a7889458b1efa94ad6896c1705d049ab83f3   ghcr.io/ansys/pyfluent:v24.2.0   "/ansys_inc/v242/fluent/bin/fluent -gu -sifile=/mnt/pyfluent/serverinfo-ncrs3ybj.txt 3ddp -gu"   10 seconds ago   Up 9 seconds   0.0.0.0:48813->48813/tcp, :::48813->48813/tcp   mystifying_turing
```

**Comment by mkundu1** [comment]
> @mkundu1 @seanpearsonuk
> 
> Following test is failing in [this PR](https://github.com/ansys/pyfluent/pull/2650) after doing following change.
> 
> https://github.com/ansys/pyfluent/pull/2650/files#diff-1ddb020aec61b14c762b419b1816d54721d6f90e625495650de70556a91f05e4
> 
> ![image](https://private-user-images.githubusercontent.com/106588300/321213243-51524b45-4e08-4756-8947-31ba4e3ef95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTMxMjgsIm5iZiI6MTcxMjc1MjgyOCwicGF0aCI6Ii8xMDY1ODgzMDAvMzIxMjEzMjQzLTUxNTI0YjQ1LTRlMDgtNDc1Ni04OTQ3LTMxYmE0ZTNlZjk1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxMjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDJlMjY1ZmZiOTBmYThlNjQ0NWI0NGUxZWFjM2FlMGE3OWIyMTk1NGY0MzMyMTU2MDViYWUzYjdlZDJmNDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TpWY1UgdbRDWY_jwfsaQD8_x5POUJVEBNohEybX9mmg)
> 
> We were getting error as - `None` type object is not iterable because `addArgs` were `None` so we have added check for non empty `addArgs` then following test started to fail.
> 
> https://github.com/ansys/pyfluent/actions/runs/8629019261/job/23654040820?pr=2650
> 
> ![image](https://private-user-images.githubusercontent.com/106588300/321227050-c7a4ae1e-a58a-4d91-b51d-7f85538d95d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTMxMjgsIm5iZiI6MTcxMjc1MjgyOCwicGF0aCI6Ii8xMDY1ODgzMDAvMzIxMjI3MDUwLWM3YTRhZTFlLWE1OGEtNGQ5MS1iNTFkLTdmODU1MzhkOTVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxMjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWE1MjJlOGYyNTQ3ZmMyZDQzZjJiMzIxNTNmN2Y4YWEyN2ZmYjFlYmU5OGI4NTE0YjExODc2YzcyOWYzMmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZVPSyEcV2b39FL98JmH7G6zGHKoeSHK_TZijDgn27H8)

The default value of the `additional_arguments` argument is `""` in `launch_fluent`. The above check is based on the assumption that `additional_arguments` will never be None.

**Comment by hpohekar** [comment]
@mkundu1 

I see. Right, got it. It should be `""` and not `None` because `None` is coming from `kwargs.get("additional_arguments")`. 

We will update it to `kwargs["additional_arguments"]`.

Thank you.
