### ISSUE TITLE
"v23.2.0" version has hard-coded.

### ISSUE THREAD

**Issue by hpohekar** [ansys/pyfluent#2640]
(line 286 ) https://github.com/ansys/pyfluent/blob/main/src/ansys/fluent/core/launcher/fluent_container.py.

This tries to search for 23.2.0 instead of 24.2.0 and gives following error.

![image](https://github.com/ansys/pyfluent/assets/106588300/eb1112fc-a73b-45d7-877f-a0bcd3dd565a)

**Comment by hpohekar** [comment]
@seanpearsonuk @mkundu1 @prmukherj 

I think `image_tag` should be latest.

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk @mkundu1 @prmukherj
> 
> I think `image_tag` should be latest.

🥇
