### ISSUE TITLE
utils/generic.py: confusing mix of functionality

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2643]
- contains unrelated functionalities
- each group of functionality should be in a separate module with a relevant name
- `loop` is a shared object instantiated at module scope, only relevant to some functions
- `utils` namespace name is not helpful. Are all these things meant to be public?

**Comment by hpohekar** [comment]
@seanpearsonuk 

Regarding `Are all these things meant to be public?` - We are not including these modules in rst. Therefore they are not available in public documentation. If we want, we can make them private explicitly.

**Comment by hpohekar** [comment]
@seanpearsonuk

Regarding `utils namespace name is not helpful.` - Do we want to rename it to something like `utilities` ?
