### ISSUE TITLE
Deprecate show_gui argument of launch_fluent

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2674]
Ideally, we should remove the `show_gui` argument and put a generic mechanism for migrating older scripts. Some idea:
```
@deprecate(old_arg=<old_arg>, new_arg=<new_arg>, converter=<function converting old_arg val to new_arg val)
def f(<new_arg>=<new_arg val>):
```
User can still pass `f(<old_arg>=<old_arg val>)` which will be executed as `f(<new_arg>=<new_arg val>)`. `<old_arg>` won't show up in documentation.

**Comment by prmukherj** [comment]
@mkundu1, I would like to work on this. I want to check how this is done. I am assigning it to myself.
