### ISSUE TITLE
Make the root solver object more easily accessible in the API documentation

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2703]
### Description of the modifications

As @lagacep-ans suggested, perhaps make the root object a subitem of the "Solver settings object" header, to make it easier to find
![image](https://github.com/ansys/pyfluent/assets/132297401/00d9c040-bf39-4c3b-8f90-3c9235c25b29)
or even as a separate item just after "Solver settings object"

**Comment by hpohekar** [comment]
@raph-luc 

We have moved root object on top level and it will appear in below page after [PR](https://github.com/ansys/pyfluent/pull/2912) get merged.

![image](https://github.com/ansys/pyfluent/assets/106588300/cca1db69-c651-415b-9974-e70bddbeadcc)

@seanpearsonuk 

Do we need to make root object as a subitem of Solver after exposing it on top level ?
