### ISSUE TITLE
Bug located in meshing_utilities

### ISSUE THREAD

**Issue by PyPablo** [ansys/pyfluent#2704]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The following works
`test = session.meshing_utilities.get_face_zones(filter="*")
print(test)
[26271, 26038, 267, 266, 265, 264, 263, 207, 206, 205, 204, 203, 201, 200, 199, 197]`

But trying to get corresponding labels returns None

`print(session.meshing_utilities.get_labels_on_face_zones(face_zone_id_list=test))
None`

Also, the command 

`test = session.meshing_utilities.get_edge_zones(filter="*")
print(test)`

Returns none, when there are all zones
![image](https://github.com/ansys/pyfluent/assets/99959795/ad77938c-b39c-4b48-b496-f402ae3c14d4)

### 📝 Steps to reproduce

Runs command above

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by hpohekar** [comment]
I have verified this in both PyFluent and PyConsole. It is working fine.

![image](https://github.com/ansys/pyfluent/assets/106588300/c4b9644e-a166-4ec5-a184-8713b12b9abc)

![image](https://github.com/ansys/pyfluent/assets/106588300/2f418d31-b188-4978-af85-77f3e9a0871f)

**Comment by hpohekar** [comment]
One of the reason could be local cache.

1. Install PyFluent with codegen files in a new virtual environment. Or

2. Uninstall existing PyFluent and reinstall it with codgen files.
