### ISSUE TITLE
Inconsistent default view orientation for save_picture

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2723]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When running in "hidden_gui" or "gui" mode, images saved from pyfluent standalone sessions are saved in "top" view. In other gui modes such as "no_gui", or in pyconsole in "hidden" mode images default saved in "isometric" view

Pyconsole is consistent with legacy console 

**pyfluent standalone in "ui_mode = hidden_gui"**

![image](https://github.com/ansys/pyfluent/assets/126583804/029bfcc1-03fd-4c73-9ba0-d9b91736b2a3)

**pyconsole in "-hidden" fluent session**

![image](https://github.com/ansys/pyfluent/assets/126583804/8a7f4be2-75f1-4c7e-a6db-601c1913781f)

There is also inconsistencies between windows and linux:

**Linux pyfl in -gu mode** 

![image](https://github.com/ansys/pyfluent/assets/126583804/e6163e21-fe7b-43eb-99e1-925533a84bf7)

**windows pyfl in -gu mode**

![image](https://github.com/ansys/pyfluent/assets/126583804/8e87aa81-5558-42d3-8dac-9eb2d36ae984)

### 📝 Steps to reproduce

- download and unzip attached case data
- launch pyfluent session from common files and run following commands:
```

import ansys.fluent.core as pyfluent

solver = pyfluent.launch_fluent(version = "3d", mode = "solver", precision="double", ui_mode="hidden_gui")
solver.file.read_case_data(file_name="ablation_Solved")

solver.results.graphics.contour.display(object_name="contour-1")


solver.results.graphics.views.camera.position(xyz=[0, 1, 0])


solver.results.graphics.picture.save_picture(file_name="contour_gu_pyfl") 

```
With pyconsole session in windows, launching fluent with the -hidden flag, run following commands:
```
solver.file.read_case_data(file_name="ablation_Solved")

solver.results.graphics.contour.display(object_name="contour-1")


solver.results.graphics.views.camera.position(xyz=[0, 1, 0])


solver.results.graphics.picture.save_picture(file_name="contour_gu_pycon") 


```
[ablation.zip](https://github.com/ansys/pyfluent/files/15042102/ablation.zip)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
commonfiles python
```

**Comment by millerj97** [comment]
@cj-hodgson issue affecting regression
@mkundu1 @seanpearsonuk

**Comment by mkundu1** [comment]
will look into this after the current pyfluent issues with ui_mode and file upload/download are resolved

**Comment by mkundu1** [comment]
I can reproduce the same issue in standalone Fluent if I launch with `-nm` flag (don't display mesh after case read). Suggest to file a Fluent side bug as this is unrelated to PyFluent.

**Comment by seanpearsonuk** [comment]
@mkundu1 Thanks for looking into this. Should we make PyFluent more configurable with respect to its use of `-nm`? As you point out, we currently hard-code `launch_string += " -nm"`, but we could allow that to be skipped if a new launch argument is set. I don't see this as a major issue in the product, rather just a case of wanting to allow things to align for the sake of testing. The more open we are to configuration, the easier the task of aligning with core behaviour.

**Comment by mkundu1** [comment]
@seanpearsonuk Thanks, yes, we can make this option configurable.

**Comment by mkundu1** [comment]
`pyfluent.SHOW_MESH_AFTER_CASE_READ = True` will restore the Fluent behaviour.
