### ISSUE TITLE
pyfluent.launch_fluent(ui_mode=pyfluent.UIMode.GUI) or pyfluent.launch_fluent(ui_mode="gui") doesn't work anymore

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2754]
Looks like the user-input value of `ui_mode` is cleared in the line `ui_mode = _get_ui_mode(show_gui)` in standalone launcher.

**Comment by mkundu1** [comment]
Still getting some odd behaviour with the ui_mode argument. Looking at the PR now `_get_ui_mode`'s arguments are swapped during call.

**Comment by hpohekar** [comment]
@mkundu1 I have tried both `solver = pf.launch_fluent(ui_mode="gui")` and `solver = pf.launch_fluent(ui_mode=pf.UIMode.GUI)` both of them are working fine.

Could you please elaborate on the odd behavior that you have observed. Thank you.

**Comment by hpohekar** [comment]
@mkundu1 Yes, right. Their values were swapping during the call. It's resolved now.
