### ISSUE TITLE
Pandas 2.X not allowed - forcing users to build Pandas wheels on Python 3.12

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyfluent#2799]
https://github.com/ansys/pyfluent/blob/cbab7df3853aa870b65e629774a3457ef01fe077/pyproject.toml#L53

Hi @ansys/pyfluent-maintainers - is there a reason for not upgrading the upper limit of ``pandas`` to ``<3`` rather than ``<2``?

**Comment by RobPasMue** [comment]
If you try installing PyFluent on a Windows machine with Python 3.12, it forces you to build pandas from scratch which is definitely time consuming and error prone (build errors due to compiler features missing).

**Comment by seanpearsonuk** [comment]
Hi @RobPasMue Thanks very much for the notification. @prmukherj will investigate.
