### ISSUE TITLE
Different error messages for incorrect assignment in pyfluent vs pyconsole

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2803]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Low priority issue, tracking for testing.
Error message when attempting to assign a quantity to a setting is different and less helpful in pyfluent standalone:
```
solver.setup.boundary_conditions.pressure_outlet['outlet'].turbulence.turbulent_intensity = mass output ---> Could not handle the quantity, '(200.0, "kg")' for the path, setup/boundary-conditions/pressure-outlet/outlet/turbulence/backflow-turbulent-intensity.
```
```
solver.setup.boundary_conditions.pressure_outlet['outlet'].turbulence.turbulent_intensity = mass output ---> 'backflow_turbulent_intensity_alias' object has no attribute 'allowed_values'
````

### 📝 Steps to reproduce

Load a case in pyfluent 
import quantity class
create quantity
assign the quantity to a boundary condition object with non-matching units
repeat in pyconsole

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys.fluent.core = 0.20.1
```

**Comment by millerj97** [comment]
@cj-hodgson

**Comment by hpohekar** [comment]
@millerj97 @seanpearsonuk @mkundu1 

We are getting same error message for both PyFluent and PyConsole.

PyFluent

![image](https://github.com/ansys/pyfluent/assets/106588300/c4aa68d7-ac49-4e68-ae76-9f804ec3ff75)

PyConsole

![image](https://github.com/ansys/pyfluent/assets/106588300/476a7401-bdc8-4a7a-ade8-9ab261d9e581)
