### ISSUE TITLE
`additional_arguments` not being forwarded properly for Fluent container launches

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2804]
While working on `simba-plugin-fluent` I noticed that `launch_fluent` `additional_arguments` is not being forwarded properly for Fluent container launches, going to add more info as I investigate

**Comment by mkundu1** [comment]
Duplicate of #2624

**Comment by raph-luc** [comment]
Thanks @mkundu1 I should've searched first (and I had already seen that one, just forgot all about it)
