### ISSUE TITLE
pyfluent-ci-1 issue

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2814]
The runner area of `pyfluent-ci-1` is probably corrupted as it keeps failing with [this error](https://github.com/ansys/pyfluent/actions/runs/9058569962/job/24884464092#step:14:82) in every run. This issue is not seen in other runners. I've deleted `_work` and `_diag` folders within the `~/actions-runner` folder, but that didn't help. I think as a next step we can completely remove the `~/actions-runner` folder and do a [fresh setup](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners#adding-a-self-hosted-runner-to-an-organization) of the runner application - this will require org access.

@RobPasMue Can you please check this sometime if you have some idea about this? Currently, I've stopped the runner service, so that the runner is not used in github.

**Comment by RobPasMue** [comment]
Let me check indeed whenever I have some time. Sorry for the inconveniences.

**Comment by mkundu1** [comment]
@RobPasMue No problem at all, thanks very much for looking into this

**Comment by RobPasMue** [comment]
Issue was related to corrupted poetry cache. Closing issue.
