### ISSUE TITLE
deleting cellzone using pyFluent script

### ISSUE THREAD

**Issue by drhcelik** [ansys/pyfluent#2815]
Hello, I need help on one issue. After completing meshing, I want to delete one cell zone and save the mesh using pyFluent.

In GUI, it can be done by using Mesh>Menage>Delete and selecting the cell zone not needed. How could I do the same using script?

Thanks a lot.

**Comment by prmukherj** [comment]
@drhcelik, you can use the following tui command:
meshing.tui.mesh.manage.delete([<_zone-name_ or _zone-id_>], "yes", "yes")

**Comment by drhcelik** [comment]
It worked, thanks a lot.
