### ISSUE TITLE
Should we consistently support both str and enum in the public API?

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2866]
Currently there are some inconsistencies, e.g. among the arguments of `launch_fluent`:
```
product_version: Optional[FluentVersion]
mode: Optional[Union[FluentMode, str, None]]
ui_mode: Union[UIMode, str, None]
```
Strings are easier to type in a constrained interface, e.g. terminal without any auto-completion.

**Comment by raph-luc** [comment]
I'd say yes: should at least accept all arguments that can be enumerations as strings (potentially integers as well for e.g. FluentVersion).

**Comment by prmukherj** [comment]
I agree, we should add support for both str and int as required.
