### ISSUE TITLE
Mount the PyFluent working directory to Docker containers by default

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2867]
Ever since https://github.com/ansys/pyfluent/pull/359 we have been working with Fluent containers mounted to `pyfluent.EXAMPLES_PATH` in the host system. This was apparently fine as until recently, PyFluent with Fluent containers was mainly being used for the PyFluent CI and not many people external to the PyFluent team were using PyFluent with Fluent containers as well. 

Evidently, as seen in the recent uptick in user questions and bug reports related to Fluent containers, more and more people are using PyFluent with Fluent containers.

I do not believe that mounting the `pyfluent.EXAMPLES_PATH` to the Fluent container by default is useful or intuitive to users. I would suggest that this be reconsidered, and changed so that the current PyFluent working directory is mounted to the Fluent container working directory. In this way, both PyFluent and Fluent would be working in the exact same working directory (though each one sees it with a different absolute path). Note that currently PyFluent launches standalone Fluent by default also in the current PyFluent working directory, so this would mean the docker and standalone launchers would have behavior that is more similar to each other.

For the CI, I believe this means changes would also need to be made to the `examples.download_file()` method to make things seamless, as it is currently downloading to `pyfluent.EXAMPLES_PATH` by default, and it should then download to the current working directory (which is also more intuitive IMO). 

This would also break scripts from the users that may already be relying on this (odd) behavior of PyFluent mounting containers to the absolute path of `pyfluent.EXAMPLES_PATH` (and downloading example files to there as well).

Overall, I believe this would be a lot more intuitive to users. This change, with the changes for https://github.com/ansys/pyfluent/issues/2865, should make using PyFluent with Fluent containers a lot more user friendly.

In addition, making the example configuring `launch_fluent()` with `host_mount_path` more prominent would probably also be helpful (maybe adding more examples like that as well, now that Fluent containers seems to be a more common use-case).

@mkundu1 @hpohekar @prmukherj @seanpearsonuk

**Comment by mkundu1** [comment]
Very good point, synchronizing the working directory will give a more intuitive behaviour. And if we make the default mount path configurable, we don't have to make much adjustments for the CIs.

**Comment by seanpearsonuk** [comment]
@raph-luc @mkundu1 @prmukherj @hpohekar  I feel that it is important to expedite this work.  Any of you may self-assign.

**Comment by raph-luc** [comment]
Similar to the requests by Martijn Hoeijmakers, an idea is to consider automatically processing paths when we notice that they are specified using the host's absolute file path system, to transform them into the absolute paths as appropriate for Fluent running inside the container. I think we should create a separate issue tracker for that, but just wanted to share this idea here as it is relevant to this topic.

If we decide to go ahead with something like this, we'd probably be using an infrastructure similar to that of the file transfer service we have. I think this would possibly be like an extension to that service.
