### ISSUE TITLE
Some API classes are incorrectly private

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2904]
A base class of a public class is implicitly public.  E.g., `_HasAllowedValuesMixin` shows up in the documentation but it is not clickable ([here](https://fluent.docs.pyansys.com/version/stable/api/solver/_autosummary/settings/object_name_1.html#object-name-1)). Please check if this is more general and deal with such instances.

**Comment by hpohekar** [comment]
Sphinx does not generate docs for private members. We will have to make it public then it will be clickable.

**Comment by seanpearsonuk** [comment]
That's what I mean. It should be public since it defines part of the interface of something else that is public. This isn't only about the Sphinx documentation.
