### ISSUE TITLE
Turn off the output

### ISSUE THREAD

**Issue by HYB777** [ansys/pyfluent#2965]
Hi, I want to turn off the output while using pyfluent, how to do it?

**Comment by mkundu1** [comment]
If you want to hide the Fluent output, you can execute `<session>.transcript.stop()` after launching a session.

To hide PyFluent warnings, see [this](https://fluent.docs.pyansys.com/version/stable/getting_started/faqs.html#how-do-you-disable-pyfluent-warnings-shown-in-the-console) FAQ entry.
