### ISSUE TITLE
Update ``docker`` and ``requests`` library versions

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyfluent#3007]
From https://github.com/ansys/pyfluent/blob/a478627b9f80b6889e4b08e1af15d5dc9b2a426d/pyproject.toml#L47-L59

I see you are using version 6 of ``docker`` and 2.31 of ``requests``. I strongly encourage you to bump this version to version 7.1.0 for ``docker`` and version 2.32.3 or above for ``requests`` library, since there was a security issue with versions prior to 2.31.

Pinging @ansys/pyfluent-admins - this will require a new patch release of 0.21.0 asap.

**Comment by RobPasMue** [comment]
For some reason release 0.21.1 is not on PyPI.

**Comment by RobPasMue** [comment]
@mainakk could you please look into it since you did the patch release?

**Comment by mkundu1** [comment]
@RobPasMue Yes, there is an issue in the last PR. I started preparing a new version.

**Comment by mkundu1** [comment]
@RobPasMue The correct version is now released in pypi, sorry about the hiccup.
