### ISSUE TITLE
Currently calling the TUI commands in a generic manner, run codgen

### ISSUE THREAD

**Issue by awaisnawab2112** [ansys/pyfluent#3028]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Attempting to run pyfluent on HPC, Fluent launches fine but don't have access to local (python based) TUI commands, code says 
pyfluent.tui WARNING: Currently calling the TUI commands in a generic manner. Please run `python codegen/allapigen.py` from the top-level pyfluent directory to generate the local TUI commands classes.

Have tried running said allapigen script but results in:
cannot import name cogeden_outdir from ansys.fluent.core

### 📝 Steps to reproduce

Running in python 3.8 virtual environment with ansys.fluent.core installed. Using Ansys R1 2024

### 💻 Which operating system are you using?

Linux HPC (rocky based)

### 📀 Which ANSYS version are you using?

2024 R1, python 3.8

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.25
ansys-api-platform-instancemanagement==1.1.0
ansys-fluent-core==0.17.1
ansys-platform-instancemanagement==1.1.2
certifi==2024.6.2
charset-normalizer==3.3.2
contourpy==1.1.1
CoolProp==6.6.0
ctREFPROP==0.10.2
cycler==0.12.1
docker==7.1.0
fonttools==4.53.0
grpcio==1.64.1
grpcio-health-checking==1.62.2
h5py==3.11.0
idna==3.7
importlib_metadata==8.0.0
importlib_resources==6.4.0
kiwisolver==1.4.5
lxml==5.2.2
matplotlib==3.7.5
numpy==1.24.4
packaging==24.1
pandas==2.0.3
pillow==10.4.0
platformdirs==4.2.2
protobuf==4.25.3
psutil==6.0.0
pyfluids==2.6.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
scipy==1.10.1
six==1.16.0
tomli==2.0.1
tzdata==2024.1
urllib3==2.2.2
zipp==3.19.2
```

**Comment by awaisnawab2112** [comment]
Problem only seems to occur for Ansys Fluent 2024 R1, utilised Fluent 2023 R1 with no issues for anyone having the same problem.

Cheers

**Comment by mkundu1** [comment]
`ansys-fluent-core==0.17.1` didn't contain API files for Ansys Fluent 2024 R1. You can use a more recent version of PyFluent to resolve the issue.
