### ISSUE TITLE
Wait for updated state in the enhanced meshing workflow

### ISSUE THREAD

**Issue by prmukherj** [ansys/pyfluent#3037]
Remove the time.sleep(1) by updating and waiting for the updated state.

![346952048-6fe3ecc0-90bf-4d68-9fc4-1f7dd53cdd5c](https://github.com/ansys/pyfluent/assets/109645853/0478897b-c77b-4111-ac4a-56f9f7a98177)

**Comment by mkundu1** [comment]
@prmukherj I think this is already resolved by other changes.
