### ISSUE TITLE
BaseSession foreign objects

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3082]
I notice that `BaseSession` has `events` and `monitors` member but they should only be introduced at the solver level.
```
>>> import ansys.fluent.core as pf
>>> meshing = pf.launch_fluent(mode=pf.FluentMode.MESHING)
>>> {'monitors','events'}.intersection(dir(meshing))
{'events', 'monitors'}
```

**Comment by mkundu1** [comment]
I think events should be available in meshing sessions. We shall restrict monitors to solver sessions.

**Comment by seanpearsonuk** [comment]
@mkundu1 Thanks for clarifying. For an `events` object to make sense in each session type, shall we have a distinct enum type in each registration interface?

**Comment by mkundu1** [comment]
@seanpearsonuk Good idea, the following events are relevant to meshing:
```
class MeshingEvent(Enum):
    """Enumerates over supported Fluent meshing events."""

    ABOUT_TO_LOAD_CASE = "AboutToReadCaseEvent"
    CASE_LOADED = "CaseReadEvent"
    SETTINGS_CLEARED = "ClearSettingsDoneEvent"
    PROGRESS_UPDATED = "ProgressEvent"
    FATAL_ERROR = "ErrorEvent"
```
