### ISSUE TITLE
settings objects contains a public file_transfer_service

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3085]
I don't believe the naming was as intended. It's needed within the implementation only so it should be private. As such, it can straightforwardly be a method (instead of using `@property`). With it being private, we can also drop the docstring.

**Comment by hpohekar** [comment]
@seanpearsonuk 

We are already setting `_file_transfer_service` as a private attribute to base / root object therefore we can not make `file_transfer_service` as a private method or attribute in `Base` class.

![image](https://github.com/user-attachments/assets/c61b8703-2079-4480-a11d-2f5979614216)

**Comment by seanpearsonuk** [comment]
@hpohekar This issue is fixed now, I believe. Is that right?
