### ISSUE TITLE
Inquiry Regarding Automation of Mesh Creation with pyfluent

### ISSUE THREAD

**Issue by strustar** [ansys/pyfluent#3100]
Dear pyfluent Development Team,
My name is Jay Son, and I reside in South Korea.
I am writing to inquire about PyFluent.
I believe one of the primary benefits of using pyfluent is its potential for automation.
Specifically, I am interested in automating the process of mesh creation, which is currently a repetitive task.
From what I have seen, the examples provided in pyfluent mainly illustrate how to work with already created meshes.
However, my goal is to create .msh or .cas files using Python alone, including pymapdl.
Could you please let me know if this is possible?
If so, it would be greatly appreciated if you could add a simple example demonstrating this to the pyfluent documentation.
Thank you for your assistance.
Best regards, Jay Son

**Comment by prmukherj** [comment]
@strustar, Please refer to this example and let us know if you have any further queries:
https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/external_compressible_flow.html#sphx-glr-examples-00-fluent-external-compressible-flow-py
