### ISSUE TITLE
Suspicious error message

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3116]
Test fails for 22.2 but the error message seems to be picking up the API Info for the wrong version.

https://github.com/ansys/pyfluent/actions/runs/10012396726/job/27678968477?pr=3115

```
FAILED tests/test_solver_monitors.py::test_solver_monitors - AttributeError: 'file' object has no attribute 'read_case'.

The most similar API names are:
file.read_case (Command)
file.read_case_data (Command)
file.read_case_setting (Command)
```

**Comment by mkundu1** [comment]
`read_case` was added in 23.1. In 22.2, we had `file.read_case(file_type=...`.

**Comment by hpohekar** [comment]
@seanpearsonuk 

It's correct that `'file' object has no attribute 'read_case'.` for 22.2 version. It has only `read` method.

![image](https://github.com/user-attachments/assets/690cabe2-5316-4c3c-8025-0c5367cf4579)

We are not generating `api_objects.json` per version to reduce packaging size in Fluent. 

Therefore it is showing search results for latest release Fluent version.
