### ISSUE TITLE
Launching and connecting to Fluent page issue

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3123]
Issue is visible in the nightly dev build. This is intended to render a numbered list:

You can use the [connect_to_fluent()](https://github.com/ansys/api/general/launcher/index.html#ansys.fluent.core.launcher.launcher.connect_to_fluent) function to connect to a running Fluent session that has already started the gRPC server. There are some options for starting Fluent’s gRPC server:

#.Start Fluent with <fluent_executable> -sifile=<server_info_file_name>, or #.Execute the server/start-server TUI command in Fluent, or #.Execute File -> Applications -> Server -> Start... from the Fluent GUI ribbon menu.

**Comment by mkundu1** [comment]
Already fixed:
![Image](https://github.com/user-attachments/assets/2aee1bdf-86ef-4169-ac16-148a1335f902)
