### ISSUE TITLE
The parameter values obtained via casereader and via settings API are of different units.

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#3138]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

The parameter values obtained via casereader and via settings API are of different units.
 
This is what I get in case of Casereader/lightweight: - 
```
reader = CaseFile(case_file_name=input_filepath)
reader.input_parameters()
```
_OrderedDict([('inlet_pressure', OrderedDict([('name', 'inlet_pressure'), ('numeric_value', 3.0), ('unit', 'atm'), ('bounds', [])]))])_
 
in case of settings API: - 
`fluent_session.settings.parameters.input_parameters.list()`
_OrderedDict([('inlet_pressure', OrderedDict([('numeric_value', 303975.0), ('units', ['pressure', 'density*specific-energy', 'force-per-area', 'source-turbulent-viscosity'])]))])_

### 📝 Steps to reproduce

Step 1: extract parameters using CaseReader:
reader = CaseFile(case_file_name=input_filepath)
reader.input_parameters()

Step 2: extract parameters using settings API
fluent_session.settings.parameters.input_parameters.list()

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2025R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.25
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-fluent-core==0.22.dev0
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc0
ansys-tools-filetransfer==0.1.0
```

**Comment by tejalprabhu01** [comment]
@mkundu1 @seanpearsonuk

**Comment by mkundu1** [comment]
Filed a Fluent bug - 1105818. I'll look into a PyFluent side workaround meanwhile.
