### ISSUE TITLE
Clarification on units returned through different APIs

### ISSUE THREAD

**Issue by sravanansys** [ansys/pyfluent#315]
Hi,

I am seeing this behavior that the settings API always return the values in SI unit regardless of what units were set in Fluent UI and TUI API returns the value according to the unit set in Fluent? Is this the expected behavior based on summary of #76 ?

![image](https://user-images.githubusercontent.com/99287292/163653492-75904cba-3b9d-4556-bbde-650867d823f3.png)

If yes, it would be better to document it.

Regards,
Sravan

**Comment by seanpearsonuk** [comment]
APIs return values in SI units, which is documented: https://fluent.docs.pyansys.com/version/stable/user_guide/units.html.
