### ISSUE TITLE
Check set_state behaviour

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3195]
We have a recent fix around `TaskObject.TaskType` being assigned `None`, following this creation syntax:
```Python
>>> workflow.setState({r'TaskObject:Describe Overset Features': {},})
```
This kind of fix does not appear necessary in meshing workflow's own Python interface. A fundamental check to do first is whether `TaskObject.TaskType` is `None` via meshing workflow's Python interface following the above command. If so, then meshing workflow needs to fix that behaviour. If not, then we need to fix the PyFluent behaviour.

**Comment by prmukherj** [comment]
TaskObject.TaskType is None via meshing workflow's Python interface, and this has been verified.

Moreover the actual issue due to which this was required has been resolved cleanly by segregation of the Classic Meshing Workflow from the Enhanced one.
