### ISSUE TITLE
Out-of-the-Box Support for Capturing Transaction Logs in a file

### ISSUE THREAD

**Issue by anssakthi** [ansys/pyfluent#3255]
### 📝 Description of the feature

We have implemented a custom method to capture transaction logs during operations. However, this method is not working as expected under certain conditions. It would be beneficial to have a built-in, out-of-the-box feature within the library that can reliably handle this task.

### 💡 Steps for implementing the feature

We are currently using the following approach to capture logs
`
class TranscriptData():

   def __init__(self, filename):
       self.filename = filename

   def __call__(self, data):
       with open(self.filename, "a") as f:
              f.write(f"{data}\n")
     
transcript = TranscriptData(os.path.join(wdr.parent,"meshing_fluent.log"))
flow_mesh_setup.session.transcript.register_callback(transcript)
`
However, the issue with this approach is that when running PyFluent with GPU, the logs are being appended twice.

**Comment by seanpearsonuk** [comment]
@hpohekar Please can you double-check first that this is requesting something not already provided.

**Comment by hpohekar** [comment]
@anssakthi @seanpearsonuk 

We can write transcript data to a specific file as follows. It writes data to given file name - `"test_transcript.trn"`.

```
>>> import ansys.fluent.core as pyfluent
>>> from ansys.fluent.core import examples
>>> case_file_name = examples.download_file("mixing_elbow.cas.h5", "pyfluent/mixing_elbow")
>>> session = pyfluent.launch_fluent()
>>> session.transcript.start("test_transcript.trn")
>>> session.settings.file.read_case(file_name=case_file_name)
>>> session.settings.file.write_case(file_name=r"write_test.cas.h5")
>>> session.transcript.stop()    
>>> session.exit()    
```              

We can write transcript logs to a specific file using PyFluent logging as follows. It writes logs to given file name - `"'test_file.log"`.

```
>>> import ansys.fluent.core as pyfluent
>>> config_dict = pyfluent.logging.get_default_config()
>>> config_dict['handlers']['pyfluent_file']['filename'] = 'test_file.log'
>>> pyfluent.logging.enable(custom_config=config_dict)
PyFluent logging file D:\Repos\pyfluent\test_file.log
Setting PyFluent global logging level to DEBUG.
>>> import ansys.fluent.core as pyfluent
>>> from ansys.fluent.core import examples
>>> case_file_name = examples.download_file("mixing_elbow.cas.h5", "pyfluent/mixing_elbow")
>>> session = pyfluent.launch_fluent()
>>> session.settings.file.read_case(file_name=case_file_name)
>>> session.settings.file.write_case(file_name=r"write_test.cas.h5")
>>> session.exit()
```
