### ISSUE TITLE
Errors while adding DP in parametric project

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#3280]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

Following error is seen while adding Design Point in a parametric project:
![image](https://github.com/user-attachments/assets/68b97cab-2876-4f78-b267-e42079cda9b4)

This is reproduced only on some user systems.
Find attached project with which the issue was reproduced:
[Design0001.zip](https://github.com/user-attachments/files/16926952/Design0001.zip)

@seanpearsonuk @mkundu1 @prmukherj 

### 📝 Steps to reproduce

import ansys.fluent.core as pyfluent
session = pyfluent.launch_Fluent(start_watchdog=True)
study_name = session.settings.current_parametric_study()
study = session.settings.parametric_studies[study_name]
dp_names = set([*study.design_points.keys()])
study.design_points.create()
dp_name = set([*study.design_points.keys()]).difference(dp_names).pop()
design_point = study.design_points[dp_name]
design_point.input_parameters[name] = value

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2025R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core v0.22dev0
```

**Comment by prmukherj** [comment]
@tejalprabhu01, could you please confirm if this issue is reproducible in the latest v251 fluent image?
Thank you

**Comment by prmukherj** [comment]
@tejalprabhu01, this was a temporary issue I think with a particular fluent build due to which the PyFluent nightly tests were also failing with the same error. I think it is no longer reproducible. Please let us know if you find otherwise. Thank you.

**Comment by tejalprabhu01** [comment]
@prmukherj tested this with Fluent Build Time: Sep 12 2024 02:54:13 EST  Build Id: 155  Revision: ff7ada14bc  Branch: develop and pyfluent v0.24.1. The issue is fixed!
