### ISSUE TITLE
Look into make_a_copy functionality for settings named object

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3294]
materials method make_a_copy returns string as follows:
```Python
>>> x=solver.setup.materials.fluid.make_a_copy(from_="water",to="water-2")
>>> x
"'water"
```

Rename goes like this (it returns a string list):

```Python
>>> solver.setup.materials.fluid.rename(old="bob", new="bobby")
["'bob"]
```

create behaves differently to make_a_copy. create returns an object. Why only this one? 
```Python
>>> mysolid = solver.setup.materials.solid.create("mysolid")
>>> mysolid
<flapi.flobject.child_object_type object at 0x00000000D30002E0>
>>> mysolid.chemical_formula = "SiO2"
>>> mysolid.density = 2650
```

**Comment by prmukherj** [comment]
Current behavior in 

PyConsole:
![Image](https://github.com/user-attachments/assets/f9eef35e-3b40-44dd-ba3d-04cf26c1ad7a)

PyFluent:
![Image](https://github.com/user-attachments/assets/158d4208-e615-4e94-9995-3dca6a66a22f)

**Comment by prmukherj** [comment]
Current behavior:
![Image](https://github.com/user-attachments/assets/9288c207-8135-4ce6-a40e-52791731bcbf)
