### ISSUE TITLE
How to initialize solver with a steady solution (.dat file or .cas file) and then run transient solver and how to record transient results

### ISSUE THREAD

**Issue by alwaysbyx** [ansys/pyfluent#3322]
Hi, I'd like to learn how to initialize with a steady solution and run transient solver. 

Currently, I can only think of running steady solution and then run transient solution. 
For instance, 

```python
# run steady first
solver = pyfluent.launch_fluent(mode="solver") 
solver.settings.setup.general.solver.time.set_state("steady")
solver.settings.solution.initialization.hybrid_initialize()
solver.settings.solution.run_calculation.iterate(iter_count=1000)
# then run unsteady
solver.settings.setup.general.solver.time.set_state("unsteady-1st-order") 
solver.tui.solve.set.transient_controls.tie_step_size = 5
solver.tui.solve.dual_time_iterate(100)
```

(1) So first question, I wonder if there is methods to initialize and load .dat file for initialization? 
(2) When I try to run transient solutions, I dont know how to record transient results at each time step and I can not find any sample codes. Can any one help with this? 

Thanks!

**Comment by dnwillia-work** [comment]
Yes, you can read a data file saved from just before calling `solver.tui.sole.dual_time_iterate(100)`.

`solver.settings.file.read_data(name="steady.dat.h5")`

BTW your tui commands can be replaced too:

```
solver.settings.run_calculation.transient_controls.specified_time_step = True
solver.settings.run_calculation.transient_controls.time_step_size = 5.0
solver.settings.run_calculation.dual_time_iterate(time_step_count=100)
```

**Comment by alwaysbyx** [comment]
Thanks! 
I want to clarify that I have to run  `solver.settings.file.read_data(file_name="steady.dat.h5")` instead of 
`solver.settings.file.read_data(name="steady.dat.h5")`.
Also I can not run `solver.settings.run_calculation.` as there is no `run_calculation` module, instead, I can run
`solver.settings.solution.run_calculation.`

One more question, if I want to record field data at each time step, if there are any better ways I can do that? I can think of saving every case file at each time step, and then load that and get data. 

```python
# read 
field_data = solver.field_data
temp_data = field_data.get_scalar_field_data(
        field_name="temperature", surface_name = "z-mid"
    )
```

**Comment by mkundu1** [comment]
@alwaysbyx You can listen to the event `SolverEvent.TIMESTEP_ENDED`. Please check the [user guide](https://fluent.docs.pyansys.com/version/stable/user_guide/events.html#observing-events) for examples of registering callbacks on solver events.

**Comment by alwaysbyx** [comment]
Thank you. I try to implement saving figure when listening events:

```python
def save_figure(session, event_info):
    if event_info.index % interval == 0 and event_info.index != 0:
        print(event_info.index)
        session.results.graphics.contour["temp-z"].display()
        session.results.graphics.views.restore_view(view_name = "front")
        session.results.graphics.picture.save_picture(file_name="image_path") 

callback_case = solver.events.register_callback(SolverEvent.ITERATION_ENDED, save_figure) 
```

However, it save other plots instead of the contour figures. I guess it is because the other result figure is pushed to the picture list. Do you know how to save the contour figure directly?

**Comment by dnwillia-work** [comment]
> Thanks! I want to clarify that I have to run `solver.settings.file.read_data(file_name="steady.dat.h5")` instead of 

Yes, it should be `file_name`.  My mistake.

`solver.settings.file.read_data(name="steady.dat.h5")`. Also I can not run `solver.settings.run_calculation.` as there is no `run_calculation` module, instead, I can run `solver.settings.solution.run_calculation.`

Yeah, again my mistake when trying to work it out from the tree documentation.   You found the right spot.

> One more question, if I want to record field data at each time step, if there are any better ways I can do that? I can think of saving every case file at each time step, and then load that and get data.

I think mkundu1's suggestion is a good one.  Just register a function that listens to that event and write the field data you want using the field data interface.  You can also use Fluent's built-in file export capability too.

**Comment by alwaysbyx** [comment]
Can you address the above figure saving issue? Thank you!

**Comment by mkundu1** [comment]
Using Fluent's solution animation is more suitable for your use case. Here is an example code:
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent()
solver.settings.file.read_case(file_name=r"elbow.cas.h5")
solver.settings.solution.initialization.hybrid_initialize()
contour = solver.settings.results.graphics.contour.create("c1")
contour.surfaces_list = ["wall"]
animation = solver.settings.solution.calculation_activity.solution_animations.create("a1")
animation.animate_on = "c1"
animation.storage_type = 7 # for PNG format
solver.settings.solution.run_calculation.iterate(iter_count=10)
```
Above code will write a series of PNG files in the current working directory. Setting the image file format is not intuitive, here are the codes:
PPM - 4
HSF - 5
TIFF - 6
PNG - 7
JPEG - 8

**Comment by alwaysbyx** [comment]
Thank you!!
