### ISSUE TITLE
Run transient simulation and after simulating 60seconds flow time the simulation will automatically stop

### ISSUE THREAD

**Issue by alwaysbyx** [ansys/pyfluent#3328]
Hi, I use the following codes to run transient simulation. 

```python
    solver.settings.solution.calculation_activity.solution_animations[
            "animate-temp"
        ] = {
            "animate_on": "temp",
            "storage_type": 7,
            "frequency_of": "time-step",
            "frequency": 6,
            "view": "front",
            "storage_dir": save_path,
        }
    solver.tui.solve.set.transient_controls.time_step_size = 5.
    solver.tui.solve.set.transient_controls.max_flow_time = 1800.
    solver.tui.solve.dual_time_iterate(12*30)
```

However, it will automatically stop the simulation aftet 60 seconds of flow time. After logging:
```python
Flow time = 59s, time step = 59
301 more time steps
Creating animation sequence xxxxx
```
the execution ends. Is it because the solution animation only supports 60 seconds of flow time or is there other reasons? Thank you!

**Comment by mkundu1** [comment]
`solver.tui` has interfaces for command execution only. For the set-state capability and a better API experience in general, please use the `solver.settings` API:
```
solver.settings.solution.run_calculation.transient_controls.time_step_size = 5
solver.settings.solution.run_calculation.transient_controls.max_flow_time = 5=1800
```

**Comment by alwaysbyx** [comment]
I am using the following codes. I want to note that set max_flow_time will incur the error: `RuntimeError: api-set-var: the object is not active
Error Object: solution/run-calculation/transient-controls/max-flow-time
`.

However, it still stops automatically without running all the time steps. 

```
Flow time = 55s, time step = 11
189 more time steps
```


```python
# codes to run transient simulation
solver.settings.solution.run_calculation.transient_controls.time_step_size = 5.
        solver.settings.solution.run_calculation.dual_time_iterate(
            time_step_count=200, max_iter_per_step=5
        )
```
