### ISSUE TITLE
HDF-5 error while writing case file

### ISSUE THREAD

**Issue by tejalprabhu01** [ansys/pyfluent#3333]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [ ] I am using a Python virtual environment

### 🐞 Description of the bug

I am getting following error while writing case file with the command : session.settings.file.write_case_data(file_name=output_filepath)

HDF5-DIAG: Error detected in HDF5 (1.12.2) MPI-process 0:
  #000: C:\.conan\888d91\1\hdf5-1.12.2\src\H5F.c line 532 in H5Fcreate(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #001: C:\.conan\888d91\1\hdf5-1.12.2\src\H5VLcallback.c line 3282 in H5VL_file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: C:\.conan\888d91\1\hdf5-1.12.2\src\H5VLcallback.c line 3248 in H5VL__file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: C:\.conan\888d91\1\hdf5-1.12.2\src\H5VLnative_file.c line 63 in H5VL__native_file_create(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #004: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Fint.c line 2112 in H5F_open(): problems closing file
    major: File accessibility
    minor: Unable to close file
  #005: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Fint.c line 1574 in H5F__dest(): problems closing file
    major: File accessibility
    minor: Unable to release object
  #006: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Faccum.c line 1072 in H5F__accum_reset(): can't flush metadata accumulator
    major: File accessibility
    minor: Unable to flush data from cache
  #007: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Faccum.c line 1037 in H5F__accum_flush(): file write failed
    major: Low-level I/O
    minor: Write failed
  #008: C:\.conan\888d91\1\hdf5-1.12.2\src\H5FDint.c line 240 in H5FD_write(): driver write request failed
    major: Virtual File Layer
    minor: Write failed
  #009: C:\.conan\888d91\1\hdf5-1.12.2\src\H5FDsec2.c line 870 in H5FD__sec2_write(): file write failed: time = Tue Oct  1 11:32:36 2024
, filename = 'D:/Release25R1/Bugbash/Test_fluent2.opd/Sensitivity/Design0001\nozzle-2D-WB.cas.h5', file descriptor = 3, errno = 13, error message = 'Permission denied', buf = 00000291D3E7EC98, total write size = 800, bytes this sub-write = 800, bytes actually written = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Write failed
  #010: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Fint.c line 2076 in H5F_open(): unable to flush superblock
    major: File accessibility
    minor: Unable to flush data from cache
  #011: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Fio.c line 267 in H5F_flush_tagged_metadata(): can't reset accumulator
    major: Low-level I/O
    minor: Can't reset object
  #012: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Faccum.c line 1072 in H5F__accum_reset(): can't flush metadata accumulator
    major: File accessibility
    minor: Unable to flush data from cache
  #013: C:\.conan\888d91\1\hdf5-1.12.2\src\H5Faccum.c line 1037 in H5F__accum_flush(): file write failed
    major: Low-level I/O
    minor: Write failed
  #014: C:\.conan\888d91\1\hdf5-1.12.2\src\H5FDint.c line 240 in H5FD_write(): driver write request failed
    major: Virtual File Layer
    minor: Write failed
  #015: C:\.conan\888d91\1\hdf5-1.12.2\src\H5FDsec2.c line 870 in H5FD__sec2_write(): file write failed: time = Tue Oct  1 11:32:36 2024
, filename = 'D:/Release25R1/Bugbash/Test_fluent2.opd/Sensitivity/Design0001\nozzle-2D-WB.cas.h5', file descriptor = 3, errno = 13, error message = 'Permission denied', buf = 00000291D3E93218, total write size = 96, bytes this sub-write = 96, bytes actually written = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Write failed

I have attached the transcript and case file for reference

@seanpearsonuk @mkundu1 @prmukherj 
[data.zip](https://github.com/user-attachments/files/17202865/data.zip)

### 📝 Steps to reproduce

session = pyfluent.launch_fluent(dimension=2, mode="solver", ui_mode="gui", start_watchdog=False )
session.settings.file.read(file_type="case", file_name=r"nozzle-2D-WB.cas.h5")
session.settings.solution.initialization.hybrid_initialize()
session.settings.solution.run_calculation.iterate()
session.settings.parameters.output_parameters.list()
session.settings.file.write_case_data(file_name=output_filepath)

PS- here the case file already exists and needs to be overwritten

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2025R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-fluent-core
```

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 

Do you believe that this is a PyFluent issue? It looks either that there isn't write permission, or else, less likely, a malfunction in the library used by Fluent.  `write_case_data` generally works even if the files exist. 

@hpohekar Please could you triage this issue when you have some time?

**Comment by tejalprabhu01** [comment]
@seanpearsonuk I get this issue only while using from optiSLang, outside optiSLang the case file gets overwritten without error.

**Comment by hpohekar** [comment]
@seanpearsonuk @tejalprabhu01 

Ensure that your program has permission to write to the directory where you are trying to create the file. 

If a file with the same name already exists and is open in another process, it might prevent your program from creating or opening it. Ensure that no other processes are accessing the file.

**Comment by tejalprabhu01** [comment]
@hpohekar The program definitely has write permissions in the directory, because there are others files written in there. Also mesh file gets overwritten. The issue is only for case files. 

About being used by other process, atleast optiSLang has not explicitly launched any other process that is accessing the same case file, since there is only one fluent process with that particular working directory. I donot know if internally any fluent subprocess is locking that case file.

**Comment by hpohekar** [comment]
@tejalprabhu01 

Can you share output of `lsof /path/to/nozzle-2D-WB.cas.h5` to ensure that no other processes are accessing this file ?

**Comment by hpohekar** [comment]
`python_connect_server`
from OptisLang launches Fluent as a child process but it holds access of case file (even after exiting Fluent) therefore we can not write to same file.
