### ISSUE TITLE
FieldDataService::getSurfacesInfo: invalid field

### ISSUE THREAD

**Issue by ShiYi2023** [ansys/pyfluent#3379]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

As soon as I try to define a surface for any type of plotting I get this error:
`Error: FieldDataService::getSurfacesInfo: invalid field 
Error Object: #f`

I can manually create contours in Fluent.
![374798159-5d7c6e54-f150-4d90-9d2a-e5b459643e9d](https://github.com/user-attachments/assets/4f9fefdf-5ba2-4037-abd1-7b21c4f6d1e4)

Pyfluent can also be created normally. 
`
session.results.graphics.contour['abc'] = {"field": "temperature","surfaces_list": ["cell:1","heating"]}
`

However, when using visualization. pyvista, it is not possible to obtain and set surfaces_list. Surfaces_list=["cell: 1", "heating"] and print (surfaces_list. lowed_values) will both report errors. I'm not sure what the reason is, I hope to get help.
![2](https://github.com/user-attachments/assets/4f7e6c96-ecdf-4f86-9c3f-4f3148f82cd1)

### 📝 Steps to reproduce

I can initiate a pyfluent session but as soon as I try to define a surface I get this error: Error: FieldDataService::getSurfacesInfo: invalid field,the same error is visible in the GUI command view as well.

`
import ansys.fluent.core as pyfluent
from ansys.fluent.core import UIMode
from ansys.fluent.visualization import set_config
from ansys.fluent.visualization.matplotlib import Plots
from ansys.fluent.visualization.pyvista import Graphics
solver_session = pyfluent.launch_fluent(precision="double", processor_count=2, mode="solver")
solver_session.tui.file.read_case("123123.cas.h5")
solver_session.tui.file.read_data("123123.dat.h5")
graphics = Graphics(session=solver_session)

temperature_contour = graphics.Contours["contour-1"]
temperature_contour.field = "temperature"
print(temperature_contour.surfaces_list.allowed_values) #Error: FieldDataService::getSurfacesInfo: invalid field
#temperature_contour.surfaces_list = ["cell:1", "heating"] #Error: FieldDataService::getSurfacesInfo: invalid field
#temperature_contour.display("window-1")
`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Revision: 23.1.0 for ANSYS 2023 R1

### 🐍 Which Python version are you using?

3.12

### 📦 Installed packages

```shell
about-time==4.2.1
absl-py==2.1.0
alive-progress==3.1.5
ansys-api-fluent==0.3.27
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-fluent-core==0.26.0
ansys-fluent-parametric==0.10.0
ansys-fluent-visualization==0.14.0
ansys-platform-instancemanagement==1.1.2
ansys-tools-filetransfer==0.1.0
ansys-units==0.3.2
anyio==4.6.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
attrs==24.2.0
babel==2.16.0
beartype==0.17.2
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
contourpy==1.3.0
cycler==0.12.1
debugpy==1.8.6
decorator==5.1.1
defusedxml==0.7.1
docker==7.1.0
et-xmlfile==1.1.0
executing==2.1.0
fastjsonschema==2.20.0
flatbuffers==24.3.25
fonttools==4.53.1
fqdn==1.5.1
gast==0.6.0
google-pasta==0.2.0
grapheme==0.6.0
grpcio==1.66.1
grpcio-health-checking==1.62.3
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httpx==0.27.2
idna==3.8
importlib_metadata==8.5.0
ipykernel==6.29.5
ipython==8.27.0
ipywidgets==8.1.5
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
keras==3.5.0
kiwisolver==1.4.7
libclang==18.1.1
lxml==4.9.4
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
matplotlib-inline==0.1.7
mdurl==0.1.2
mistune==3.0.2
ml-dtypes==0.4.0
namex==0.0.8
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
nltk==3.9.1
notebook==7.2.2
notebook_shim==0.2.4
numpy==1.26.4
openpyxl==3.1.5
opt-einsum==3.3.0
optree==0.12.1
overrides==7.7.0
packaging==24.1
pandas==1.5.3
pandocfilters==1.5.1
parso==0.8.4
patsy==0.5.6
pillow==10.4.0
platformdirs==3.11.0
plotly==5.24.0
plotly-express==0.4.1
pooch==1.8.2
prometheus_client==0.21.0
prompt_toolkit==3.0.48
protobuf==4.25.4
psutil==5.9.8
pure_eval==0.2.3
pycparser==2.22
Pygments==2.18.0
pyparsing==3.1.4
PySide6==6.7.2
PySide6_Addons==6.7.2
PySide6_Essentials==6.7.2
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.2
pyvista==0.44.1
pyvistaqt==0.11.1
pywin32==306
pywinpty==2.0.13
PyYAML==6.0.2
pyzmq==26.2.0
QtPy==2.4.1
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.8.1
rpds-py==0.20.0
scipy==1.14.1
scooby==0.10.0
seaborn==0.13.2
Send2Trash==1.8.3
setuptools==74.1.2
shiboken6==6.7.2
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
statsmodels==0.14.2
tenacity==9.0.0
tensorboard==2.17.1
tensorboard-data-server==0.7.2
tensorflow==2.17.0
tensorflow-intel==2.17.0
termcolor==2.4.0
terminado==0.18.1
tinycss2==1.3.0
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
ttkbootstrap==1.10.1
types-python-dateutil==2.9.0.20240906
typing_extensions==4.12.2
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.2
vtk==9.3.1
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.4
wheel==0.44.0
widgetsnbextension==4.0.13
wrapt==1.16.0
zipp==3.20.1
```

**Comment by prmukherj** [comment]
@ShiYi2023, not able to reproduce this. Could you please share your case file if possible. Or, please try to use the example in https://github.com/ansys/pyfluent-visualization/blob/main/examples/00-postprocessing/post_processing_exhaust_manifold.py and try to replicate your issue.

Thank you.

**Comment by ShiYi2023** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by ShiYi2023** [comment]
[test.zip](https://github.com/user-attachments/files/17326638/test.zip)
@prmukherj Thank you for your help. The attachment is the case. I have tried the official demo and it worked fine, so I am very confused

**Comment by prmukherj** [comment]
I can reproduce the issue using the case file. Will get back to you soon.

**Comment by prmukherj** [comment]
The created surfaces in the case file are invalid ("cell", "interior-cell"). If we delete these surfaces manually and run then this will pass. We had added a check in the server side for these cases from 23R2 and this will work from 23R2 without any issues but if you wish to use 23R1, you need to follow this work-around.

Thank you.

cc. @seanpearsonuk, @ajain-work

**Comment by ShiYi2023** [comment]
@prmukherj Thank you for your help, it has been very helpful to me
