### ISSUE TITLE
some optional dependencies are not real project dependencies 

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3420]
Some of these are only used in documentation, not in library code:

openpyxl = { version = ">=3.1.5", optional = true }
plotly = { version = ">=5.22.0", optional = true }
python-pptx = { version = ">=0.6.23", optional = true }
seaborn = { version = ">=0.13.2", optional = true }
tensorflow = { version = ">=2.17.0", optional = true }

See pyproject.toml

**Comment by hpohekar** [comment]
> Some of these are only used in documentation, not in library code:
> 
> openpyxl = { version = ">=3.1.5", optional = true } plotly = { version = ">=5.22.0", optional = true } python-pptx = { version = ">=0.6.23", optional = true } seaborn = { version = ">=0.13.2", optional = true } tensorflow = { version = ">=2.17.0", optional = true }
> 
> See pyproject.toml

@seanpearsonuk These dependencies are required for example scripts therefore we have made them optional.

**Comment by seanpearsonuk** [comment]
@hpohekar optional mitigates the issue but the dependendnecies are nevertheless in the wrong place. They should be expressed as documentation dependencies only.

**Comment by hpohekar** [comment]
@seanpearsonuk We have already added them in `[tool.poetry.extras]`

**Comment by hpohekar** [comment]
> @hpohekar optional mitigates the issue but the dependendnecies are nevertheless in the wrong place. They should be expressed as documentation dependencies only.

OK.
