### ISSUE TITLE
ImportError: cannot import name 'SolverEvent' from 'ansys.fluent.core'

### ISSUE THREAD

**Issue by alwaysbyx** [ansys/pyfluent#3452]
`from ansys.fluent.core import SolverEvent`
For this code, I could not import SolverEvent and error raises as 
`ImportError: cannot import name 'SolverEvent' from 'ansys.fluent.core'`

Is there any updates about the package

**Comment by mkundu1** [comment]
What is the version of ansys.fluent.core? `SolverEvent` was added in 0.23.

**Comment by alwaysbyx** [comment]
Thanks! I have python3.9 and using `pip install ansys-fluent-core` will automatically install 0.22.0.
