### ISSUE TITLE
Replace some scheme_eval service calls

### ISSUE THREAD

**Issue by hpohekar** [ansys/pyfluent#3512]
Point 1:

`(map car (apply append (map client-inquire-cell-vector-functions (inquire-domain-for-cell-functions))))
(velocity relative-velocity)` can be replaced by `GetVectorFieldsInfo`

**Comment by seanpearsonuk** [comment]
@hpohekar What details do you have in mind here?

**Comment by hpohekar** [comment]
@seanpearsonuk I have already discussed few things with @mkundu1 as follows:

Point 1:

Regarding (units/get-pretty-wb-units-from-dimension (units/inquire-dimension '{quantity})) we always get field-data in SI units. The SI unit can be queried from the ansys-units library.

Point 2:

`(map car (apply append (map client-inquire-cell-vector-functions (inquire-domain-for-cell-functions))))
(velocity relative-velocity)` can be replaced by `GetVectorFieldsInfo`
