### ISSUE TITLE
Data Sampling using settings API doesn't show list of custom field functions

### ISSUE THREAD

**Issue by sravanansys** [ansys/pyfluent#353]
Settings API object for data sampling shows list of species used for data sampling that user can specify the list of species. But it doesn't show list of custom field functions as shown in this image. This would limit the users to specify specific custom field functions to be used for data sampling

![image](https://user-images.githubusercontent.com/99287292/165698464-8f0aaba2-af46-46d4-a4f8-86645a2e0141.png)

**Comment by seanpearsonuk** [comment]
TODO: create US

**Comment by seanpearsonuk** [comment]
@gyeole We haven't created a user story for this at the moment. We need to direct a user story to the appropriate team

**Comment by seanpearsonuk** [comment]
Now listed here https://github.com/ansys/pyfluent/issues/2006

**Comment by seanpearsonuk** [comment]
Resolved.
