### ISSUE TITLE
Exception handling not working for TUI APIs

### ISSUE THREAD

**Issue by mkvani** [ansys/pyfluent#392]
**Feature**: TUI API for material change/create

**Issue**: When TUI API is used for material change/create, it does not provide any response for exception handling. In case, TUI API did not work correctly, then there is no way to know this from API response.

TUI API command used:

''' Python

session.tui.solver.define.materials.change_create('copper', 'copper', 'no', 'yes', 'cyl-orthotropic', 0, 0, 0, 0, 0, 1, 'constant', radial_cond, 'constant', tangential_cond, 'constant', axial_cond)

'''
The above API passes a wrong TUI command to Fluent. However, this API does not provide a repose showing error.

Response of the command:

![image](https://user-images.githubusercontent.com/102018222/167384498-27d6fefe-6efc-4631-af37-f9dfb91c4fe5.png)

Best regards,
Manoj

**Comment by seanpearsonuk** [comment]
Closing based on the response from @mkundu1
