### ISSUE TITLE
Automatic Plot and File does not work with TUI

### ISSUE THREAD

**Issue by PySRG** [ansys/pyfluent#404]
This might be related to Fluent itself and not PyFluent so please discard if appropriate.

While setting up Report Definitions using TUI API, it does not automatically create Report Plot and Report File. I see the same behavior while using TUI in Fluent console. I am using 5th May build of Fluent 2022R2.

**Comment by Carlisle-Lee** [comment]
I am a beginner for pyfluent. I also want to output a report with monitor.report_files. Have you successfully defined a report_file in code? Could you share the method? I cannot define the surface in report_file! Thanks!

**Comment by dnwillia-work** [comment]
@Carlisle-Lee Please open a separate issue for your question.

**Comment by mkundu1** [comment]
Any improvement regarding usage of these settings can be followed up in settings API in Fluent side, hence closing this.
