### ISSUE TITLE
solver.setup.boundary_conditions.set_state(test) GRPC_ERROR

### ISSUE THREAD

**Issue by ypatel-qa** [ansys/pyfluent#548]
Issue reported by Ryan O'Conor (PyFluent AFT).

![image](https://user-images.githubusercontent.com/97630098/175358571-4fe3f68b-096a-4c5b-b273-45a6f8be93ab.png)

![image](https://user-images.githubusercontent.com/97630098/175358225-9401998c-dbf3-4ff8-a3fb-4f192a0a5dcf.png)

**Comment by gyeole** [comment]
@mkundu1 @seanpearsonuk 
![image](https://user-images.githubusercontent.com/94447555/187951489-50f09348-99e1-4c5a-ac62-b3ef058dfca3.png)

**Comment by rploconnor** [comment]
@mkundu1 @seanpearsonuk : Further to what Gitesh has noted, check also the Symmetries.

**Comment by seanpearsonuk** [comment]
@gyeole Do you think thath this is fully resolved by now?
