### ISSUE TITLE
FieldData Re-design & New Features

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#561]
```
>>> help(field_data.get_fields)
Help on method get_fields in module ansys.fluent.core.services.field_data:

get_fields() -> Dict[int, Dict[int, Dict[str, <built-in function array>]]] method of ansys.fluent.core.services.field_data.FieldData instance
    Provide data for previously added requests.

    Returns
    -------
    Dict[int, Dict[int, Dict[str, np.array]]]
        Data is returned as dictionary of dictionaries in following structure:
        tag_id [int]-> surface_id [int] -> field_name [str] -> field_data[np.array]
```
so, in the absence of any "previously added requests" get_fields() returns an empty dictionary:

```
>>> s.field_data.get_fields()
{}
```

Without reading help, the behaviour is surprising, which we definitely want to avoid.
Additionally the result of get_fields is coupled to other calls (add_get_vector_fields_request etc).  All call are going through a single field_data object so this design is unsafe in terms of exception and thread safety. The Python field_data object should be clean and stateless.

Meanwhile:

```
>>> field_info.get_fields_info()
```

returns information about all the fields.

Summary
======
- The baseline requirement is a simple to use interface without surprises
- The result of one call to query data should not be coupled to previous calls.  This is an antipattern that directly causes defective behaviour
- In **addition** to the above _baseline requirement_, we can consider including specialized methods/interfaces like those described above, but only if they follow rigorous design paradigms

**Comment by dnwillia-work** [comment]
I agree with the need for a simple 'array like' interface usable on the client side.

For example, I should be able to retrieve an array as follows:

`a = getArray("zone-5", "pressure")  # collects the pressure field from zone-5 and copies it to the client`

- The object `a` would be a NumPy array
- The Python interpreter environment is serial so `a` should be coming in the serial order for global IDs.  It means data shipping the data in Fluent before pulling it into the interpreter.

Manipulating and setting the data would also be needed I think:
```
T = getArray("zone-5", "temperature")
T*= 10.0

# Sends T to the compute nodes and data ships the data so it's repartitioned using the current solver partitioning
# i.e. assume the ordering in the client is consecutive in terms of global IDs
getArray("zone-5", "temperature") = T

# No need to send an entire array or data ship, just overwrites the compute node values
getArray("zone-5", "pressure") = 5.0  
```

Ideally this interface should work on solver zones and other post extractions.

**Comment by RebelYoung** [comment]
I found a problem for the sort of data from `field_data` command, because of the multi blocks split by fluent.

**Comment by dnwillia-work** [comment]
Do you mean that the field data does not come in the expected order?

**Comment by RebelYoung** [comment]
> Do you mean that the field data does not come in the expected order?

yes, it is different that the data just has  the regional order in their domain, which is split by fluent in N-process mode.
You can found the `field_data` got the same data as GUI `xy-plot write` command.
The number of the points would be not certain, because of N-process mode. 
 But `tui.file.write_profile` is stable.

**Comment by dnwillia-work** [comment]
Probably the best that one could do for cells, faces or nodes is reorder it into the serial order.  For extracted data (eg: solution data on a cut plane) I'm not sure, you could maybe reorder by global ID for element data by the cut cell IDs but for nodes one would need an ordering policy.

**Comment by h-krishnan** [comment]
You might be able to access the cell/face ID as a field and use that to sort the data to get a partition independent array.

**Comment by dnwillia-work** [comment]
Yeah, maybe.  I can't seem to figure out if that's possible right now.  There's no easy API to look at the available fields to see if that's one of them and it's definitely not there with the mesh data.

**Comment by RebelYoung** [comment]
As the following example:

**2d, 40k cells, outer-flow, 2/4 process**
There are two wall-type boundary condition named `up` and `down`,  curves from (0,0) to (1,0) having **150** points respectively.
I wanna get the wall-type surface nodes data by `field_data` , ordered by `x-coordinate`, for aviod reading and writing texts to accelerating the program.
However, the data has different order depending on the partitioning, obtained from the command. Compared with GUI and TUI commands, `xy-plot` and `write profile`, I found the data is as same as `Results-plot-xyplot`. 
If you choose the `xyplot` writing data, the number of the points raises, depending on whether the surface was split into different partitions in fluent. In addition, the data in partitions maybe sorted by ID not x-coordinate.
![single process](https://user-images.githubusercontent.com/59256512/212787308-0532d790-7c8b-4a12-b10e-ff100008e331.png)
The quantity is right 150, and the order is decided by ID.
But, in 2 or 4 process mode, the sequence has subsequences, which have local order obviously.
![image](https://user-images.githubusercontent.com/59256512/212787830-b320fcc7-5e8d-4dbe-8208-08c481258d79.png)
![image](https://user-images.githubusercontent.com/59256512/212788190-91dc0c07-87c6-4fe0-bf4c-a91143c94c93.png)
![image](https://user-images.githubusercontent.com/59256512/212788246-f03d71db-17f2-4e79-a52d-9bbb90b8d3de.png)
![image](https://user-images.githubusercontent.com/59256512/212788664-61206cca-dd68-4e79-af8c-8673aa8892ef.png)

The local order is not certain because the topo in mesh partitions is not fixed.

**Comment by RebelYoung** [comment]
Another idea is create a new function in `field_data` to obtain data from `write profile`, outputing the face-center values and having excepted order.

**Comment by dnwillia-work** [comment]
Yeah, ok.  I managed to figure out how you can get the cell id data:
```
session.file.read(file_type="case", file_name="helix.cas.h5")
fd = session.field_data
cid = fd.get_scalar_field_data(field_name="cell-id", surface_name = "wall", node_value=False)
```
So, you could sort the data on faces or cells using that as proposed by Krishan.

I can't see a way to get the face or node IDs, which would be more optimal.  if you pass  `node_value=True` there (or not at all) Fluent seems to reconstruct the cell IDs on the nodes.

**Comment by seanpearsonuk** [comment]
> 

In general, you can call:

```
>>> get_data = s.field_data.get_scalar_field_data
>>> get_data.field_name.allowed_values()
['abs-angular-coordinate', 'angular-coordinate', 'anisotropic-adaption-cells', 'axial-coordinate', 'boundary-cell-dist', 'boundary-layer-cells', 'boundary-normal-dist', 'boundary-volume-dist', 'cell-element-type', 'cell-equiangle-skew', 'cell-equivolume-skew', 'cell-id', 'cell-parent-index', 'cell-partition-active', 'cell-partition-stored', 'cell-refine-level', 'cell-type', 'cell-volume', 'cell-volume-change', 'cell-wall-distance', 'cell-weight', 'cell-zone', 'face-area-magnitude', 'face-handedness', 'interface-overlap-fraction', 'mark-poor-elements', 'orthogonal-quality', 'partition-neighbors', 'radial-coordinate', 'smoothed-cell-refine-level', 'x-coordinate', 'x-face-area', 'y-coordinate', 'y-face-area', 'z-coordinate', 'z-face-area']
>>> get_data.surface_name.allowed_values()
['default-interior', 'pressure-outlet-7', 'symmetry', 'velocity-inlet-5', 'velocity-inlet-6', 'wall', 'z=0_out']
```

**Comment by RebelYoung** [comment]
> > 
> 
> In general, you can call:
> 
> ```
> >>> get_data = s.field_data.get_scalar_field_data
> >>> get_data.field_name.allowed_values()
> ['abs-angular-coordinate', 'angular-coordinate', 'anisotropic-adaption-cells', 'axial-coordinate', 'boundary-cell-dist', 'boundary-layer-cells', 'boundary-normal-dist', 'boundary-volume-dist', 'cell-element-type', 'cell-equiangle-skew', 'cell-equivolume-skew', 'cell-id', 'cell-parent-index', 'cell-partition-active', 'cell-partition-stored', 'cell-refine-level', 'cell-type', 'cell-volume', 'cell-volume-change', 'cell-wall-distance', 'cell-weight', 'cell-zone', 'face-area-magnitude', 'face-handedness', 'interface-overlap-fraction', 'mark-poor-elements', 'orthogonal-quality', 'partition-neighbors', 'radial-coordinate', 'smoothed-cell-refine-level', 'x-coordinate', 'x-face-area', 'y-coordinate', 'y-face-area', 'z-coordinate', 'z-face-area']
> >>> get_data.surface_name.allowed_values()
> ['default-interior', 'pressure-outlet-7', 'symmetry', 'velocity-inlet-5', 'velocity-inlet-6', 'wall', 'z=0_out']
> ```

What's your `pyfluent version` and `fluent version` ？
It failed in `0.11.0` and `2022R2`.

**Comment by seanpearsonuk** [comment]
> > > 
> > 
> > 
> > In general, you can call:
> > ```
> > >>> get_data = s.field_data.get_scalar_field_data
> > >>> get_data.field_name.allowed_values()
> > ['abs-angular-coordinate', 'angular-coordinate', 'anisotropic-adaption-cells', 'axial-coordinate', 'boundary-cell-dist', 'boundary-layer-cells', 'boundary-normal-dist', 'boundary-volume-dist', 'cell-element-type', 'cell-equiangle-skew', 'cell-equivolume-skew', 'cell-id', 'cell-parent-index', 'cell-partition-active', 'cell-partition-stored', 'cell-refine-level', 'cell-type', 'cell-volume', 'cell-volume-change', 'cell-wall-distance', 'cell-weight', 'cell-zone', 'face-area-magnitude', 'face-handedness', 'interface-overlap-fraction', 'mark-poor-elements', 'orthogonal-quality', 'partition-neighbors', 'radial-coordinate', 'smoothed-cell-refine-level', 'x-coordinate', 'x-face-area', 'y-coordinate', 'y-face-area', 'z-coordinate', 'z-face-area']
> > >>> get_data.surface_name.allowed_values()
> > ['default-interior', 'pressure-outlet-7', 'symmetry', 'velocity-inlet-5', 'velocity-inlet-6', 'wall', 'z=0_out']
> > ```
> 
> What's your `pyfluent version` and `fluent version` ？ It failed in `0.11.0` and `2022R2`.

You should only need a later version of PyFluent; 0.12.3 is out.
