### ISSUE TITLE
Doc Builds are Incomplete

### ISSUE THREAD

**Issue by dnwillia-work** [ansys/pyfluent#575]
So, regarding building the documentation there is an issue currently for the autogenerated documentation.

If you do a `make clean` and then `make html` in the doc area it needs to be a clean documentation build.  `make clean` should delete all the documentation, including all of the autogenerated documentation files, then `make html` should execute everything necessary to build the entire documentation, including a rebuild of the autogenerated files.

What happens currently is that the codegen scripts which build some of the documentation are not executed when you call `make html` so if the generated content is updated by a PR (eg the `codgen/data` area or by Fluent itself) then `make html`  for the doc does not regenerate the parts that would get updated if the codegen scripts were run first.  This is one reason why the `settings_rstgen.py` script is called during a doc build.

**Comment by seanpearsonuk** [comment]
need to start generating doc rst files from Python rather than from grpc objects

**Comment by seanpearsonuk** [comment]
@mkundu1 what is the status of this?

**Comment by hpohekar** [comment]
@seanpearsonuk discussed with @mkundu1 and will start working soon.

**Comment by mkundu1** [comment]
@hpohekar We need to address the following issues in the present code related to codegen:

1. Some classes in datamodel like those for the command arguments are not generated as a part of codegen. We can support that.
2. .rst files are generated as part of tuigen and datamodelgen. We can separate that step to generate the .rst files from the generated Python classes. We are already doing that for settings API (described in the previous comments).

1 is more important as the generated classes will provide better documentation, intellisense. 2 is more of refactoring/maintenance change.

**Comment by hpohekar** [comment]
@mkundu1 

The current documentation for command arguments looks as follows - 

![image](https://github.com/ansys/pyfluent/assets/106588300/b91c2552-172a-42ac-9654-f6ef1d0e760d)

https://fluent.docs.pyansys.com/version/stable/api/meshing/datamodel/meshing/File/index.html

Could you please share link of expected class docstring from PyFluent public documentation for reference, so that we can get idea about how new documentation should look like for command argument.

Thank you.

**Comment by hpohekar** [comment]
> @hpohekar We need to address the following issues in the present code related to codegen:
> 
> 1. Some classes in datamodel like those for the command arguments are not generated as a part of codegen. We can support that.
> 2. .rst files are generated as part of tuigen and datamodelgen. We can separate that step to generate the .rst files from the generated Python classes. We are already doing that for settings API (described in the previous comments).
> 
> 1 is more important as the generated classes will provide better documentation, intellisense. 2 is more of refactoring/maintenance change.

PR for 2nd point - https://github.com/ansys/pyfluent/pull/2663

**Comment by hpohekar** [comment]
https://github.com/ansys/pyfluent/issues/3330
