### ISSUE TITLE
GRPC ERROR from incomplete argument input

### ISSUE THREAD

**Issue by egravenh** [ansys/pyfluent#580]
Reproducible in Python ver. 3.9 and 3.8

Steps:

     1. Launch IDLE and enter the following:

import ansys.fluent.core as pyfluent
session = pyfluent.launch_fluent(precision="double", processor_count=4)
pyfluent.set_log_level('DEBUG')

     2. Manually type the following in the Shell:
session.solver.tui.file.read_case_data(

The following error is printed:
![image](https://user-images.githubusercontent.com/107507511/176749616-be915fb6-4f1b-40ce-b78e-bf678d2b0e03.png)

This is also reproducible for other commands (-i.e. session.solver.tui.mesh.scale(....))

**Comment by seanpearsonuk** [comment]
@mkundu1 @ypatel-qa @egravenh @cj-hodgson 

I couldn't reproduce this with the latest build
