### ISSUE TITLE
Fluent console output not printed correctly in python interpreter

### ISSUE THREAD

**Issue by egravenh** [ansys/pyfluent#581]
Reproducible in Python ver. 3.9 and 3.8

Steps:

     1. Place case file in working directory (download from link: https://tfs.ansys.com:8443/tfs/FluentTesting/FluentTesting/_git/matrix?path=%2FPARAM_steady_basic%2Fstd%2Felbow_param.cas.h5&version=GBdevelop)
     2. Launch IDLE and enter the following:
import ansys.fluent.core as pyfluent
session = pyfluent.launch_fluent(precision="double", processor_count=4)
session.solver.tui.file.read_case(case_file_name="elbow_param.cas.h5") 
pyfluent.set_log_level('DEBUG')
from ansys.fluent.core.services.scheme_eval import Symbol
session.scheme_eval.eval((Symbol("list-input-parameters"),)) 

A formatted parameter list is printed in the Fluent Console, but fails to fully print in the IDLE Shell:
![console_output](https://user-images.githubusercontent.com/107507511/176756995-d39f6e9f-c5a3-4bef-9429-0c37ace6c5fa.png)

**Comment by seanpearsonuk** [comment]
@mkundu1 not forwarding this to Fluent.  We need to understand more here.

**Comment by seanpearsonuk** [comment]
cannot reproduce
