### ISSUE TITLE
run_calculation object name contains a verb, implying method

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#683]
`run_calculation` sounds like a method because it begins with a verb, followed by a direct object noun.
I would like to request rename of this node. `calculation` might be OK.

**Comment by seanpearsonuk** [comment]
[FLUENT US 684790]

**Comment by dnwillia-work** [comment]
I've got to agree with this suggestion but it requires changing it inside Fluent.  First we should change it there, then we can do it in the API.
