### ISSUE TITLE
Fluent Case tu PyFluent

### ISSUE THREAD

**Issue by ehsansadeghi1** [ansys/pyfluent#697]
Would be nice if there could be a way to export the fluent case to pyfluent format directly. The journal file for fluent case is not possible to translate to pyfluent easily.

**Comment by tone-cukon** [comment]
Are you talking about reading a fluent case file with pyfluent? Shouldnt that be possible now?

**Comment by tone-cukon** [comment]
When using examples from documentation it works just fine, but when I try to read my own fluent case/data file with pyfluent I get the following error:
root         ERROR    GRPC_ERROR: File "airfoil_export_cas_and_data_from_fluent.cas.h5" not found!
Error Object: #f

**Comment by dnwillia-work** [comment]
I'll guess that you mean that you want to translate a Fluent TUI journal into a PyFluent journal?   If so, this is being worked on for a future release of Fluent.

**Comment by seanpearsonuk** [comment]
Transitioning to all aspects of modern data is a long time objective broader than the PyFluent project. Closing.
