### ISSUE TITLE
TUI command not working using []

### ISSUE THREAD

**Issue by GbrMnz** [ansys/pyfluent#943]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Translating the tui command:
`/file/export/common-fluids-format-post export_test1 slice_test1 () pressure ()()() `
I execute, as suggested in the [user guide](https://fluent.docs.pyansys.com/user_guide/tui_commands.html#ref-user-guide-tui-commands):
`ss.tui.file.export.common_fluids_format_post('export_test1', 'slice_test1', [], 'pressure', [], [], [])`
wich throws:
`invalid command ['()]`

It works with:
`ss.tui.file.export.common_fluids_format_post('export_test1', 'slice_test1', '()', 'pressure', '()', '()', '()')`

### 📝 Steps to reproduce

- launch session
- read case-dat
- execute tui command

### 💻 Which operating system are you using?

Linux

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
aiohttp==3.8.1
aiosignal==1.2.0
ansys-api-fluent==0.3.1
ansys-api-mapdl==0.5.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-corba==0.1.1
ansys-fluent-core==0.11.0
ansys-fluent-visualization==0.5.0
ansys-mapdl-core==0.63.2
ansys-mapdl-reader==0.52.0
ansys-platform-instancemanagement==1.0.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
async-timeout==4.0.2
attrs==22.1.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
cffi==1.15.1
charset-normalizer==2.1.1
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.0.0
fastjsonschema==2.16.1
fonttools==4.37.1
frozenlist==1.3.1
geomdl==5.3.1
googleapis-common-protos==1.56.4
grpcio==1.48.1
h5py==3.7.0
idna==3.4
imageio==2.21.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
install==1.3.5
ipycanvas==0.13.1
ipyevents==2.0.1
ipykernel==6.15.3
ipython==8.5.0
ipython-genutils==0.2.0
ipyvtklink==0.2.2
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.16.0
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
kiwisolver==1.4.4
lxml==4.9.1
MarkupSafe==2.1.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack-python==0.5.6
multidict==6.0.2
nbclient==0.6.8
nbconvert==7.0.0
nbformat==5.5.0
nest-asyncio==1.5.5
notebook==6.4.12
numpy==1.23.3
opencv-python==4.6.0.66
packaging==21.3
pandas==1.4.4
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
pkgutil_resolve_name==1.3.10
plotly==5.10.0
prometheus-client==0.14.1
prompt-toolkit==3.0.31
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
pyfluent==0.2.1
Pygments==2.13.0
pyiges==0.2.1
pyparsing==3.0.9
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyrsistent==0.18.1
PySide6==6.2.3
python-dateutil==2.8.2
pytz==2022.2.1
pyvista==0.36.1
pyvistaqt==0.7.0
pyzmq==23.2.1
qtconsole==5.3.2
QtPy==2.2.0
qtwidgets==0.18
scipy==1.9.1
scooby==0.6.0
Send2Trash==1.8.0
shiboken6==6.2.3
six==1.16.0
soupsieve==2.3.2.post1
stack-data==0.5.0
tenacity==8.1.0
terminado==0.15.0
tinycss2==1.1.1
tornado==6.2
tqdm==4.64.1
traitlets==5.4.0
vtk==9.1.0
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==4.0.3
wslink==1.8.2
yarl==1.8.1
zipp==3.8.1
```

**Comment by seanpearsonuk** [comment]
@GbrMnz Thanks, this scenario also works with `ss.tui.file.export.common_fluids_format_post('export_test1', 'slice_test1', [], "pressure", "quit", [], [])`, but if your version is as solid as I presume it is, then we will go with it in the docs. We will update the docs rather than the code.

@gyeole for any comment

**Comment by gyeole** [comment]
> @GbrMnz Thanks, this scenario also works with `ss.tui.file.export.common_fluids_format_post('export_test1', 'slice_test1', [], "pressure", "quit", [], [])`, but if your version is as solid as I presume it is, then we will go with it in the docs. We will update the docs rather than the code.
> 
> @gyeole for any comment

I think this issue was there initially but which was fixed in tui implementation. @mkundu1  Can you please add your comment. Thanks.

**Comment by seanpearsonuk** [comment]
Closing, according to @gyeole's comment

**Comment by JerolSOIBAM** [comment]
Hi, 

I am trying to export files of the whole domain in Ensight Gold format and here is an example i wrote 
`    fluent_instance.tui.file.export.ensight_gold(file_name=output_file_path, variables=["X Velocity"])
    fluent_instance.tui.file.export.ensight_gold(file_name=output_file_path, variables=["Temperature"])
    fluent_instance.tui.file.export.ensight_gold(file_name=output_file_path, variables=["Pressure"])
    `
But when I run this only the velocity gets exported nothing else. I get only this
exported_data.ensi.encas, exported_data.ensi.geo, exported_data.ensi.xml, exported_data.ensi.vel

Is there a way to do this? I could not find detailed documentation on this. Could you guide me what is the correct way to do this?

from the website i found this it dosent say much https://fluent.docs.pyansys.com/version/stable/api/solver/_autosummary/settings/ensight_gold.html#ensight-gold

**Comment by seanpearsonuk** [comment]
@JerolSOIBAM in future please could you open a new issue so that we and other users can find answered questions, but this is OK for this time. 

Please can you first check if Temperature and Pressure are exported if you run those directly as TUI commands in Fluent itself for the same setup. Thanks.
