### ISSUE TITLE
Monitors list should be allowed to be retrieved  before initializing

### ISSUE THREAD

**Issue by shihuAnsys** [ansys/pyfluent#955]
### 📝 Description of the feature

Hi, Guys

When I try to access the monitors list, I found you must initialize the case first or you will get a NULL list. Pls see the following script and output for your reference. This is not enough. For many users, they didn't want to initialize the case before finally submitting their cases to the remote clusters. They may just check their settings on their local low-configuration desktop. 

----------------------------------
```
>>> root.monitors_manager.get_monitor_set_names()
[]
>>>
>>> tui.solve.initialize.initialize_flow('ok')
/solve/initialize> invalid command [ok]
>>> root.monitors_manager.get_monitor_set_names()
['residual']
```
----------------------------------

Thanks!

### 💡 Steps for implementing the feature

root.monitors_manager.get_monitor_set_names()
tui.solve.initialize.initialize_flow('ok')
root.monitors_manager.get_monitor_set_names()

**Comment by shihuAnsys** [comment]
Hi, @seanpearsonuk @ajain-work I checked in the new version. Now it works. Thanks for your great work!

**Comment by seanpearsonuk** [comment]
Thanks for confirming this, @shihuAnsys
